### ISSUE TITLE
bitbucket_cloud.branch_for_base command problem 

### ISSUE THREAD

**Issue by alexandreraulin** [danger/danger#1017]
# Report

## What did you do?

Check the base branch of a PR with CircleCI and Bitbucket Cloud

## What did you expect to happen?

Danger should check the base branch with : `bitbucket_cloud.branch_for_base`

## What happened instead?

```
bundle exec danger --verbose
bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined method `[]' for nil:NilClass
 #  from Dangerfile:6
 #  -------------------------------------------
 #  
 >  failure "Please re-submit this PR to develop, we may have already fixed your issue." if bitbucket_cloud.branch_for_base != "develop"
 #  -------------------------------------------

  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb:108:in `branch_for_base'
  Dangerfile:6:in `block in parse'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/dangerfile.rb:200:in `eval'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/dangerfile.rb:196:in `parse'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/dangerfile.rb:274:in `run'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/danger_core/executor.rb:28:in `run'
  /usr/local/bundle/gems/danger-5.6.6/lib/danger/commands/runner.rb:68:in `run'
  /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/bundle/gems/danger-5.6.6/bin/danger:5:in `<top (required)>'
  /usr/local/bundle/bin/danger:17:in `load'
  /usr/local/bundle/bin/danger:17:in `<top (required)>'
Exited with code 1
```

## Your Environment

* Which CI are you running on?
CircleCI

* Are you running the latest version of Danger?
Yes (5.6.6)

* What is your Dangerfile?

  ```ruby
warn("PR is classed as Work in Progress") if bitbucket_cloud.pr_title.include? "WIP"
warn("Big PR") if git.lines_of_code > 500

fail("Please provide a summary in the Pull Request description") if bitbucket_cloud.pr_body.length < 5

failure "Please re-submit this PR to develop, we may have already fixed your issue." if bitbucket_cloud.branch_for_base != "develop"

  ```

* Others things 
- I've added DANGER_BITBUCKETCLOUD_USERNAME and DANGER_BITBUCKETCLOUD_PASSWORD variables in CircleCI
- bitbucket_cloud.pr_title works well
- I've the same problem with branch_for_head

**Comment by orta** [comment]
Cool, happy to accept a PR for it 👍

**Comment by alexandreraulin** [comment]
Hi, sorry I forgot one thing, according to the documentation (https://danger.systems/reference.html), this method are already implemented. I looked the code and this method exist [dangerfile_bitbucket_cloud_plugin.rb](https://github.com/danger/danger/blob/e9ee502bfd71850cea2d0dc4c531c5d76a6c7438/lib/danger/danger_core/plugins/dangerfile_bitbucket_cloud_plugin.rb#L107)
I can try to debug that but I'm a beginner in Ruby 😬
