### ISSUE TITLE
Can't import GitHub Dangerfile from GitLab

### ISSUE THREAD

**Issue by nicolas-brousse** [danger/danger#1037]
# Report

## What did you do?

I execute `danger` on my git project hosted in a self hosted GitLab instance.

## What did you expect to happen?

Running your Dangerfile without it crashing. And so be able to use import a `Dangerfile` from a GitHub repository.

## What happened instead?

```
Passing the note body as a Hash is deprecated.  You should just pass the String.
bundler: failed to load command: danger (/builds/group/project/vendor/bundle/ruby/2.4.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: 
[!] Invalid `temporary_danger.rb` file: syntax error, unexpected '<'
<html><body>You are being <a hr
 ^
/tmp/d20181117-41-1wr6db8/temporary_danger.rb:1: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
<html><body>You are being <a href="https://git.pa
                   ^
/tmp/d20181117-41-1wr6db8/temporary_danger.rb:1: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
ml><body>You are being <a href="https://gitlab.domain.tld
                              ^
/tmp/d20181117-41-1wr6db8/temporary_danger.rb:1: unknown regexp options - bdy
/tmp/d20181117-41-1wr6db8/temporary_danger.rb:1: syntax error, unexpected '<'
gn_in">redirected</a>.</body></html>
                              ^
/tmp/d20181117-41-1wr6db8/temporary_danger.rb:1: unterminated regexp meets end of file
 #  from /tmp/d20181117-41-1wr6db8/temporary_danger.rb:1
 #  -------------------------------------------
 >  <html><body>You are being <a href="https://gitlab.domain.tld/users/sign_in">redirected</a>.</body></html>
 #  -------------------------------------------

 #  from Dangerfile:1
 #  -------------------------------------------
 >  danger.import_dangerfile("pantographe/danger")
 #  -------------------------------------------

  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:201:in `eval'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:201:in `block in parse'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:197:in `parse'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:161:in `import_dangerfile_from_github'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:77:in `import_dangerfile'
  Dangerfile:1:in `block in parse'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:201:in `eval'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:201:in `block in parse'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:197:in `parse'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/dangerfile.rb:275:in `run'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/danger_core/executor.rb:28:in `run'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/lib/danger/commands/runner.rb:70:in `run'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /builds/group/project/vendor/bundle/ruby/2.4.0/gems/danger-5.8.0/bin/danger:5:in `<top (required)>'
  /builds/group/project/vendor/bundle/ruby/2.4.0/bin/danger:23:in `load'
  /builds/group/project/vendor/bundle/ruby/2.4.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* GitLab CI runner on my own server.
* `danger --version`: 5.8.0

  ```ruby
  danger.import_dangerfile("pantographe/danger")
  ```

**Comment by orta** [comment]
Interesting, looks like a pretty weird edge case. You're welcome to take a look at it 👍

**Comment by nicolas-brousse** [comment]
Looks like [Danger::DangerfileDangerPlugin#import_dangerfile_from_github](https://github.com/danger/danger/blob/56286aab4d3b9644eb6da5e81d0ab5b32575e9d4/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb#L156) use [`request_source`](https://github.com/danger/danger/blob/56286aab4d3b9644eb6da5e81d0ab5b32575e9d4/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb#L159) to download the `Dangerfile`.  
Since in my case I use GitLab, I guess that `danger.import_dangerfile` try to load it from my GitLab instance.

**Comment by orta** [comment]
Ah, I think that's a pretty reasonable expectationdefault then - so maybe some docs would need to change?

**Comment by nicolas-brousse** [comment]
Sounds weird for me to could prefix with `github:` and having Danger trying to load `Dangerfile` from my GitLab instance with `danger.import_dangerfile(github: "pantographe/danger")`.

I didn't notice before, but the example I copied was without `github:`/`gitlab:` key. But yes, if I use `github:` it use the same code and I was expected to have my GitHub `Dangerfile` loaded.

**Comment by prokopsimek** [comment]
Same issue here.

Using Gitlab CI

Dangerfile:
```
danger.import_dangerfile(github: "Applifting/danger")
```
