### ISSUE TITLE
Verbose log actually calls plugin method

### ISSUE THREAD

**Issue by Kyaak** [danger/danger#1041]
# Report

## What did you do?

Im trying to test my new plugin for [cobertura reports](https://github.com/Kyaak/danger-cobertura) but raising an issue with danger setup.

The problems seems to be when running in verbose, in my case testing with `danger local` which adds verbose by default.
I dont know if this would also happen without verbose.

## What did you expect to happen?

Dangerfile should succeed without even using my plugin.

## What happened instead?

The verbose execution of danger runs `danger_core/dangerfile.rb:151 - print_known_info` which crashes in `danger_core/dangerfile.rb:134 - block (2 levels) in method_values_for_plugin_hashes`.

What happens: it calls my function `show_coverage` and executes it. This raises an error because the required file is not set yet.

Adding a parameter to my function 'fixes' this issue.

```bash
bundler: failed to load command: danger (/Users/mschwamberger/.rvm/gems/ruby-2.5.1/bin/danger)
RuntimeError: SHOW_COVERAGE CALLED
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-cobertura-1.0.1/lib/cobertura/plugin.rb:41:in `show_coverage'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:134:in `block (2 levels) in method_values_for_plugin_hashes'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:122:in `map'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:122:in `block in method_values_for_plugin_hashes'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:118:in `each'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:118:in `flat_map'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:118:in `method_values_for_plugin_hashes'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:151:in `print_known_info'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:175:in `parse'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/danger_core/dangerfile.rb:273:in `run'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/commands/pr.rb:61:in `block in run'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/commands/local_helpers/local_setup.rb:38:in `setup'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/lib/danger/commands/pr.rb:60:in `run'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/gems/danger-5.8.2/bin/danger:5:in `<top (required)>'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/bin/danger:23:in `load'
  /Users/mschwamberger/.rvm/gems/ruby-2.5.1/bin/danger:23:in `<top (required)>'

```

## Your Environment

* Which CI are you running on?

>  Danger local

* Are you running the latest version of Danger?

>  Yes

* What is your Dangerfile?

  ```ruby

  #cobertura.report = "build/reports/cobertura/cobertura.xml"
  #cobertura.warn_if_file_less_than(percentage: 50)

  ```

Yes, my Dangerfile has only comment. 
I don't call the method `cobertura. show_coverage` but the `setup` of danger does it.

Is danger intended to work with method without parameters?

Similar issue: https://github.com/danger/danger/issues/959

**Comment by orta** [comment]
Yeah, this probably is a bug, that's meant to try and provide a summary of information at the end of a run and doing that by safely asking for info it can grab. Maybe it needs to be more conservative?

**Comment by Kyaak** [comment]
Yep, that's a nice idea.
Is there any reason that only methods without attributes are selected?

https://github.com/danger/danger/blob/b5b1ca80ff5f25cdd44cbdc2eb59ecbb4dfb18a7/lib/danger/danger_core/dangerfile.rb#L120

It seems you are trying to get a return value right?
https://github.com/danger/danger/blob/b5b1ca80ff5f25cdd44cbdc2eb59ecbb4dfb18a7/lib/danger/danger_core/dangerfile.rb#L134

Maybe we can access yard doc if available?

**Comment by orta** [comment]
I think the idea was (and at least within danger's core codebase) that a function without a param should be safe to call, but I dig that for plugins that's very reasonable to not be the case 

Maybe only the "core" plugins could be put in there?

**Comment by Kyaak** [comment]
Yeah, maybe at this point, only core plugins should be printed.

Relying on all plugins to be safe to call methods without parameters seems to be odd.
Furthermore this breaks quite the usage of the verbose log, since most plugin methods which execute their intended "plugin" functionality will have attributes.

The profit to print 1/5 methods, where actually all methods are interesting is not so high.

**Comment by benzimmer** [comment]
Any chance of getting this fixed any time soon? Asking for a friend 😬

**Comment by orta** [comment]
You're welcome to take a look 👍
