### ISSUE TITLE
Unable to Get Local Issuer Certificate

### ISSUE THREAD

**Issue by btzc** [danger/danger#1043]
# Report

## What did you do?
Run ```danger local```

## What did you expect to happen?
I expected the Dangerfile to be run against the most recent pull request

## What happened instead?
Got an SSL error saying that it couldn't get the local issuer certificate.

```
Turning on --verbose

Traceback (most recent call last):
	29: from /Users/my_user/.rbenv/versions/2.5.1/bin/danger:23:in `<main>'
	28: from /Users/my_user/.rbenv/versions/2.5.1/bin/danger:23:in `load'
	27: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/danger-5.8.2/bin/danger:5:in `<top (required)>'
	26: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	25: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/danger-5.8.2/lib/danger/commands/local.rb:55:in `run'
	24: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/danger-5.8.2/lib/danger/commands/local_helpers/local_setup.rb:32:in `setup'
	23: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/danger-5.8.2/lib/danger/request_sources/github/github.rb:117:in `fetch_details'
	22: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/octokit-4.13.0/lib/octokit/client/pull_requests.rb:33:in `pull_request'
	21: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/octokit-4.13.0/lib/octokit/connection.rb:19:in `get'
	20: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/octokit-4.13.0/lib/octokit/connection.rb:156:in `request'
	19: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	18: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:138:in `get'
	17: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/connection.rb:387:in `run_request'
	16: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/rack_builder.rb:143:in `build_response'
	15: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:119:in `call'
	14: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:146:in `call!'
	13: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:208:in `process'
	12: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:303:in `fetch'
	11: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
	10: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:38:in `call'
	 9: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
	 8: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
	 7: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:85:in `perform_request'
	 6: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:1213:in `get'
	 5: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:1455:in `request'
	 4: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
	 3: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 2: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:981:in `connect'
	 1: from /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/Users/my_user/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (Faraday::SSLError)
```

## Your Environment

* Which CI are you running on?
Jenkins, but this command was executed locally on the machine to test through the terminal. Am running MacOSX.

* Are you running the latest version of Danger?
5.8.2

* What is your Dangerfile?
  ```message("Hello, this worked")```

**Comment by btzc** [comment]
Yeah! So I've tried a few things. First I tried disabling using SSL to verify entirely using ```git config http.sslVerify false``` but still got the same output. I've also tested curling the Github API from that same machine using the authentication code I setup and it was able to give me a 200 response. If it helps I'm trying to set this up using Enterprise Github.

**Comment by orta** [comment]
Interesting, yeah, I'm unsure - it seems to be happening when the GitHub API asks for PR metadata via the API, maybe the environment var for redirecting to your GH enterprise is mis-configured?

**Comment by btzc** [comment]
I set the following environment variables before running danger locally:
```
export DANGER_GITHUB_HOST=our_github_host
export DANGER_GITHUB_API_BASE_URL=https://our_github_host/api/v3
export DANGER_GITHUB_API_TOKEN=our_authentication_token
```

I've tried setting the API to just http instead of https but it threw a different error:
```
/Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/danger-5.8.2/lib/danger/request_sources/github/github.rb:131:in `fetch_issue_details': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by keithmccall** [comment]
> I set the following environment variables before running danger locally:
> 
> ```
> export DANGER_GITHUB_HOST=our_github_host
> export DANGER_GITHUB_API_BASE_URL=https://our_github_host/api/v3
> export DANGER_GITHUB_API_TOKEN=our_authentication_token
> ```
> 
> I've tried setting the API to just http instead of https but it threw a different error:
> 
> ```
> /Users/my_user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/danger-5.8.2/lib/danger/request_sources/github/github.rb:131:in `fetch_issue_details': undefined method `[]' for nil:NilClass (NoMethodError)
> ```

In which file do you declare the environment variables when running locally?
