### ISSUE TITLE
Bitbucket Cloud: ParserError: 765: unexpected token at ''

### ISSUE THREAD

**Issue by RicardoBelchior** [danger/danger#1061]
# Report

## What did you do?

Run `bundle install` and `bundle exec danger`

## What did you expect to happen?

Running Danger without it crashing. It used to work before, can't recall anything that might have changed on our setup.

## What happened instead?

```
+ bundle exec danger
/usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/ci_source/support/find_repo_info_from_url.rb:22: warning: already initialized constant Danger::FindRepoInfoFromURL::REGEXPBB
/usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/ci_source/support/find_repo_info_from_url.rb:13: warning: previous definition of REGEXPBB was here
bundler: failed to load command: danger (/usr/local/bin/danger)
JSON::ParserError: 765: unexpected token at ''
  /usr/local/lib/ruby/2.5.0/json/common.rb:156:in `parse'
  /usr/local/lib/ruby/2.5.0/json/common.rb:156:in `parse'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/request_sources/bitbucket_cloud_api.rb:81:in `fetch_json'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/request_sources/bitbucket_cloud_api.rb:33:in `fetch_pr_json'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/request_sources/bitbucket_cloud.rb:44:in `fetch_details'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/danger_core/dangerfile.rb:266:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/danger_core/executor.rb:28:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/lib/danger/commands/runner.rb:70:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.11.0/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:23:in `load'
  /usr/local/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on?
Bitrise

* Are you running the latest version of Danger?
I don't specify it in the Gemfile, so yes:

```
...
Installing danger 5.11.0
Installing danger-junit 0.7.4
```

* What is your Dangerfile?

```ruby

modules = ["analytics", "app", "library", "podcast", "remote", "shared_resources"]
modules_src_dirs = modules.map { |m| m+"/src/main" }
modules_test_dirs = modules.map { |m| m+"/src/test" } + modules.map { |m| m+"/src/androidTest" }

has_app_changes = git.modified_files.any? { |w| modules_src_dirs.any? { |dir| w.include? dir } }
has_test_changes = git.modified_files.any? { |w| modules_test_dirs.any? { |dir| w.include? dir } }
is_version_bump = git.modified_files.include? "version.properties"

if has_app_changes && !has_test_changes && !is_version_bump
  warn("Tests were not updated", sticky: false)
end


# Let people say that this isn't worth a CHANGELOG entry in the PR if they choose
declared_trivial = (bitbucket_cloud.pr_title + bitbucket_cloud.pr_body).include?("#trivial") || !has_app_changes

# Warn if CHANGELOG was not updated
if !git.modified_files.include?("CHANGELOG.md") && !declared_trivial
  fail("Please include a CHANGELOG entry.", sticky: false)
end

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if bitbucket_cloud.pr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# Public install page
public_install_page_url = ENV['BITRISE_PUBLIC_INSTALL_PAGE_URL']
message("📱 [New app deployed to Bitrise](#{public_install_page_url})") if public_install_page_url

# Report results of unit tests
Dir["**/TEST-*.xml"].each do |file_name|
  junit.parse file_name
  junit.show_skipped_tests = true
  junit.report
end
  ```

**Comment by orta** [comment]
It's probably worth running this locally and echoing out what the JSON from bitbucket looks like, because that's what's failing to be parsed.

**Comment by RicardoBelchior** [comment]
By running locally you mean with `danger local` or `danger pr` ?

Running `danger local` , gives me:
```
/Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/local_git_repo.rb:61:in `raise_error_for_missing_remote': 
danger cannot find your git remote, please set a remote. And the repository must host on GitHub.com or GitHub Enterprise. (RuntimeError)
```
But I'm on Bitbucket, so I'm not sure if it's possible.

And running: `danger pr https://bitbucket.org/trinitymirror-ondemand/androidmirrornews/pull-requests/1319`

I get the output:

```
/Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/support/find_repo_info_from_url.rb:22: warning: already initialized constant Danger::FindRepoInfoFromURL::REGEXPBB
/Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/support/find_repo_info_from_url.rb:13: warning: previous definition of REGEXPBB was here
Traceback (most recent call last):
	16: from /Users/ricardobelchior/.rbenv/versions/2.5.3/bin/danger:23:in `<main>'
	15: from /Users/ricardobelchior/.rbenv/versions/2.5.3/bin/danger:23:in `load'
	14: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/bin/danger:5:in `<top (required)>'
	13: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	12: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/commands/pr.rb:57:in `run'
	11: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/commands/pr.rb:57:in `new'
	10: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
	 9: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/danger_core/environment_manager.rb:30:in `new'
	 8: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/local_git_repo.rb:45:in `initialize'
	 7: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/local_git_repo.rb:95:in `found_pull_request'
	 6: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/support/pull_request_finder.rb:17:in `call'
	 5: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/support/pull_request_finder.rb:31:in `check_if_any_pull_request!'
	 4: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/support/pull_request_finder.rb:51:in `pull_request'
	 3: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/ci_source/support/pull_request_finder.rb:82:in `remote_pull_request'
	 2: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/request_sources/bitbucket_server_api.rb:35:in `pull_request'
	 1: from /Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/request_sources/bitbucket_server_api.rb:40:in `fetch_pr_json'
/Users/ricardobelchior/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/danger-5.10.2/lib/danger/request_sources/bitbucket_server_api.rb:66:in `fetch_json': undefined method `request_uri' for #<URI::Generic:0x00007fcc16352318> (NoMethodError)
```

Sorry this is not very helpful. I'm glad to try out other things if you guide me through.

**Comment by RicardoBelchior** [comment]
Maybe stupid question... but is it possible to run danger locally, given that I'm working on a Bitbucket repository?

**Comment by orta** [comment]
If you use the ENV VARs in this CI Source: https://github.com/danger/danger/blob/master/lib/danger/ci_source/local_git_repo.rb

Then it should run locally.

Danger PR should support bitbucket, so maybe it's the same bug? That's a pretty [new feature](https://github.com/danger/danger/pull/1047) so might not be battle tested yet

**Comment by RicardoBelchior** [comment]
Looks like the new feature you mentioned is for BitbucketServer, whereas I'm on bitbucket cloud 😞 

Looking at the code in https://github.com/danger/danger/blob/master/lib/danger/ci_source/local_git_repo.rb
I don't see any mention to Bitbucket Cloud. I was hoping that bitbucket server would also work for bitbucket cloud, but it seems not. 

Any other tip to see why danger is failing with that `ParserError` (in my original question) ? 
Like running `bundle exec danger --verbose` or something similar...

**Comment by orta** [comment]
Yep, you're getting invalid JSON from the server, without being able to log it though it's hard to give any useful advice

**Comment by RicardoBelchior** [comment]
So, I decided to clone the repository and try running it on my machine... I add to change a lot of files and hardcoded some variables but finally got it running locally. And in the end... the danger script ran as expected. The question I now have is, why is it failing on my CI (Bitrise)? 

Along the way, I encountered the same error I was looking for (JSON::ParserError). It happened whenever the request `bitbucket_cloud_api#fetch_json` failed and returned an empty json. In my case it failed because of wrong environment variables for the DANGER_BITBUCKETCLOUD_USERNAME/PASSWORD. But it can probably fail for other reasons too..

Any tips?

**Comment by RicardoBelchior** [comment]
Ok, it now looks like the problem is fixed after changing some stuff on Bitrise. Looks like the environment variables were not being made available at runtime 🤷‍♂️ 

I think that, by now, I could prepare a pull request to allow running danger on bitbucket cloud, locally. Would you be interested on that ?

**Comment by orta** [comment]
Congrats!

Sure, works for me - I'd recommend adding a bunch of tests around it so that someone doesn't accidentally break it 👍

**Comment by orta** [comment]
( Though, as an Android dev (I think..) you might want to consider adding it to danger-js so that you could use [Danger Kotlin](https://github.com/danger/kotlin) )
