### ISSUE TITLE
Getting "Danger does not have write access to the PR to set a PR status." but can post to GitHub using a test script

### ISSUE THREAD

**Issue by rist** [danger/danger#1074]
# Report
We are using Danger with Jenkins for PR on our Github enterprise instance.
Since some days - which I'm afraid coincides with our update to Github Enterprise 2.16.0 we get the the error message "Danger does not have write access to the PR to set a PR status.".
I created a sample ruby script using the same access token and am able to update the status of our PRs.
I have the feeling that setting the status sometimes work in the first run, but not in later cases.

## What did you do?
Run bundle exec danger as last step in our Jenkins task.
We pinned to the most recent danger version in our Gemfile (5.12.0)

## What did you expect to happen?
That danger is able to correctly update my PRs.

## What happened instead?
I get this output in my Jenkins console:
+ bundle exec danger --verbose
All green. Yay.

Danger does not have write access to the PR to set a PR status.

## Your Environment
Jenkins
Danger 5.12

  ```
  swiftlint.lint_files

  failure "PR title should match Angular JS conventions - see https://gist.github.com/stephenparish/9941e89d80e2bc58a153 - e.g. 'feat: GG-1234 add kitchen sink'" if github.pr_title.match(/^(feat|fix|chore|impr)(\([a-zA-Z]+\))?:( [a-zA-Z][a-zA-Z0-9 ,'\-\._!\u2019]*[^\.])$/) == nil

  failure "Please add \"ready to merge\" label." if github.pr_labels.detect{|l| l.include? "ready to merge"} == nil

  failure "Please remove \"blocked\" label." if github.pr_labels.detect{|l| l.include? "blocked"} != nil
  ```

**Comment by orta** [comment]
There's not much going on in that part fo the codebase, we just all the GitHub API client set the status

https://github.com/danger/danger/blob/9321658a2ef520bf0f625f342737cdb70c55e2fa/lib/danger/request_sources/github/github.rb#L212-L244

Perhaps you could fork and echo out the error message, and that could provide a better clue on what's going on?

**Comment by rist** [comment]
I forked and added some debug statements and get this:

```
For 'properties/target_url', nil is not a string. // See: https://developer.github.com/enterprise/2.16/v3/repos/statuses/#create-a-status
["/Users/georgegoci/gems/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in `on_complete'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'", "/Users/georgegoci/gems/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'", "/Users/georgegoci/gems/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/request/retry.rb:128:in `call'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'", "/Users/georgegoci/gems/ruby/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'", "/Users/georgegoci/gems/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'", "/Users/georgegoci/gems/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/connection.rb:156:in `request'", "/Users/georgegoci/gems/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/connection.rb:28:in `post'", "/Users/georgegoci/gems/ruby/2.3.0/gems/octokit-4.13.0/lib/octokit/client/statuses.rb:43:in `create_status'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/lib/danger/request_sources/github/github.rb:222:in `submit_pull_request_status!'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/lib/danger/request_sources/github/github.rb:204:in `update_pull_request!'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/lib/danger/danger_core/dangerfile.rb:247:in `post_results'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/lib/danger/danger_core/dangerfile.rb:278:in `run'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/lib/danger/danger_core/executor.rb:28:in `run'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/lib/danger/commands/runner.rb:70:in `run'", "/Users/georgegoci/gems/ruby/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'", "/Users/georgegoci/gems/ruby/2.3.0/gems/danger-5.12.0/bin/danger:5:in `<top (required)>'", "/Users/georgegoci/gems/ruby/2.3.0/bin/danger:22:in `load'", "/Users/georgegoci/gems/ruby/2.3.0/bin/danger:22:in `<top (required)>'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `load'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:74:in `kernel_load'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli/exec.rb:28:in `run'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:424:in `exec'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:27:in `dispatch'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/cli.rb:18:in `start'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:30:in `block in <top (required)>'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'", "/Library/Ruby/Gems/2.3.0/gems/bundler-1.16.3/exe/bundle:22:in `<top (required)>'", "/usr/local/bin/bundle:22:in `load'", "/usr/local/bin/bundle:22:in `<main>'"]
All green. Good on 'ya.
```

after putting some hardcoded value into details_url it works

**Comment by orta** [comment]
Oh, interesting, II think the detection of the issue comment URL must somehow be failing - II think the easiest fix is to make the line `target_url: details_url` be `target_url: details_url || "https://danger.systems/ruby` then it won't break, but you can't follow the link back

**Comment by bibendi** [comment]
I got the same error today. I have a private repo on github. I'm going to dive into remote debugging tomorrow :slightly_smiling_face:

**Comment by bibendi** [comment]
Sorry for the noise.
Somehow the `Commit status` permission was disabled.
![image](https://user-images.githubusercontent.com/320886/73209323-16e19a00-4159-11ea-8842-e8ad09bb891e.png)

**Comment by rogerluan** [comment]
@bibendi where is that page? I'm facing a similar issue but couldn't find that specific page of your screenshot 😅

**Comment by kazaneshimizu** [comment]
Same error, I granted permission for `statuses: write` and it worked.

ref: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by sandstrom** [comment]
I don't think this is a bug in Danger, and I'd vote for closing this issue.

Perhaps, the documentation could be improved to mention that when Danger is running in Github actions, it needs the appropriate permissions.

```yaml
permissions:
  pull-requests: write # required for Danger to post comments
  issues: write # required for Danger to post comments
  # potentially other permissions, as needed
```
