### ISSUE TITLE
Gitlab inline comments fail to submit

### ISSUE THREAD

**Issue by JanPawlov** [danger/danger#1092]
After updating danger gem to 5.16.0 our GitlabCI script fails,
 ```
bundle update
bundle exec danger
```
 results in 
```ruby
/var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: 400 (Bad request) "Note {:line_code=>["can't be blank", "must be a valid line code"]}" not given. Request URI: https://git.temp.pl/api/v4/projects/my_project/merge_requests/28/discussions (Gitlab::Error::BadRequest)
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/client/merge_requests.rb:235:in `create_merge_request_discussion'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/request_sources/gitlab.rb:401:in `block in submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/request_sources/gitlab.rb:359:in `reject'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/request_sources/gitlab.rb:359:in `submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/request_sources/gitlab.rb:320:in `submit_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/request_sources/gitlab.rb:172:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/request_sources/gitlab.rb:139:in `update_pull_request!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.0/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```

## Your Environment

* Which CI are you running on? 

Gitlab CI
```
Running with gitlab-runner 11.7.0 (8bb608ff)
```
* Are you running the latest version of Danger?
```ruby
...
Using git 1.5.0
Fetching danger 5.16.0
Installing danger 5.16.0
Using danger-plugin-api 1.0.0
Using ruby-ll 2.1.2
Using oga 2.15
Using danger-android_lint 0.0.6
Using ox 2.10.0
Using danger-checkstyle_format 0.1.1
Using mime-types-data 3.2018.0812
Using mime-types 3.2.2
Using multi_xml 0.6.0
Using httparty 0.16.4
Fetching gitlab 4.10.0
Installing gitlab 4.10.0
Using danger-gitlab 6.0.0
...
```
* What is your Dangerfile?

```ruby
warn("MR is classed as Work in Progress") if gitlab.mr_title.include? "[WIP]"

warn("Detekt config has changed") if git.modified_files.include? "detekt-config.yml"

failure "Please provide a summary in the Merge Request description" if gitlab.mr_body.length < 5

# Warn when there is a big MR
warn("Big MR") if git.lines_of_code > 500

# detekt
checkstyle_format.base_path = Dir.pwd

checkstyle_format.report "/builds/my_project/app/build/reports/detekt/detekt.xml"

# AndroidLint
# android_lint.lint(inline_mode: true) currently, only for github
android_lint.report_file = "app/build/reports/lint-results.xml"
android_lint.lint
 ```

**Comment by JanPawlov** [comment]
{"version":"11.8.0","revision":"ce13864"}

**Comment by pbendersky** [comment]
I can't reproduce it... any other info you can provide me? Are you using forks? What branch are you trying to merge to?

**Comment by JanPawlov** [comment]
There are no forks in the project, MR is to default branch

**Comment by pbendersky** [comment]
Just was able to reproduce it. I'll try to fix it during the day.
