### ISSUE TITLE
Regression - Gitlab inline comments fail to submit

### ISSUE THREAD

**Issue by JanPawlov** [danger/danger#1097]
#Report
After 5.16.1 update inline comments worked, unfortunately it started to fail in a new project. MR target branch is set to default.
```
bundle update
bundle exec danger
```

results again (#1092) with:
```
/var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: 400 (Bad request) "Note {:line_code=>["can't be blank", "must be a valid line code"]}" not given. Request URI: https://git.domain.com/api/v4/projects/new_project/merge_requests/1/discussions (Gitlab::Error::BadRequest)
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/client/merge_requests.rb:235:in `create_merge_request_discussion'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:414:in `block in submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:374:in `reject'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:374:in `submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:335:in `submit_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:187:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```
## Your Environment

* Which CI are you running on?

Gitlab CI 

`{"version":"11.8.0","revision":"ce13864"}`

* Are you running the latest version of Danger?

```
...
Using claide 1.0.2
Using claide-plugins 0.9.2
Fetching danger 5.16.1 (was 5.14.0)
Installing danger 5.16.1 (was 5.14.0)
Using danger-plugin-api 1.0.0
Using ruby-ll 2.1.2
Using oga 2.15
Using danger-android_lint 0.0.6
Using ox 2.10.0
Using danger-checkstyle_format 0.1.1
Using mime-types-data 3.2018.0812
Using mime-types 3.2.2
Using multi_xml 0.6.0
Using httparty 0.16.4
Fetching gitlab 4.10.0 (was 4.9.0)
Installing gitlab 4.10.0 (was 4.9.0)
Using danger-gitlab 6.0.0
...
```
* What is your Dangerfile?

 ```ruby
declared_trivial = (gitlab.mr_title + gitlab.mr_body).include?("trivial")

warn("MR is classed as Work in Progress") if gitlab.mr_title.include? "[WIP]"

failure "Please provide a summary in the Merge Request description" if gitlab.mr_body.length < 5

# Warn when detekt config has changed
warn("Detekt config has changed") if git.modified_files.include? "detekt-config.yml"

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# detekt
checkstyle_format.base_path = Dir.pwd
checkstyle_format.report "/builds/group/project/app/build/reports/detekt/detekt.xml"

# AndroidLint
android_lint.report_file = "app/build/reports/lint-results.xml"
android_lint.lint
```

**Comment by pbendersky** [comment]
Do you know if the linter message is on one of the modified files or not? Thank you

**Comment by JanPawlov** [comment]
OK. I did some testing.  I resolved all issues found by [Detekt](https://github.com/arturbosch/detekt), job succeded.

Then I noticed I did not use inline mode, so i switched to `android_lint.lint(inline_mode: true)`, job succeded and linter messages were successfully added to changed files.

After that, I reverted all the changes that were caught by detekt initially. Some of them were successfully commented on the diff, but the job failed. So, the issue seems to be caused by some of detekt issues. 

For example, job succeded when detekt found: 
```
Ruleset: exceptions - 20min debt
	TooGenericExceptionCaught - [e] at /builds/...
Ruleset: formatting - 5min debt
	SpacingAroundCurly - [PsiElement(LBRACE)] at /builds/...
```

But failed when 
```
Ruleset: exceptions - 20min debt
	TooGenericExceptionCaught - [e] at /builds/...
Ruleset: formatting - 10min debt
	NoUnusedImports - [Element(IMPORT_DIRECTIVE)] at /builds/...
	SpacingAroundCurly - [PsiElement(LBRACE)] at /builds/...
```
Despite the fact all issues that are in the changed files (NoUnusedImports, SpacingAroundCurly) are inlined were successfully commented.

On my last resort I removed all detekt issues (except TooGenericExceptionCaught, which is not in the modified files), and job failed with:

```
/var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: Bad Request. Request URI: https://git.domain.com/api/v4/projects/my_project/merge_requests/1/discussions/98cfb80d9b3ff234b5bdc2124b8ad98d2d4cb65b/notes/35931 (Gitlab::Error::BadRequest)
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/client/merge_requests.rb:284:in `update_merge_request_discussion_note'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:421:in `block in submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:374:in `reject'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:374:in `submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:335:in `submit_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:187:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/gems/danger-5.16.1/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```

This might indicate problems with resolving an issue that is no longer in the code. I'll try to find some more patterns tommorow.
