### ISSUE TITLE
Danger fails on buddybuild when running on PR from a fork

### ISSUE THREAD

**Issue by Goos** [danger/danger#1103]
We just set up danger in our repository and it fails when running on PRs from forks.

## What did you do?

```
bundle install  
bundle exec danger --fail-on-errors=true
```

## What did you expect to happen?

It would run danger and find the branch & commit in my fork.

## What happened instead?

It failed to find the commits and/or the branch:
```
fatal: Couldn't find remote ref refs/heads/event-ordering
fatal: Couldn't find remote ref refs/heads/event-ordering
fatal: Couldn't find remote ref refs/heads/event-ordering
fatal: Couldn't find remote ref refs/heads/event-ordering
bundler: failed to load command: danger (/usr/local/bin/danger)
RuntimeError: Commit c2b6bb0b doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed.
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/scm_source/git_repo.rb:111:in `raise_if_we_cannot_find_the_commit'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/scm_source/git_repo.rb:93:in `ensure_commitish_exists_on_branch!'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/request_sources/github/github.rb:112:in `setup_danger_branches'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/danger_core/environment_manager.rb:57:in `ensure_danger_branches_are_setup'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/danger_core/dangerfile.rb:259:in `setup_for_running'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/danger_core/dangerfile.rb:270:in `run'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/danger_core/executor.rb:29:in `run'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/lib/danger/commands/runner.rb:72:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/danger-5.14.0/bin/danger:5:in `<top (required)>'
/usr/local/bin/danger:22:in `load'
/usr/local/bin/danger:22:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? 
Buddybuild
* Are you running the latest version of Danger?
Yup
* What is your Dangerfile?
```
warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"

swiftlint.lint_files fail_on_error: true
```

**Comment by orta** [comment]
Did that commit exist in the repo?

**Comment by Goos** [comment]
@orta yeah the commit exists but it seems like it's trying to look at the wrong remote (origin) instead of my fork.

**Comment by orta** [comment]
Ah cool, might be worth looking that the [buddy build](https://github.com/danger/danger/blob/master/lib/danger/ci_source/buddybuild.rb) part of the codebase and compare it to the env vars that bb shows and see If they need changing

**Comment by Goos** [comment]
@orta thanks for the quick response – this part right [here](https://github.com/danger/danger/blob/master/lib/danger/ci_source/buddybuild.rb#L59) looks like it's defaulting to the origins, if I'm reading it correctly. Would it be possible to use the slug to construct a URL instead somehow?

**Comment by orta** [comment]
I'm unsure, I've never used buddy build: maybe there's an API? maybe there's another remote on the repo? Maybe there's another env var?

**Comment by Goos** [comment]
Hey! Gonna resurrect this issue because I forgot about it for a while. @orta do you know what the `repo_url` is actually used for? It seems to me that we should be able to know where to fetch the changes from even without the `repo_url` since we have the `repo_slug` (i.e. `{username}/{repo}`). Is there any way we can construct a `repo_url` by using the slug somehow?

**Comment by JohnRoesler** [comment]
I'm having this same issue with github actions - danger can't find the commit from the forked repo because it appears to be looking in the origin.

**Comment by Kaspik** [comment]
Yes, happening for us too on public Open Source repo. Can we somehow work around that?

```
bundler: failed to load command: danger (/usr/local/lib/ruby/gems/2.6.0/bin/danger)
105
RuntimeError: Commit f28e72a0 doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed.
```

**Comment by Kaspik** [comment]
@orta Let me know if you have any idea what to do here - but it could be easy for someone who knows where is Danger looking for wrong remote?

**Comment by orta** [comment]
it looks like danger is not finding the head commit, so the pull from the remote repo seems to be failing somewhere? 

I can't really remember where all that code is anymore though, so I'm afraid you'll have to do some digging to find the commands it runs and try see why danger can't find the commits.

**Comment by Kaspik** [comment]
@orta I already did today, and I think I'm not sure if `setup_danger_branches` in `github.rb:112` is getting the right stuff, if so, then `ensure_commitish_exists_on_branch` (`git_repo:99`) uses `origin` as remote and it might not be the correct one - and I wasn't able to dig into that and get the info from that.

I just checked other repos and it looks like **all frameworks / repos / projects** not only on Github have the same issue with Forks and some of them just removed Danger for open source with many fork PRs... which is sad 😢 

```
/usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/scm_source/git_repo.rb:117:in `raise_if_we_cannot_find_the_commit'
107
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/scm_source/git_repo.rb:99:in `ensure_commitish_exists_on_branch!'
108
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/request_sources/github/github.rb:112:in `setup_danger_branches'
109
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/environment_manager.rb:58:in `ensure_danger_branches_are_setup'
110
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:259:in `setup_for_running'
111
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:270:in `run'
112
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/executor.rb:29:in `run'
113
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/lib/danger/commands/runner.rb:73:in `run'
114
  /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
115
  /usr/local/lib/ruby/gems/2.6.0/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
116
  /usr/local/lib/ruby/gems/2.6.0/bin/danger:23:in `load'
117
  /usr/local/lib/ruby/gems/2.6.0/bin/danger:23:in `<top (required)>'
```

I gave up after about two hours...

**Comment by orta** [comment]
I'd be very surprised if all projects using forks are seeing this, this issue has been open for a year and danger is used extensively in open source projects. I'm not sure why it's working in these cases though.

The code here looks correct though, both head and base references are requested - and if those commands fail then it should also raise I believe

https://github.com/danger/danger/blob/c51e39c61c814f545c4c88c0179920684b620e56/lib/danger/request_sources/github/github.rb#L99-L114

**Comment by Kaspik** [comment]
And isn't that exactly the problem?
```
github.rb:112:in `setup_danger_branches'
```
which means
```
scm.ensure_commitish_exists_on_branch! head_branch, head_commit 
```
raises an issue...

It seems like `git_fetch_branch_to_depth`is fetching from wrong place then.

Can you point me to any open source repo with Danger and PR from fork that works, please? I'll do my best to find out what's happening...

**Comment by orta** [comment]
This repo has had a few PRs from forks, here's a PR which still has a danger comment: https://github.com/danger/danger/pull/1207

**Comment by Kaspik** [comment]
Thanks @orta , that might help!

I can see that Circle CI job has setup: https://github.com/danger/danger/blob/69809e8fbb2f61f2755607d2219608ac645eb4d6/.circleci/config.yml#L24
```
      - run: '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger || echo "Skipping Danger for External Contributor"'
      - run: bundle exec danger init --mousey --impatient
```
Looking at the Circle CI run on given job, I can see that it skipped the first one due to external contributor, and then tried the second run:

What exactly the `mousey` and `impatient` does? Could it be that?

**Comment by orta** [comment]
[Travis should be the one running the dangerfile](https://github.com/danger/danger/blob/master/.travis.yml#L31-L32) for PRs (need to test many, but don't want it spamming and confusing for others) 

Though I don't see the status, here's the run: https://travis-ci.org/github/danger/danger/jobs/666482321#L2452

mousey and impatient are options to `init` which makes it not output so much and not wait for user input during the process, that's mainly a lint that the init command works and not useful here alas

**Comment by orta** [comment]
I've got a PR with it running: https://github.com/danger/danger/pull/1210 - though it's not from a fork

**Comment by orta** [comment]
Looks like what GitHub Actions does is:

- Clone danger/danger
- Create a merge commit with the changes in the PR into it
  ```
   /usr/bin/git log -1

   commit ac8589d580c00e773bf8e8dcb8bf9ba62bf1147c

   Author: Orta <orta.therox+github@gmail.com>

   Date:   Mon Apr 6 17:40:52 2020 -0400

    Merge 90137a1b12581aab3efa299c1a37776c7998e91b into c577853adbdc50b36b5ed06cf1a195f8554e1c21
  ```

Then it uses that as head, so the actual commit from your fork isn't there at all. Which is why danger never finds it.

This is likely because other CIs clone _your_ repo fork, where as these other one's clone the main repo and merge the changes in

There are two valid options from my perspective:

 - Check to see if it's a fork PR and if it is also make sure that the fork is fully fetched _as well_ as the main repo
 - Allow GitHub Actions, and others to use HEAD instead of the real PR head (which isn't available)

I don't mind either route

**Comment by Kaspik** [comment]
Sounds like the first would take more time as it would be cloning/fetching two repos where the second one would be just using different commit as HEAD, right?

Honestly I don't care, but it's great to see this moving, thank you so much!

**Comment by orta** [comment]
Nah, only Danger Ruby would get this - the others all use the GH/GL/BB API and don't need local FS access to git for their info.

Your guess is right - it'd have to fetch from two remotes instead of one right now. The latter has a chance for inaccuracy though, it _might_ be a safe assumption that HEAD represents the current tip of the PR, but it might also not. That's why danger is a bit pedantic here and really making sure it knows the full history.

**Comment by Kaspik** [comment]
Let's do what you think is better, or maybe more bulletproof :)

**Comment by b-onc** [comment]
Here to chime in, we're also seeing this behavior in our repo which uses Github Actions.
See https://github.com/GetStream/stream-chat-swift/pull/154 for example

**Comment by orta** [comment]
Cool, then I'd recommend someone make a PR which checks the PR data to make sure both remotes are fetched: https://github.com/danger/danger/blob/7da261774d02359b723aec83abc3ba72fe7e8149/lib/danger/request_sources/github/github.rb#L99

**Comment by Xorima** [comment]
Github Actions also does not pass secrets to any fork builds, which might be a cause.

**Comment by troyfontaine** [comment]
Using:
```yaml
      - uses: actions/checkout@v2
```
Will only checkout the single commit to be tested-you need something with more depth, so you can either use `actions/checkout@v1` or specify the `fetch-depth` as in:

```yaml
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
```

This solved my issues with Github Actions 😄

**Comment by ngetahun** [comment]
@orta Does Danger use the same secrets in CI check on PRs from forks. I was seeing this error

```

Could not set up API to Code Review site for Danger

For your GitHub repo, you need to expose: DANGER_GITHUB_API_TOKEN
You may also need: DANGER_GITHUB_HOST, DANGER_GITHUB_API_BASE_URL, DANGER_OCTOKIT_VERIFY_SSL

``` 

Seems like the repo secrets were not being shared.

**Comment by orta** [comment]
Yep thread is about how GitHub does not share secrets to forks on PRs. It's out of Danger's control I'm afraid, you'd need to make it public like:

```yml
        run: |
          TOKEN='7469b4e94ce21b43e3ab7a'
          TOKEN+='79960c12a1e067f2ec'
          DANGER_GITHUB_API_TOKEN=$TOKEN yarn danger
```

**Comment by Xorima** [comment]
Is there a Danger App I can install into my org which will run on PRs as clearly Danger in the CI process just is not compatible with Github's Action design

**Comment by orta** [comment]
I'm not taking responsibility for something that important in my spare time. GitHub CI effectively made building it not worth it for me: https://www.youtube.com/watch?v=G_3JiEwby5Q 

But I believe Yahoo! Japan implemented a version you can run yourself: https://github.com/yahoojapan/hosted-danger

**Comment by SgtPooki** [comment]
idk if this will fix everyone's problems, but changing github workflow trigger from `pull_request` to `pull_request_target` resolved the issue for me. see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by Xorima** [comment]
@SgtPooki can you post the full action workflow you are using as I'm struggling to recreate it

**Comment by SgtPooki** [comment]
> @SgtPooki can you post the full action workflow you are using as I'm struggling to recreate it

it's in `ipfs/awesome-ipfs` repo. Also, there was some feedback on the PR or issue I created in that repo from `galargh` that you may find valuable regarding what setting `pull_request_target` actually does.

**Comment by jaymzh** [comment]
A few updates here:

1. Moving to `pull_request_target` basically never triggers the workflow in my experience, so that doesn't solve the 'access to the fork" problem, best I can tell.
2. The details in https://github.com/danger/danger/issues/1103#issuecomment-610055193 seem accurate, we need to make sure we look for the commit in the right place, and it seems like we're not... but not SOMETIMES, because other times it works (??)

I've found a few work-arounds (see https://github.com/chef/chef/pull/13976), basically I `tee` the output to a file, and if the failure shows Danger intentionally failed the PR, I exit 1, otherwise I exit 0. THis means that for forked-PRs, when it works, the output is only in the test log, which is still something, and for branched-PRs, the output will get put into a nice comment, which is good enough. It would be even better if danger itself could have different exit codes for that.

**Comment by orta** [comment]
You could use `--fail-on-errors=true` to force an error code on the branched PR, though warnings would still slip by living only in logs

In Danger JS I [explored](https://github.com/danger/danger-js/blob/main/CHANGELOG.md#1110) using [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) as another route for this, as well as https://github.com/danger/danger-js/pull/1126 but that meant I would be storing a bunch of people's github tokens which isn't something I want to do really

**Comment by jaymzh** [comment]
> You could use `--fail-on-errors=true` to force an error code on the branched PR, though warnings would still slip by living only in logs


What? It works on branched repos, just not on forked repos. And it already fails on error, that's not the problem, the problem is it also fails for all PRs from forked repos because it can't find the commit making it seem like the author has bugs even when they don't. Hence the grepping the output above to decide what really happened.

**Comment by jaymzh** [comment]
I FINALLY found a work around:

```
      - uses: actions/checkout@v4
        with:
          # This will checkout the fork, if it's a fork
          # or the main repo if it's a branch
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
```

**Comment by jaymzh** [comment]
so I tried to work around this today, and while I didn't get a solution, I think what i found may be enlightening.

I added a step to checkout the fork remote:
```
      - run: |
          set -x
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          echo $EVENT
          echo $PR_REPO
          echo $BASE_REPO
          # should be PR_REPO_URL, but that doesn't exist
          # for some reason...
          git remote add pr https://github.com/$PR_REPO
          git fetch pr
          git remote -v
          git checkout $PR_HEAD
          git show
        if: github.event.pull_request.head.repo.full_name != github.repository
        env:
          EVENT: ${{ github.event_name }}
          PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url }}
          BASE_REPO: ${{ github.repository }}
          PR_HEAD: ${{ github.event.pull_request.head.ref }}

```

When I did that, however, Danger, I think, ended up comparing the branch to itself, and saw no delta, and thus was very happy.

So then I tried to pass in --base:

```
      - run: |
          danger --verbose --fail-on-errors=true --base=$BASE
        env:
          BASE: ${{ github.event.pull_request.base.ref }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But then it complains it can't find `main` anywhere in the repo (`Commit main doesn't exist`). That can't be right!

I then tried dropping the `checkout`, but that didn't work either.  I even tried modifying my git-fix step to be:

```
          git checkout -b main origin/main
          git checkout $PR_HEAD
```

to make sure the right main and the right head would be there. This gets the right things in the right places:

```
+ git remote -v
origin	https://github.com/chef/chef (fetch)
origin	https://github.com/chef/chef (push)
pr	https://github.com/jaymzh/chef (fetch)
pr	https://github.com/jaymzh/chef (push)
+ git checkout -b main origin/main
Previous HEAD position was 63aab93aff Merge cb81921547c7a0b0bdac3ebdf66f7726e5210015 into 3e18296d7e4f1a175f43f41d08173c708634cd8c
Switched to a new branch 'main'
branch 'main' set up to track 'origin/main'.
+ git checkout dangerfix
Switched to a new branch 'dangerfix'
branch 'dangerfix' set up to track 'pr/dangerfix'.
```

But, this, once again, caused danger to simply see nothing.

I tried at this point modifying danger call to be this, though I think this is what it does by default:

```
      - run: |
          danger --verbose --fail-on-errors=true --base=$BASE --head=$PR_HEAD
        env:
          BASE: ${{ github.event.pull_request.base.ref }}
          PR_HEAD: ${{ github.event.pull_request.head.ref }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But it sees nothing.

So then I decided to add `message(git.diff)` to see what diff it thinks it's seeing.

Low and behold, it's my diff. It crashes on `unless source.valid_encoding?` (https://github.com/chef/chef/actions/runs/7148990967/job/19470679407?pr=14134), but in the stacktrace I can see the diff.

So at this point, given I've made sure that both the base ref and the head ref are both there, I think it seems reasonable to believe there's something that Danger isn't quite catching here.

**Comment by mmd-osm** [comment]
I'm wondering if anyone has tried out the set up described in https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/ (in particular ReceivePR.yml + CommentPR.yml) along with danger?

**Comment by jaymzh** [comment]
That seems like it would work if Danger were modified to be able to dump it's run results into some standard format, but not act on it, and then read it in and act on it. But AFAIK, it does not have such options.

**Comment by orta** [comment]
Danger in JS [is already split](https://danger.systems/js/usage/danger-process) in a way to be able to do this (because it allows for different runtimes) - it'd require a pretty massive re-work of this ruby codebase to do that probably

**Comment by mmd-osm** [comment]
Thank you both for your insights. I did a bit of testing locally last night and would appreciate your feedback, if I'm on the right track. I particular, I'm wondering if these commands would need some further adjustments when running as part of GH actions. 

### Step 0: Preparation: environment variables

For testing purposes, I defined the following environment variables. Here I'm also not 100% clear how this would need to be adjusted for GH actions.

```
export DANGER_GITHUB_API_TOKEN=xxx
export DANGER_FAKE_CI="YEP" DANGER_TEST_REPO='openstreetmap/openstreetmap-website' DANGER_TEST_PR='5269'
```


### Step 1: ReceivePR.yml - generate JSON DSL format for step 2

```
$ yarn --silent danger pr https://github.com/openstreetmap/openstreetmap-website/pull/5269 --json > dsl_5269.json
```
For this step, I also looked into "danger ci", but it seems this is doing too much for our use case, and can't emit the DSL in json format?

### Step 2: ReceivePR.yml - process Dangerfile, generate danger results as json output

```
$ cat dsl_5269.json | yarn --silent danger runner
danger-results://tmp/danger-results-c6ad4a36.json
```

This script outputs the "danger-results" location. My assumption would be that I have to check in this file as an artifact, and then process it in step 3 below.

I guess Steps 1 and 2 could be combined to as a single command as well?

```
$ yarn --silent danger pr https://github.com/openstreetmap/openstreetmap-website/pull/5269 --json | yarn --silent danger runner
```

Danger results output might look shown in this example:

<details>

```JSON
{
  "fails": [
    {
      "message": "Gem/Bundle changes were not documented in the Description. If this is a major update, add #gemlock_major_upgrade to the PR Description."
    }
  ],
  "warnings": [],
  "messages": [],
  "markdowns": [],
  "scheduled": []
}

```

</details>

### Step 3: Inside CommentPR.yml, update the pull request with findings from step 2.

```
yarn --silent danger process ./update_pr.rb
```

The respective ruby script processes the JSON danger result from step 2.  I've noticed that danger process had some issues with the json file generated in step 2, probably due to some additional whitespace. That why I had to do some reformatting using  `JSON.parse(input).to_json`. I'm not sure if this is the recommended approach, though.

```ruby
#!/usr/bin/ruby
str = STDIN.tty? ? "Cannot read from STDIN" : $stdin.read
exit(1) unless str

require "json"

input = File.read("/tmp/danger-results-c6ad4a36.json")
results = JSON.parse(input).to_json

STDOUT.write(results)
```

Thanks!
