### ISSUE TITLE
Failed to rescue in block in submit_inline_comments_for_kind!

### ISSUE THREAD

**Issue by JanPawlov** [danger/danger#1106]
# Report
Running `danger` using gem versions 

```ruby
Using danger 6.0.0
Using danger-plugin-api 1.0.0
...
Using danger-android_lint 0.0.6
Using ox 2.10.0
Using danger-checkstyle_format 0.1.1
...
Using gitlab 4.10.0
Using danger-gitlab 7.0.0
```

results in

```
Server responded with code 400, message: 400 (Bad request) "Note {:line_code=>["can't be blank", "must be a valid line code"]}" not given. Request URI: https://git.domain.com/api/v4/projects/my_project/merge_requests/2/discussions
body: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:warning:</td>
      <td width="100%" data-sticky="false">app/src/main/java/com/domain/project/SomeClass.kt#L1Needless blank line(s)</td>
    </tr>
  </tbody>
</table>

position: {:position_type=>"text", :new_path=>"app/src/main/java/com/domain/project/SomeClass.kt", :new_line=>1, :base_sha=>"727a60e3b24bfcba507b3d8687b1a428c73f5e4d", :start_sha=>"727a60e3b24bfcba507b3d8687b1a428c73f5e4d", :head_sha=>"378f448b7a41cc43b67a98855fd2c39e1398cb22"}
/var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:425:in `rescue in block in submit_inline_comments_for_kind!': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:402:in `block in submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:374:in `reject'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:374:in `submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:335:in `submit_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:187:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
/var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: Bad Request. Request URI: https://git.domain.com/api/v4/projects/my_project/merge_requests/2/discussions/2a8634d25f816bbefefe629998db4533905a8a7f/notes/36227 (Gitlab::Error::BadRequest)
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/client/merge_requests.rb:284:in `update_merge_request_discussion_note'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:422:in `block in submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:374:in `reject'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:374:in `submit_inline_comments_for_kind!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:335:in `submit_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:187:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/gems/danger-6.0.0/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```

## Your Environment

* Which CI are you running on?

`GitLab 11.8.0 (ce13864)`

* What is your Dangerfile?

 ```ruby
declared_trivial = (gitlab.mr_title + gitlab.mr_body).include?("trivial")

warn("MR is classed as Work in Progress") if gitlab.mr_title.include? "[WIP]"

failure "Please provide a summary in the Merge Request description" if gitlab.mr_body.length < 5

# Warn when detekt config has changed
warn("Detekt config has changed") if git.modified_files.include? "detekt-config.yml"

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# detekt
checkstyle_format.base_path = Dir.pwd
checkstyle_format.report "/builds/hireme/hireme-android/app/build/reports/detekt/detekt.xml"

# AndroidLint
android_lint.report_file = "app/build/reports/lint-results.xml"
android_lint.lint(inline_mode: true)

 ```

**Comment by pbendersky** [comment]
@JanPawlov sorry! Just uploaded a fix. Would you mind trying it before we merge?
You can change your `Gemfile` as:
`gem "danger", :git => "https://github.com/pbendersky/danger.git", :branch => "issue-1106"`

**Comment by JanPawlov** [comment]
@pbendersky Will do just that

**Comment by JanPawlov** [comment]
@pbendersky Works fine, however all the warnings that failed are are added to the last inline comment. This results is that I have warnings in the inline comment that are not related to the diff itself. Is this intentional behaviour? Could failed warning be added as a normal comment, so they are not linked to the wrong diff?

**Comment by pbendersky** [comment]
They should be added to the regular comment, not the last inline comment. I do wonder if this is a product of your MR having the inline comments already present?
Can you delete all the danger generated comments and retry?

**Comment by JanPawlov** [comment]
This might be the case. Ran danger before I cleared all the comments and all the warnings got posted into last inline comment. After clearing the comments there were no errors and everything was added into inline comments properly. After that I retried once again, some errors occurred, only this time all the warnings got posted as a regular comment, leaving inlines intact. 

To test the behaviour I'm triggering 3 issues with the code, 2 of them are in the single file. I noticed that if I removed that extra issue from the code danger runs seamlessly,inline comment fails emerge when there is more than 1 issue per file.

**Comment by pbendersky** [comment]
Sounds ok to me then. On a new MR it should work properly. I don’t think it’s worth looking into the issue as it happened if you had previously run another version of danger. Do you agree?

**Comment by JanPawlov** [comment]
I agree, this should be lookined into on a fresh MR with new release, I think we’re slowly getting there with the funcionallity 👌

**Comment by pbendersky** [comment]
Hopefully! Thanks again for the feedback!

**Comment by JanPawlov** [comment]
Running `danger` on a fresh MR today resulted in 
```
/var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 404, message: 404 Not found. Request URI: https://git.domain.com/api/v4/projects/my_project/merge_requests/37/notes/36755 (Gitlab::Error::NotFound)
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/client/notes.rb:269:in `edit_merge_request_note'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/request_sources/gitlab.rb:215:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/bin/danger:5:in `<top (required)>'
	from /var/lib/gems/2.6.0/bin/danger:23:in `load'
	from /var/lib/gems/2.6.0/bin/danger:23:in `<main>'
```

**Comment by pbendersky** [comment]
Are there any comments generated by danger in that MR? That code path should execute to edit the last comment.

What does the API call for `https://git.domain.com/api/v4/projects/my_project/merge_requests/37/notes` return?

**Comment by JanPawlov** [comment]
There are no notes on this MR and https://git.domain.com/api/v4/projects/my_project/merge_requests/37/notes returns `[ ]`. There should be 3-4 issues, not necessarily inlined

**Comment by pbendersky** [comment]
What about 
https://git.domain.com/api/v4/projects/my_project/merge_requests/37/discussions? Do you get results there? How many of those are generated by danger? Any of those not inlined? Thank you!

**Comment by JanPawlov** [comment]
MR was fresh, there was no comments (`/notes` and `/discussions` returned emprty arrays). 
I reran the job and it succeeded.

**Comment by JanPawlov** [comment]
I just occurred a new error: 
```
/var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:39:in `rescue in decode': The response is not a valid JSON (Gitlab::Error::Parsing)
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:36:in `decode'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:18:in `parse'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:12:in `block in <class:Request>'
	from /var/lib/gems/2.6.0/gems/httparty-0.16.4/lib/httparty/request.rb:399:in `parse_response'
	from /var/lib/gems/2.6.0/gems/httparty-0.16.4/lib/httparty/request.rb:367:in `block in handle_response'
	from /var/lib/gems/2.6.0/gems/httparty-0.16.4/lib/httparty/response.rb:35:in `parsed_response'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:69:in `validate'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /var/lib/gems/2.6.0/gems/gitlab-4.10.0/lib/gitlab/client/notes.rb:269:in `edit_merge_request_note'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/request_sources/gitlab.rb:215:in `update_pull_request_with_inline_comments!'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/danger_core/executor.rb:29:in `run'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/lib/danger/commands/runner.rb:72:in `run'
	from /var/lib/gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /var/lib/gems/2.6.0/bundler/gems/danger-51ac60a9599a/bin/danger:5:in `<top (required)>'
	from /var/lib/gems/2.6.0/bin/danger:23:in `load'
	from /var/lib/gems/2.6.0/bin/danger:23:in `<main>'
```

**Comment by pbendersky** [comment]
I'll check. Can you please tell me what comments did `danger` generate? Inline or not? From the error, I'd guess you had a non-inline comment and it failed when trying to update it, but I'm not sure.
