### ISSUE TITLE
Danger fails commenting in gitlab

### ISSUE THREAD

**Issue by reshadf** [danger/danger#1111]
# Report

## What did you do?

Run `bundle exec danger --verbose`

## What did you expect to happen?

Running your Dangerfile without it crashing. and commenting successfully

## What happened instead?

```
/Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 404, message: 404 API Version Not Found. Request URI: https://gitlab.intern.[redacted].nl/api/v4http://gitlab.intern.[redacted].nl/api/v4/projects/42/merge_requests/220/discussions?id=42¬eable_id=220&page=2&per_page=20 (Gitlab::Error::NotFound)
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/paginated_response.rb:92:in `next_page'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/paginated_response.rb:40:in `each_page'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/paginated_response.rb:47:in `auto_paginate'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/request_sources/gitlab.rb:79:in `mr_comments'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/request_sources/gitlab.rb:161:in `update_pull_request_with_inline_comments!'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/danger_core/executor.rb:29:in `run'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/commands/runner.rb:72:in `run'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/bin/danger:5:in `<top (required)>'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/danger:23:in `load'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/danger:23:in `<main>'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
+ set -eo pipefail
+ set +o noclobber
+ :
+ eval ''
+ exit 0
ERROR: Job failed: exit status 1
```

## Your Environment

* Which CI are you running on? -> Gitlab
* Are you running the latest version of Danger? -> 7.0.0
* What is your Dangerfile?

```
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example

# Skip Danger for work-in-progress PRs
if gitlab.mr_title.include?("[WIP]") || gitlab.mr_title.include?("WIP:")
  return
end

def filterFiles(files)
  return files.select { |f| f.end_with? ".h", ".m", ".swift", ".mm" }
end

declared_trivial = gitlab.mr_title.include? "#trivial"

message "Make sure to test your changes before moving your ticket to Code review."

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("MR is classed as Work in Progress") if gitlab.mr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big MR") if git.lines_of_code > 500

# Ensure a clean commits history
if git.commits.any? { |c| c.message =~ /^Merge branch '#{gitlab.branch_for_base}'/ }
  fail "Please rebase to get rid of the merge commits in this PR"
end

# If these are all empty something has gone wrong, better to raise it in a comment
if git.modified_files.empty? && git.added_files.empty? && git.deleted_files.empty?
  fail "This MR has no changes at all, this is likely an issue during development."
end

# Info.plist file shouldn't change often. Leave warning if it changes.
is_plist_change = git.modified_files.sort == ["[redacted]/Info.plist"].sort

if !is_plist_change
  warn "Plist changed, don't forget to localize your plist values"
end

added_paths = filterFiles(git.added_files)
touched_paths = filterFiles(git.added_files | git.modified_files)

touched_paths.each do |p|
  next unless File.exist?(p)
  content = File.read(p)

  lines = content.split("\n")
  lines.each_with_index do |line, index|
    # warn if there are any TODOs, NSLogs or prints left in the touched files
    warn("`TODO` comment left", file: p, line: index + 1) if line.downcase =~ /\/\/\s?todo/
    warn("`FIXME` comment left", file: p, line: index + 1) if line.downcase =~ /\/\/\s?fixme/
    warn("`NSLog` left", file: p, line: index + 1) if line.downcase =~ /\sNSLog\(@"/
    warn("`print` left", file: p, line: index + 1) if line.downcase =~ /\sprint\("/
  end
end

# Don't let testing shortcuts get into master by accident
fail("fdescribe left in tests") if `grep -r fdescribe specs/ `.length > 1
fail("fit left in tests") if `grep -r fit specs/ `.length > 1

# report the coverage
xcov.report(
   scheme: '[redacted]',
   workspace: '[redacted].xcworkspace',
)
```

I think something fails on this line: 
```post_exception(ex, danger_id, new_comment) unless danger_id.nil?```

**Comment by pbendersky** [comment]
From this error, it seems that you are using a very old version of GitLab that doesn’t support the v4 API. Can you confirm that?

**Comment by reshadf** [comment]
I use v4 api. I resolved it somehow bu removing the merge request entirely and recreating it. Before it stopped working my dangerfile wasnt correct so somehow it was in a state that couldnt handle anything anymore.

**Comment by matteomatassoni** [comment]
We have a similar problem:

```
Gitlab::Error::BadRequest: Server responded with code 400, message: Bad Request. Request URI: <DANGER_GITLAB_API_BASE_URL>/projects/<group>%2F<project_name_part_before_space>%2D<project_name_part_after_space>/merge_requests/<MR_IID>/discussions/9bf737af350631f1834ba7ed27f1cc1274f73668/notes/64759
```

**Comment by oboenikui** [comment]
It seems that the necessary request params are missing, so I made the above Pull Request.

**Comment by jk** [comment]
We're seeing the same error:
```
/usr/local/bundle/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 400, message: Bad Request. Request URI: https://[GITLAB_HOST]/api/v4/projects/[PROJECT_NAMESPACE]/merge_requests/1178/discussions/8710f1c48802f62564b9bb2adce9a42c4d2bdc85/notes/20222 (Gitlab::Error::BadRequest)
	from /usr/local/bundle/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
	from /usr/local/bundle/gems/gitlab-4.10.0/lib/gitlab/client/merge_requests.rb:284:in `update_merge_request_discussion_note'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/request_sources/gitlab.rb:346:in `block in submit_inline_comments!'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/request_sources/gitlab.rb:342:in `each'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/request_sources/gitlab.rb:342:in `submit_inline_comments!'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/request_sources/gitlab.rb:187:in `update_pull_request_with_inline_comments!'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/danger_core/dangerfile.rb:278:in `run'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/danger_core/executor.rb:29:in `run'
	from /usr/local/bundle/gems/danger-6.0.2/lib/danger/commands/runner.rb:72:in `run'
	from /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-6.0.2/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:23:in `load'
	from /usr/local/bundle/bin/danger:23:in `<main>'
```
