### ISSUE TITLE
Danger fails updating comments in gitlab

### ISSUE THREAD

**Issue by reshadf** [danger/danger#1124]
# Report

## What did you do?
the CI ( gitlab ) ran the following command on a Merge request that was already reviewed by Danger. When it tries to update it, it fails see #1111 the possible fix should have been #1116 but it is not working yet. 
`- bundle exec danger --verbose`

## What did you expect to happen?

updating comments without problems

## What happened instead?

gitlab returns an error because the URL pointing to that specific endpoint is set up in a weird way. 

see:
```
  /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/request.rb:67:in `validate': Server responded with code 404, message: 404 API Version Not Found. Request URI: https://gitlab.intern.[redacted].nl/api/v4http://gitlab.intern.[redacted].nl/api/v4/projects/42/merge_requests/220/discussions?id=42¬eable_id=220&page=2&per_page=20 (Gitlab::Error::NotFound)
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/paginated_response.rb:92:in `next_page'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/paginated_response.rb:40:in `each_page'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/gitlab-4.10.0/lib/gitlab/paginated_response.rb:47:in `auto_paginate'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/request_sources/gitlab.rb:79:in `mr_comments'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/request_sources/gitlab.rb:161:in `update_pull_request_with_inline_comments!'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/request_sources/gitlab.rb:154:in `update_pull_request!'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/danger_core/dangerfile.rb:278:in `run'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/danger_core/executor.rb:29:in `run'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/lib/danger/commands/runner.rb:72:in `run'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/gems/danger-6.0.1/bin/danger:5:in `<top (required)>'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/danger:23:in `load'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/danger:23:in `<main>'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  	from /Users/[redacted]-macserver/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
  + set -eo pipefail
  + set +o noclobber
  + :
  + eval ''
  + exit 0
  ERROR: Job failed: exit status 1
```

## Your Environment

* Which CI are you running on?
> gitlab
* Are you running the latest version of Danger?
> yes
* What is your Dangerfile?

  ```ruby
    # Sometimes it's a README fix, or something like that - which isn't relevant for
  # including in a project's CHANGELOG for example

  # Skip Danger for work-in-progress PRs
  if gitlab.mr_title.include?("[WIP]") || gitlab.mr_title.include?("WIP:")
    return
  end

  def filterFiles(files)
    return files.select { |f| f.end_with? ".kt", ".java" }
  end

  declared_trivial = gitlab.mr_title.include? "#trivial"

  message "Make sure to test your changes before moving your ticket to Code review."

  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  warn("MR is classed as Work in Progress") if gitlab.mr_title.include? "[WIP]"

  # Warn when there is a big PR
  warn("Big MR") if git.lines_of_code > 500

  # Ensure a clean commits history
  if git.commits.any? { |c| c.message =~ /^Merge branch '#{gitlab.branch_for_base}'/ }
    fail "Please rebase to get rid of the merge commits in this PR"
  end

  # If these are all empty something has gone wrong, better to raise it in a comment
  if git.modified_files.empty? && git.added_files.empty? && git.deleted_files.empty?
    fail "This MR has no changes at all, this is likely an issue during development."
  end

  added_paths = filterFiles(git.added_files)
  touched_paths = filterFiles(git.added_files | git.modified_files)

  touched_paths.each do |p|
    next unless File.exist?(p)
    content = File.read(p)

    lines = content.split("\n")
    lines.each_with_index do |line, index|
      # warn if there are any TODOs or Log.d left in the touched files
      warn("`TODO` comment left", file: p, line: index + 1) if line.downcase =~ /\/\/\s?todo/
      warn("`FIXME` comment left", file: p, line: index + 1) if line.downcase =~ /\/\/\s?fixme/
      warn("`Log` left", file: p, line: index + 1) if line.downcase =~ /\sLog.d\(@"/
    end
  end

  android_lint.gradle_task = "app:lintDevelopRelease"
  android_lint.report_file = "app/build/reports/lint-results-developRelease.xml"
  android_lint.filtering = true
  android_lint.lint(inline_mode: true)

  checkstyle_format.base_path = Dir.pwd
  checkstyle_format.report "app/build/reports/ktlint/ktlint-checkstyle-report.xml"
  checkstyle_format.report 'app/build/reports/detekt/detekt-checkstyle.xml'
  ```

**Comment by reshadf** [comment]
Is there a way to debug and try to solve this myself? Since we get a lot of reproductions of this issue it might be easy to find the problem :)

**Comment by reshadf** [comment]
update: after some debuggin the calls I tried deleting `DANGER_GITLAB_API_BASE_URL` from the env variables in GITLAB which fixed the issue.

**Comment by H3npi** [comment]
Which environment variables did you set?
