### ISSUE TITLE
Can't find Dangerfile on on-prem GitLab anymore

### ISSUE THREAD

**Issue by jk** [danger/danger#1130]
# Report

## What did you do?
Update from danger 6.0.6 to 6.0.7. It refers to changes introduced in PR https://github.com/danger/danger/pull/1128.

```
$ git version
git version 2.11.0
$ danger --version
6.0.7
$ danger --fail-on-errors=true
/usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:177:in `initialize':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: No such file or directory @ rb_sysopen - bbc/Dangerfile/Dangerfile
 #  from Dangerfile:6
 #  -------------------------------------------
 #  
 >  danger.import_dangerfile(gitlab: "muz/dangerfiles", branch: "master", path: "bbc/Dangerfile")
 #  -------------------------------------------
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:177:in `open'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:177:in `parse'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:129:in `import_dangerfile_from_path'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:84:in `import_dangerfile'
	from Dangerfile:6:in `eval_file'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:297:in `eval'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:197:in `parse'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:273:in `run'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/executor.rb:29:in `run'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/commands/runner.rb:72:in `run'
	from /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-6.0.7/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:23:in `load'
	from /usr/local/bundle/bin/danger:23:in `<main>'
/usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:177:in `initialize': No such file or directory @ rb_sysopen - bbc/Dangerfile/Dangerfile (Errno::ENOENT)
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:177:in `open'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:177:in `parse'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:129:in `import_dangerfile_from_path'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:84:in `import_dangerfile'
	from Dangerfile:6:in `eval_file'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:297:in `eval'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:197:in `parse'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/dangerfile.rb:273:in `run'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/danger_core/executor.rb:29:in `run'
	from /usr/local/bundle/gems/danger-6.0.7/lib/danger/commands/runner.rb:72:in `run'
	from /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-6.0.7/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:23:in `load'
	from /usr/local/bundle/bin/danger:23:in `<main>'
```

## What did you expect to happen?

Running without problems. Find the `Dangerfile` in our central gitlab repo under `bbc/Dangerfile`

## What happened instead?

It crashed, since it can't retrieve a copy of that bespoke `Dangerfile`. From the error message it looks like, it searches for that Dangerfile in `bbc/Dangerfile/Dangerfile` instead of just `bbc/Dangerfile`. But I can't see that in the source (https://github.com/danger/danger/pull/1128/files#diff-3e7b2d9e0c99848e44d769efe4878d0bR179 and https://github.com/danger/danger/pull/1128/files#diff-ff5843ecf6dcdceece17273c5a5148a6R301).

Is there eventually a problem with Dangerfiles in sub-directories?

## Your Environment

* Which CI are you running on?
  * gitlab-ci
* Are you running the latest version of Danger?
  * yes, 6.0.7
* What is your Dangerfile?
```ruby
danger.import_dangerfile(gitlab: "muz/dangerfiles", branch: "master", path: "bbc/Dangerfile")
```

**Comment by satyap** [comment]
I was able to retrieve it by doing something similar to this:

`danger.import_dangerfile(gitlab_project_id: 1234, branch: "master", path: "bbc")`

i.e. remove `/Dangerfile` from the path, and specify the gitlab project ID (which is strange if it works for you with the project name, the source makes it look like you *have* to specify the project id)

(I'm not a maintainer or anything, I only suggest this as a workaround)

**Comment by jk** [comment]
I can confirm, that

```
danger.import_dangerfile(gitlab_project_id: 42, branch: "master", path: "bbc/Dangerfile")
```

works for us.

By the way:
```
danger.import_dangerfile(gitlab: "muz/dangerfiles", branch: "master", path: "bbc")
```
does not work.

@manu-d Any news on that issue?
