### ISSUE TITLE
Danger crashes when not running on PR in CircleCI

### ISSUE THREAD

**Issue by mvandervelden** [danger/danger#1135]
# Report

## What did you do?

* Update Danger from 5.5.13 to 6.0.9

## What did you expect to happen?

* Running Dangerfile on master branch on CircleCI should report `Not a CircleCI Pull Request - skipping ``danger`` run`, without crashing/failing the build.

## What happened instead?

* Crash:
```
bundler: failed to load command: danger (/Users/distiller/project/vendor/bundle/ruby/2.4.0/bin/danger)
NoMethodError: undefined method `first' for nil:NilClass
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/ci_source/circle_api.rb:38:in `fetch_pull_request_url'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/ci_source/circle_api.rb:24:in `pull_request_url'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/ci_source/circle_api.rb:8:in `pull_request?'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/ci_source/circle.rb:59:in `validates_as_pr?'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/danger_core/executor.rb:63:in `validate_pr!'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/danger_core/executor.rb:47:in `validate!'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/danger_core/executor.rb:22:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:72:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-6.0.9/bin/danger:5:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/bin/danger:23:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* CircleCI
* Yes, v. 6.0.9

Dangerfile:
```ruby
warn("PR is classed as Work in Progress") if github.pr_title.include? "WIP"
```

**Comment by orta** [comment]
agree, maybe the ENV vars in circle changed?

**Comment by mvandervelden** [comment]
I don't know, that would be relevant mainly if the newer Danger version started relying on different ENV vars, as Danger 5.5.13 is still working as expected.

**Comment by orta** [comment]
Good question, maybe this broke it for your case: https://github.com/danger/danger/commit/7f6a6c52ed182f7d357f4859d96e368fd50f254f

**Comment by mvandervelden** [comment]
Thanks for this suggestion. I've investigated a bit more, and updated our Circle CI tokens & env vars to take the new integration into consideration. It's still crashing on the same line however.
Created #1140 that fixes the issue we're having.
