### ISSUE TITLE
Codeship integration error on CI_REPO_NAME

### ISSUE THREAD

**Issue by Draiken** [danger/danger#1136]
# Report

## What did you do?

Ran danger on Codeship PRO (docker based)

## What did you expect to happen?

Danger to run normally

## What happened instead?

I got an error
```
bundler: failed to load command: danger (/app/vendor/bundle/ruby/2.1.0/bin/danger)
Octokit::InvalidRepository: "app" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys.
  /app/vendor/bundle/ruby/2.1.0/gems/octokit-4.14.0/lib/octokit/repository.rb:92:in `raise_invalid_repository!'
  /app/vendor/bundle/ruby/2.1.0/gems/octokit-4.14.0/lib/octokit/repository.rb:34:in `initialize'
  /app/vendor/bundle/ruby/2.1.0/gems/octokit-4.14.0/lib/octokit/repository.rb:58:in `new'
  /app/vendor/bundle/ruby/2.1.0/gems/octokit-4.14.0/lib/octokit/repository.rb:58:in `path'
  /app/vendor/bundle/ruby/2.1.0/gems/octokit-4.14.0/lib/octokit/client/pull_requests.rb:20:in `pull_requests'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/request_sources/github/github.rb:37:in `get_pr_from_branch'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/ci_source/codeship.rb:31:in `pr_from_env'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/ci_source/codeship.rb:22:in `validates_as_pr?'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:63:in `validate_pr!'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:47:in `validate!'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:22:in `run'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/commands/runner.rb:72:in `run'
  /app/vendor/bundle/ruby/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /app/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/bin/danger:5:in `<top (required)>'
  /app/vendor/bundle/ruby/2.1.0/bin/danger:23:in `load'
  /app/vendor/bundle/ruby/2.1.0/bin/danger:23:in `<top (required)>'
```

My guess is that CI_REPO_NAME doesn't include the organization and therefore all urls are broken.

## Your Environment

* Which CI are you running on? Codeship PRO
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

  ```ruby
  # please paste here, with 2-space identation, thank you!
  # Sometimes it's a README fix, or something like that - which isn't relevant for
  # including in a project's CHANGELOG for example
  #declared_trivial = github.pr_title.include?('#trivial')

  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  warn('PR is classed as Work in Progress') if github.pr_title.include?('WIP')

  # Warn when there is a big PR
  warn('Big PR. Please try to create smaller PRs in the future.') if git.lines_of_code > 800

  # Translation changes
  has_locale_changes = git.modified_files.grep(%r{config/locales/en/}).any?
  warn("Don't forget to run WTI pull/push for the translations") if has_locale_changes

  # Ensure PRs have connected issues
  connect_regexp = %r{(Connect|Fixes|Closes) #\d+}
  warn("No issue connected to this PR. Remember to add 'Connect #issue_no' if this PR is related to an issue") unless pr_body.match?(connect_regexp)

  # Don't let testing shortcuts get into master by accident,
  # ensuring that we don't get green builds based on a subset of tests.
  (git.modified_files + git.added_files - %w(Dangerfile)).each do |file|
    next unless File.file?(file)
    contents = File.read(file)
    if file.start_with?('spec')
      fail("`xit` or `fit` left in tests (#{file})") if contents =~ /^\w*[xf]it/
      fail("`fdescribe` left in tests (#{file})") if contents =~ /^\w*fdescribe/
    end
  end
  ```

**Comment by orta** [comment]
I'd double check the ENV vars which are being passed to danger, I've never used cadetship so I can't really be of much advice

**Comment by Draiken** [comment]
I believe the code is wrong. On `owner_for_github(env)` it assumes the `CI_REPO_NAME` is `user/repo` and then on the initialize `repo_slug` it assumes it's `repo`.

The variable does not contain the GH user, only the repo name.
I tried overriding the variable to include it, then the error happens on git :/
```
fatal: Not a git repository (or any of the parent directories): .git
bundler: failed to load command: danger (/replaypoker/vendor/bundle/ruby/2.1.0/bin/danger)
NoMethodError: undefined method `split' for nil:NilClass
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/scm_source/git_repo.rb:67:in `origins'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/ci_source/codeship.rb:41:in `initialize'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/environment_manager.rb:30:in `new'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:25:in `new'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/danger_core/executor.rb:25:in `run'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/lib/danger/commands/runner.rb:72:in `run'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /replaypoker/vendor/bundle/ruby/2.1.0/gems/danger-5.16.1/bin/danger:5:in `<top (required)>'
  /replaypoker/vendor/bundle/ruby/2.1.0/bin/danger:23:in `load'
  /replaypoker/vendor/bundle/ruby/2.1.0/bin/danger:23:in `<top (required)>
```

I'm guessing it's because it's Codeship PRO and that means it's not a git repository, it's a docker image.

I know it's nice to have pre-built CI supports, but isn't there a way for me to skip that and provide danger with all the necessary variables directly?

**Comment by orta** [comment]
I'm afraid Danger ruby needs full access to the git history  - you can get docker images of Danger JS I believe which doesn't

**Comment by Rasbcyberassn42** [comment]
can you explain to me more about this?

R©ASB
