### ISSUE TITLE
Installing danger produces "Faraday" error

### ISSUE THREAD

**Issue by lopezm1** [danger/danger#1161]
# Report

Seeing the following error when I try to install danger on a CI container. This seemed to break this morning.

```
Using bundler 2.0.2
Fetching claide 1.0.3
Installing claide 1.0.3
Fetching colored2 3.1.2
Installing colored2 3.1.2
Fetching cork 0.3.0
Installing cork 0.3.0
Fetching nap 1.1.0
Installing nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Fetching faraday 0.16.0
Installing faraday 0.16.0
Fetching faraday-http-cache 2.0.0
Installing faraday-http-cache 2.0.0
Fetching git 1.5.0
Installing git 1.5.0
Fetching kramdown 2.1.0
Installing kramdown 2.1.0
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching no_proxy_fix 0.1.2
Installing no_proxy_fix 0.1.2
Fetching sawyer 0.8.2
Installing sawyer 0.8.2
Fetching octokit 4.14.0
Installing octokit 4.14.0
Fetching unicode-display_width 1.6.0
Installing unicode-display_width 1.6.0
Fetching terminal-table 1.8.0
Installing terminal-table 1.8.0
Fetching danger 6.0.9
Installing danger 6.0.9
Bundle complete! 1 Gemfile dependency, 21 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Traceback (most recent call last):
	22: from /usr/local/bin/danger:23:in `<main>'
	21: from /usr/local/bin/danger:23:in `load'
	20: from /var/lib/gems/2.5.0/gems/danger-6.0.9/bin/danger:4:in `<top (required)>'
	19: from /var/lib/gems/2.5.0/gems/danger-6.0.9/bin/danger:4:in `require'
	18: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger.rb:4:in `<top (required)>'
	17: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger.rb:4:in `require'
	16: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:1:in `<top (required)>'
	15: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:2:in `<module:Danger>'
	14: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:3:in `<class:Runner>'
	13: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:3:in `require'
	12: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/init.rb:3:in `<top (required)>'
	11: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/init.rb:3:in `require'
	10: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/ci_source/local_git_repo.rb:6:in `<top (required)>'
	 9: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/ci_source/local_git_repo.rb:6:in `require'
	 8: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/github/github.rb:5:in `<top (required)>'
	 7: from /var/lib/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/github/github.rb:5:in `require'
	 6: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	 5: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `require'
	 4: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	 3: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `require'
	 2: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	 1: from /var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
/var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError
```
## What did you do?

Installed danger with the following commands. 

```
          sudo apt-get install ruby-full
          sudo gem install bundler
          bundle install
          bundle exec danger
```

## What did you expect to happen?

Install danger without the error message. 

## What happened instead?

ℹ Please replace this with of what happened instead.
e.g. 💥

```
/var/lib/gems/2.5.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': uninitialized constant Faraday::Error::ClientError
```

## Your Environment

* Which CI are you running on?
CircleCI container running ubuntu 18.04

I was wondering if it was related to the fix another group did here. 
https://github.com/USRSE/usrse.github.io/pull/111

**Comment by JanPawlov** [comment]
Running Jobs today I ran into similiar problem 
```
$ bundle exec danger
/var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14:in `<module:Middleware>': superclass must be a Class (Faraday::DeprecatedConstant given) (TypeError)
	from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:11:in `<module:Octokit>'
	from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:9:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `require'
	from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/default.rb:1:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `require'
	from /var/lib/gems/2.6.0/gems/octokit-4.14.0/lib/octokit.rb:4:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/request_sources/github/github.rb:5:in `require'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/request_sources/github/github.rb:5:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/ci_source/local_git_repo.rb:6:in `require'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/ci_source/local_git_repo.rb:6:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/commands/init.rb:3:in `require'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/commands/init.rb:3:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:3:in `require'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:3:in `<class:Runner>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:2:in `<module:Danger>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:1:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger.rb:4:in `require'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/lib/danger.rb:4:in `<top (required)>'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/bin/danger:4:in `require'
	from /var/lib/gems/2.6.0/gems/danger-6.0.9/bin/danger:4:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```

```
Using CFPropertyList 3.0.1
Using public_suffix 2.0.5
Using addressable 2.7.0
Using ansi 1.5.0
Using ast 2.4.0
Using atomos 0.1.3
Fetching babosa 1.0.3 (was 1.0.2)
Installing babosa 1.0.3 (was 1.0.2)
Using bundler 2.0.2
Using claide 1.0.3
Using colored2 3.1.2
Using cork 0.3.0
Using nap 1.1.0
Using open4 1.3.4
Using claide-plugins 0.9.2
Using colored 1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using multipart-post 2.0.0
Fetching faraday 0.16.1 (was 0.15.4)
Installing faraday 0.16.1 (was 0.15.4)
Using faraday-http-cache 2.0.0
Using git 1.5.0
Using kramdown 2.1.0
Using kramdown-parser-gfm 1.1.0
Using no_proxy_fix 0.1.2
Using sawyer 0.8.2
Using octokit 4.14.0
Using unicode-display_width 1.6.0
Using terminal-table 1.8.0
Using danger 6.0.9
Using danger-plugin-api 1.0.0
Using ruby-ll 2.1.2
Using oga 2.15
Using danger-android_lint 0.0.7
Using ox 2.11.0
Using danger-checkstyle_format 0.1.1
Using mime-types-data 3.2019.0904
Using mime-types 3.3
Using multi_xml 0.6.0
Fetching httparty 0.17.1 (was 0.17.0)
Installing httparty 0.17.1 (was 0.17.0)
Using gitlab 4.12.0
Using danger-gitlab 7.0.0
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.4.1
Using unf_ext 0.0.7.6
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.5
Using emoji_regex 1.0.1
Fetching excon 0.67.0 (was 0.66.0)
Installing excon 0.67.0 (was 0.66.0)
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.13.1
Using fastimage 2.1.7
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.0
Using multi_json 1.13.1
Using os 1.0.1
Using signet 0.11.0
Using googleauth 0.6.7
Using httpclient 2.8.3
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.23.9
Using google-cloud-env 1.2.1
Using google-cloud-core 1.3.1
Using google-cloud-storage 1.16.0
Using json 2.2.0
Using mini_magick 4.9.5
Using plist 3.5.0
Fetching rubyzip 1.3.0 (was 1.2.4)
Installing rubyzip 1.3.0 (was 1.2.4)
Using security 0.1.3
Using naturally 2.2.0
Fetching simctl 1.6.6 (was 1.6.5)
Installing simctl 1.6.6 (was 1.6.5)
Using slack-notifier 2.3.2
Using terminal-notifier 2.0.0
Using tty-screen 0.7.0
Using tty-cursor 0.7.0
Using tty-spinner 0.9.1
Using word_wrap 1.0.0
Using nanaimo 0.2.6
Using xcodeproj 1.12.0
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
Fetching fastlane 2.131.0 (was 2.130.0)
Installing fastlane 2.131.0 (was 2.130.0)
```

**Comment by orta** [comment]
Looks like maybe the dependencies on octokit need to be tightened?

**Comment by bshelton229** [comment]
Pinning faraday as a short-term fix while these projects get patched is working for me as a workaround.

`gem 'faraday', '~> 0.15.0'`

**Comment by Panajev** [comment]
Can danger be retagged with this patch applied? When could an ETA for it to be available be roughly?

**Comment by JanPawlov** [comment]
Faraday 0.16.2 solved issue for me

**Comment by orta** [comment]
Given that faraday is loosely locked at `faraday (~> 0.9)` - I don't think we have to do anything here as everyone will get the updated fix or can do a `bundle update faraday` to get the fix.
