### ISSUE TITLE
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by yzhong52** [danger/danger#1175]
# Report

## What did you do?

```
bundle exec danger local --verbose
```

## What did you expect to happen?

Just want it to work with no exceptions 💔

## What happened instead?

```
ca1-p1r12-bld002:MyWorkspace_MyRepo_PR-4006 jenkins$ bundle exec danger local --verbose
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
Running your Dangerfile against this PR - https://github.svc.internal.zone/MyWorkspace/MyRepo/pull/4000

bundler: failed to load command: danger (/Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/bin/danger)
Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:981:in `connect'
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:909:in `start'
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:1455:in `request'
  /Users/jenkins/.rbenv/versions/2.5.3/lib/ruby/2.5.0/net/http.rb:1213:in `get'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:85:in `perform_request'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:43:in `block in call'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:38:in `call'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/response.rb:8:in `call'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/rack_builder.rb:143:in `build_response'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/connection.rb:387:in `run_request'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/faraday-0.17.1/lib/faraday/connection.rb:138:in `get'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/connection.rb:19:in `get'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/client/pull_requests.rb:33:in `pull_request'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/danger-6.1.0/lib/danger/request_sources/github/github.rb:117:in `fetch_details'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/danger-6.1.0/lib/danger/commands/local_helpers/local_setup.rb:37:in `setup'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/danger-6.1.0/lib/danger/commands/local.rb:55:in `run'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/gems/danger-6.1.0/bin/danger:5:in `<top (required)>'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/bin/danger:23:in `load'
  /Users/jenkins/hop/MyRepo/gem/ruby/2.5.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? 

Jenkins.

* Are you running the latest version of Danger?

Yes.

```
$ bundle exec danger --version
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /Users/jenkins/hop/cupertino/gem/ruby/2.5.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
6.1.0
```

* What is your Dangerfile?

I don't think this matter and I revert it back to the orignal default danger file generated by `danger init`:

  ```ruby
# Sometimes it's a README fix, or something like that - which isn't relevant for
# including in a project's CHANGELOG for example
declared_trivial = github.pr_title.include? "#trivial"

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

# Don't let testing shortcuts get into master by accident
fail("fdescribe left in tests") if `grep -r fdescribe specs/ `.length > 1
fail("fit left in tests") if `grep -r fit specs/ `.length > 1
  ```

**Comment by orta** [comment]
what was the result of your research the first line of the error message?

`Faraday::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)`?

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by manicmaniac** [comment]
> By closing some old issues we reduce the list of open issues to a more manageable set. And this seem like something that isn't a bug in this project, rather something on the end user.

I think so too.

Let me close this issue for now but feel free to reopen this if this one occurs in the latest Danger.
