### ISSUE TITLE
Repo slug code fails on a repo with a `.` in the name

### ISSUE THREAD

**Issue by orta** [danger/danger#119]
on this repo: https://github.com/artsy/artsy.github.io

```
✹ ✭  git remote -v 

origin	git@github.com:artsy/artsy.github.com.git (fetch)
origin	git@github.com:artsy/artsy.github.com.git (push)

✘ ✹ ✭  danger local    
Running your Dangerfile against this PR - https://github.com/artsy/artsyhub.com/pulls/216

/Users/orta/.gem/ruby/2.1.3/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/artsy/artsyhub.com/pulls/216: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /Users/orta/.gem/ruby/2.1.3/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/orta/.gem/ruby/2.1.3/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/orta/.gem/ruby/2.1.3/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/orta/.gem/ruby/2.1.3/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/orta/.gem/ruby/2.1.3/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
```

**Comment by jeroenvisser101** [comment]
More specifically, I think this might be due to `.git` being in the url
