### ISSUE TITLE
`danger dry_run` run locally crashes with `method_missing': undefined local variable or method `github'

### ISSUE THREAD

**Issue by madAndroid** [danger/danger#1203]
# Report

I've tried running Danger when installed using the following approaches:
- `rbenv` (completely fresh install)
- `asdf` (only install of ruby 2.7)
- run within Docker

All of the above methods fail with the same error

## What did you do?

Installed danger via bundler, in a fresh ruby 2.7 install via both `rbenv` and via `asdf`.
Ran `danger init`, and fails with stack trace

## What did you expect to happen?

Dry run to work properly

## What happened instead?

```
danger dry_run
/Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/git-1.6.0/lib/git/lib.rb:1054: warning: Using the last argument as keyword parameters is deprecated
Traceback (most recent call last):
        12: from /Users/andrew/.asdf/installs/ruby/2.7.0/bin/danger:23:in `<main>'
        11: from /Users/andrew/.asdf/installs/ruby/2.7.0/bin/danger:23:in `load'
        10: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
         9: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
         8: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/commands/dry_run.rb:44:in `run'
         7: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:273:in `run'
         6: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
         5: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
         4: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
         3: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
         2: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval'
         1: from Dangerfile:3:in `eval_file'
/Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:70:in `method_missing': undefined local variable or method `github' for #<Danger::Dangerfile:0x00007fdfc329a8d8> (NameError)
        12: from /Users/andrew/.asdf/installs/ruby/2.7.0/bin/danger:23:in `<main>'
        11: from /Users/andrew/.asdf/installs/ruby/2.7.0/bin/danger:23:in `load'
        10: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
         9: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
         8: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/commands/dry_run.rb:44:in `run'
         7: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:273:in `run'
         6: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
         5: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
         4: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
         3: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
         2: from /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval'
         1: from Dangerfile:3:in `eval_file'
/Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:70:in `method_missing': \e[31m (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined local variable or method `github' for #<Danger::Dangerfile:0x00007fdfc329a8d8>\e[0m
 #  from Dangerfile:3
 #  -------------------------------------------
 #  # including in a project's CHANGELOG for example
 >  declared_trivial = github.pr_title.include? "#trivial"
 #
 #  -------------------------------------------
****
```

## Your Environment

* Which CI are you running on?
Jenkins - works fine on Jenkins, fails locally
* Are you running the latest version of Danger? 
  - yes
* Gem environment:
```
gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.0 (2019-12-25 patchlevel 0) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0
  - USER INSTALLATION DIRECTORY: /Users/andrew/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/andrew/.asdf/installs/ruby/2.7.0/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/andrew/.asdf/installs/ruby/2.7.0/bin
  - SPEC CACHE DIRECTORY: /Users/andrew/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/andrew/.asdf/installs/ruby/2.7.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/andrew/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0
     - /Users/andrew/.gem/ruby/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/andrew/.asdf/installs/ruby/2.7.0/bin
     - /Users/andrew/.asdf/shims
     - /usr/local/opt/asdf/bin
     - /usr/local/Cellar/gnu-getopt/2.33.2/bin
     - /Users/andrew/bin/google-cloud-sdk/bin
     - /Users/andrew/golang/bin
     - /Users/andrew/.pyenv/shims
     - /Users/andrew/.cargo/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/MacGPG2/bin
     - /opt/X11/bin
     - /Applications/Wireshark.app/Contents/MacOS
     - /opt/packer
     - /opt/terraform
     - /usr/local/go/bin
     - /Users/andrew/bin
     - /Users/andrew/google-cloud-sdk/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/andrew/.pyenv/shims
     - /Users/andrew/.cargo/bin
     - /usr/local/opt/fzf/bin

```
* Dangerfile:

  ```ruby
  # Sometimes it's a README fix, or something like that - which isn't relevant for
  # including in a project's CHANGELOG for example
  declared_trivial = github.pr_title.include? "#trivial"

  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"

  # Warn when there is a big PR
  warn("Big PR") if git.lines_of_code > 500

  # Don't let testing shortcuts get into master by accident
  fail("fdescribe left in tests") if `grep -r fdescribe specs/ `.length > 1
  fail("fit left in tests") if `grep -r fit specs/ `.length > 1
  ```

I've tried several different approaches here, but none of them seem to work: I've tried earlier ruby versions, including trying system ruby as well .. and also earlier versions of Danger

**Comment by madAndroid** [comment]
I've also tried removing all values in `$PATH`, in case that's what's causing the issue.. and when installing in system ruby:
```gem environment
gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin19]
  - INSTALLATION DIRECTORY: ~/.gem
  - USER INSTALLATION DIRECTORY: /Users/andrew/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: ~/.gem/bin
  - SPEC CACHE DIRECTORY: /Users/andrew/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-19
  - GEM PATHS:
     - ~/.gem
     - /Users/andrew/.gem/ruby/2.6.0
     - /Library/Ruby/Gems/2.6.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /usr/sbin
     - /bin
```

same issue:

```
danger dry_run
Traceback (most recent call last):
        12: from /usr/local/bin/danger:23:in `<main>'
        11: from /usr/local/bin/danger:23:in `load'
        10: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
         9: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
         8: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/commands/dry_run.rb:44:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:273:in `run'
         6: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
         5: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
         4: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
         3: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
         2: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval'
         1: from Dangerfile:3:in `eval_file'
/Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:70:in `method_missing': undefined local variable or method `github' for #<Danger::Dangerfile:0x00007fd02385d6a8> (NameError)
        12: from /usr/local/bin/danger:23:in `<main>'
        11: from /usr/local/bin/danger:23:in `load'
        10: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
         9: from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
         8: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/commands/dry_run.rb:44:in `run'
         7: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:273:in `run'
         6: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `parse'
         5: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
         4: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
         3: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
         2: from /Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:297:in `eval'
         1: from Dangerfile:3:in `eval_file'
/Library/Ruby/Gems/2.6.0/gems/danger-6.3.1/lib/danger/danger_core/dangerfile.rb:70:in `method_missing':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined local variable or method `github' for #<Danger::Dangerfile:0x00007fd02385d6a8>
 #  from Dangerfile:3
 #  -------------------------------------------
 #  # including in a project's CHANGELOG for example
 >  declared_trivial = github.pr_title.include? "#trivial"
 #
 #  -------------------------------------------

```

**Comment by orta** [comment]
A dry run means it doesn't have access to GitHub (because it's running locally) - so the `github` variable is undefined in that command

**Comment by madAndroid** [comment]
Okay, thanks for the heads up - I couldn't find anything in the docs for that, or in the error output .. have been scratching my head for hours now, trying to figure it out 🙈

**Comment by orta** [comment]
I'd take a PR where it does a check for `github.` (and `gitlab.`/`bitbucket_x.`) in the Dangerfile beforehand and raises to give a warning

**Comment by khalilgharbaoui** [comment]
> I'd take a PR where it does a check for `github.` (and `gitlab.`/`bitbucket_x.`) in the Dangerfile beforehand and raises to give a warning

I'll see if I can scratch out some time to make the PR you mentioned...
In the meantime I did this as a workaround in my `Dangerfile`:
```
. . .
if defined?(gitlab)
  warn("MR is classed as Work in Progress") if gitlab.mr.title.include? "[WIP]"
  # more code depenting on "gitlab" being there...
end
. . .
```
