### ISSUE TITLE
Gitlab::Error::Parsing: The response is not a valid JSON

### ISSUE THREAD

**Issue by fadhlimaulidri** [danger/danger#1206]
# Report

## What did you do?
`bundle exec danger`

## What did you expect to happen?
Running your Dangerfile without it crashing.

## What happened instead?

```
$ bundle exec danger
 Gitlab::Error::Parsing: The response is not a valid JSON
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:39:in `rescue in decode'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:36:in `decode'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:18:in `parse'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:12:in `block in <class:Request>'
   /usr/local/bundle/gems/httparty-0.18.0/lib/httparty/request.rb:327:in `parse_response'
   /usr/local/bundle/gems/httparty-0.18.0/lib/httparty/request.rb:295:in `block in handle_response'
   /usr/local/bundle/gems/httparty-0.18.0/lib/httparty/response.rb:35:in `parsed_response'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/error.rb:62:in `classified_response'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/error.rb:43:in `build_error_message'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/error.rb:20:in `initialize'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:61:in `exception'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:61:in `raise'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:61:in `validate'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/request.rb:53:in `block (2 levels) in <class:Request>'
   /usr/local/bundle/gems/gitlab-4.14.1/lib/gitlab/client/versions.rb:15:in `version'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/ci_source/gitlab_ci.rb:42:in `determine_merge_request_id'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/ci_source/gitlab_ci.rb:31:in `validates_as_pr?'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/danger_core/executor.rb:63:in `validate_pr!'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/danger_core/executor.rb:47:in `validate!'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/danger_core/executor.rb:22:in `run'
   /usr/local/bundle/gems/danger-6.3.1/lib/danger/commands/runner.rb:73:in `run'
   /usr/local/bundle/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
   /usr/local/bundle/gems/danger-6.3.1/bin/danger:5:in `<top (required)>'
   /usr/local/bundle/bin/danger:23:in `load'
   /usr/local/bundle/bin/danger:23:in `<top (required)>'
 bundler: failed to load command: danger (/usr/local/bundle/bin/danger)
 ERROR: Job failed: command terminated with exit code 1
```

## Your Environment

* Which CI are you running on?
**Repo and CI in Gitlab our host**
* Are you running the latest version of Danger?
**yes**
* What is your Dangerfile?

  ```ruby
  message("Hello, this worked")

  ```

**Comment by orta** [comment]
I'd recommend adding some debugging logs to find out what JSON is crashing it

**Comment by fadhlimaulidri** [comment]
> I'd recommend adding some debugging logs to find out what JSON is crashing it

Alright, i'm waiting

**Comment by orta** [comment]
No worries

**Comment by fadhlimaulidri** [comment]
any update @orta ?

**Comment by orta** [comment]
Nothing for me, I don't fix other people's problems - that doesn't work at my scale of OSS. 

Happy to merge your PR though.

**Comment by fadhlimaulidri** [comment]
this is because any IAP setup
