### ISSUE TITLE
Gitlab auto assignee: `Dangerfile` file: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by s3kkt** [danger/danger#1223]
# Report

## What did you do?
I run danger in Docker within gitlab-ci.yml and I want to assign MR to random project group member.
I'm trying to use example "Select a random group member as assignee if no assignee is selected" from [this file](https://github.com/danger/danger/blob/master/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb)
I've set local variables in Dangerfile 
`project_id = ENV['CI_PROJECT_ID']`
`mr_id = ENV['CI_MERGE_REQUEST_IID']`

There is 2 approvals required in my project settings and about of 5 members with 'developer' permissions and higher.

## What did you expect to happen?
I expect that script will assign MR to random member of my Gitlab project group

## What happened instead?

I have an error when run 
```bash
bundle exec danger --fail-on-errors=true
```
```bash
 bundler: failed to load command: danger (/usr/local/bundle/bin/ruby/2.5.0/bin/danger)
 Danger::DSLError: 
 [!] Invalid `Dangerfile` file: undefined method `[]' for nil:NilClass
  #  from Dangerfile:20
  #  -------------------------------------------
  #  unless gitlab.mr_json["assignee"]
  >    reviewer = gitlab.api.group_members(gitlab.api.merge_request_approvals(project_id, mr_id).to_hash["approver_groups"].first["group"]["id"]).sample
  #    if gitlab.api.group_members(gitlab.api.merge_request_approvals(project_id, mr_id).to_hash["approver_groups"].first["group"]["id"]).length > 1
  #  -------------------------------------------
   Dangerfile:20:in `eval_file'
   /danger/lib/danger/danger_core/dangerfile.rb:307:in `eval'
   /danger/lib/danger/danger_core/dangerfile.rb:307:in `eval_file'
   /danger/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
   /danger/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
   /danger/lib/danger/danger_core/dangerfile.rb:197:in `parse'
   /danger/lib/danger/danger_core/dangerfile.rb:283:in `run'
   /danger/lib/danger/danger_core/executor.rb:29:in `run'
   /danger/lib/danger/commands/runner.rb:73:in `run'
   /usr/local/bundle/bin/ruby/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
   /danger/bin/danger:5:in `<top (required)>'
   /usr/local/bundle/bin/ruby/2.5.0/bin/danger:23:in `load'
   /usr/local/bundle/bin/ruby/2.5.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on?
Gitlab 12.8.1-ee
* Are you running the latest version of Danger?
Yes: `7.0.1`
* What is your Dangerfile?

```ruby
project_id = ENV['CI_PROJECT_ID']
mr_id = ENV['CI_MERGE_REQUEST_IID']

unless gitlab.mr_json["assignee"]
  reviewer = gitlab.api.group_members(gitlab.api.merge_request_approvals(project_id, mr_id).to_hash["approver_groups"].first["group"]["id"]).sample
  if gitlab.api.group_members(gitlab.api.merge_request_approvals(project_id, mr_id).to_hash["approver_groups"].first["group"]["id"]).length > 1
    while reviewer.to_hash["id"] == gitlab.mr_json["author"]["id"] do
      reviewer = gitlab.api.group_members(gitlab.api.merge_request_approvals(project_id, mr_id).to_hash["approver_groups"].first["group"]["id"]).sample
    end
  end
  message "Reviewer roulete rolled for: #{reviewer.to_hash['name']} (@#{reviewer.to_hash['username']})"
  gitlab.api.update_merge_request(project_id, mr_id, { assignee_id: reviewer.to_hash["id"] })
end
  ```

I'm new with Ruby, please, help me to debug my problem.

**Comment by orta** [comment]
Hi, this looks like an issue with your dangerfile code and not a bug with Danger which is what we use issues for. 

You're welcome to use the support forum for that: http://spectrum.chat/danger
