### ISSUE TITLE
NoMethodError: undefined method `unpack1' for "/":String

### ISSUE THREAD

**Issue by weemundo** [danger/danger#1224]
# Report

Hello, everyone! I have been stuck with this issue since past week or so and have not been able to figure out the cause of this issue. Everytime we try to run danger on our Mac Mini CI (using Gitlab CI). We get the following error: 

```
bundler: failed to load command: danger ($user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/danger)
NoMethodError: undefined method `unpack1' for "/":String
```
Any pointers on what I could be doing wrong? Appreciate the help. 

## What did you do?

bundle exec danger --verbose --fail-on-errors=true

## What did you expect to happen?

CI runs successfully 

## What happened instead?

Danger failed to load and runner could not proceed further . 

## Your Environment

Gitlab CI

Logs: 

  ```ruby

$ bundle exec danger --verbose --fail-on-errors=true
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/specifications/open4-1.3.4.gemspec:16.
bundler: failed to load command: danger (/$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/danger)
NoMethodError: undefined method `unpack1' for "/":String
Did you mean?  unpack
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client.rb:81:in `block in url_encode'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client.rb:81:in `gsub'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client.rb:81:in `url_encode'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gitlab-4.14.0/lib/gitlab/client/merge_requests.rb:43:in `merge_request'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.2/lib/danger/request_sources/gitlab.rb:146:in `fetch_details'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.2/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.2/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.2/lib/danger/danger_core/executor.rb:29:in `run'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.2/lib/danger/commands/runner.rb:73:in `run'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-6.3.2/bin/danger:5:in `<top (required)>'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/danger:23:in `load'
  /$user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/danger:23:in `<top (required)>'

  ```

**Comment by orta** [comment]
Looks like an issue in the gitlab gem, or we're sending a URL to it which it doesn't expect - you should look in that library on client.rb:81 and see what's up

**Comment by weemundo** [comment]
Thank you for responding, orta. 

I was able to resolve it just now, looks like I was using deprecated version of ruby: https://github.com/NARKOZ/gitlab/issues/550
