### ISSUE TITLE
Danger  Net::ReadTimeout

### ISSUE THREAD

**Issue by breisig** [danger/danger#1230]
# Report
We are running Dangerbot 7.0.0 [Running under Ruby 2.6.6] with Gitlab 12.10.3 and if we have a merge request with lots of changes/comments, our Jenkins server automatically runs Dangerbot  which starts to fail with the following error message.

```
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
  /usr/lib64/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill'
  /usr/lib64/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
  /usr/lib64/ruby/2.6.0/net/protocol.rb:201:in `readline'
  /usr/lib64/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
  /usr/lib64/ruby/2.6.0/net/http/response.rb:29:in `read_new'
  /usr/lib64/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
  /usr/lib64/ruby/2.6.0/net/http.rb:1506:in `catch'
  /usr/lib64/ruby/2.6.0/net/http.rb:1506:in `transport_request'
  /usr/lib64/ruby/2.6.0/net/http.rb:1479:in `request'
  /usr/lib64/ruby/2.6.0/net/http.rb:1472:in `block in request'
  /usr/lib64/ruby/2.6.0/net/http.rb:920:in `start'
  /usr/lib64/ruby/2.6.0/net/http.rb:1470:in `request'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/httparty-0.18.0/lib/httparty/request.rb:145:in `perform'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/httparty-0.18.0/lib/httparty.rb:594:in `perform_request'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/httparty-0.18.0/lib/httparty.rb:524:in `post'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/gitlab-4.14.1/lib/gitlab/request.rb:53:in `block (2 levels) in <class:Request>'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/gitlab-4.14.1/lib/gitlab/client/notes.rb:161:in `create_merge_request_note'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/lib/danger/request_sources/gitlab.rb:230:in `update_pull_request_with_inline_comments!'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/lib/danger/request_sources/gitlab.rb:169:in `update_pull_request!'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/lib/danger/danger_core/dangerfile.rb:260:in `post_results'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/lib/danger/danger_core/dangerfile.rb:288:in `run'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/lib/danger/danger_core/executor.rb:29:in `run'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/lib/danger/commands/runner.rb:73:in `run'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /var/lib/jenkins/.gem/ruby/2.6.0/gems/danger-7.0.0/bin/danger:5:in `<top (required)>'
  /var/lib/jenkins/.gem/ruby/2.6.0/bin/danger:23:in `load'
  /var/lib/jenkins/.gem/ruby/2.6.0/bin/danger:23:in `<top (required)>'
```

Is there a parameter or config option to increase the timeout? [or environment variable?] We would like to get the timeouts to stop.

## What did you do?
Run `danger --fail-on-errors=true --remove-previous-comments`

## What did you expect to happen?
Not to timeout

ℹ Please replace this with what you expected to happen.
Running your Dangerfile without it timing out.

## What happened instead?
Timeout error message.

## Your Environment
 - Jenkins
 - Gitlab
 - Dangerbot 7.0.0
 - Ruby 2.6.6

**Comment by orta** [comment]
Sounds like the CI can't reach your GitLab API - likely bad config?

**Comment by afaucogney** [comment]
We are in the same situation, since a long time. It' happen time to time...
I though in the beginning it was about size of the MR, so we just disabled inline comment, but nothing really changed (at usage point of view)

If MR may have a limit, that would be good that danger stop pushing information before that limit. I mean, rather than implementing a limit mechanism for every danger plugin, would not be that good, to implement the limit at the danger/gitlab plugin level.
```
gitlab.max_warning
gitlab.max_error
```
then trigger a another warning /error with the remaining count that has not been shown.

**Comment by orta** [comment]
in github we limit the amount of characters a comment can be, I would have expected something like that to happen on gitlab but maybe it doesn't

**Comment by afaucogney** [comment]
@orta How may know about this for gitlab ?

**Comment by orta** [comment]
Read the code, and look at the API docs?

**Comment by breisig** [comment]
Still, Shouldn't there be a command line or config option for danger to increase the timeout value?

**Comment by orta** [comment]
Sure, you're welcome to add something to the `gitlab` object which lets you set something like `gitlab.timeout_interval = 5000`
