### ISSUE TITLE
Temporary failure in name resolution when trying commenting Github PR !

### ISSUE THREAD

**Issue by afaucogney** [danger/danger#1279]
# Report

## What did you do?

I run Danger from bitrise (bitrise step) to comment Github PR of a private repo:

```
Checking dependencies
Bundler...
Bundler is not installed
Installing Bundler
$ gem "install" "bundler" "--force" "--no-document" "--version" "1.17.2"
Successfully installed bundler-1.17.2
1 gem installed
Bundler installed
Installing dependencies from your gem file
$ bundle "install"
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.............
Using public_suffix 4.0.6
Using addressable 2.7.0
Fetching ansi 1.5.0
Installing ansi 1.5.0
Fetching ast 2.4.1
Installing ast 2.4.1
Using bundler 1.17.2
Using claide 1.0.3
Using colored2 3.1.2
Fetching cork 0.3.0
Installing cork 0.3.0
Fetching nap 1.1.0
Installing nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Using ruby2_keywords 0.0.2
Using faraday 1.1.0
Fetching faraday-http-cache 2.2.0
Installing faraday-http-cache 2.2.0
Fetching rchardet 1.8.0
Installing rchardet 1.8.0
Fetching git 1.7.0
Installing git 1.7.0
Fetching rexml 3.2.4
Installing rexml 3.2.4
Fetching kramdown 2.3.0
Installing kramdown 2.3.0
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching no_proxy_fix 0.1.2
Installing no_proxy_fix 0.1.2
Fetching sawyer 0.8.2
Installing sawyer 0.8.2
Fetching octokit 4.19.0
Installing octokit 4.19.0
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Fetching danger 8.2.1
Installing danger 8.2.1
Fetching danger-plugin-api 1.0.0
Installing danger-plugin-api 1.0.0
Fetching ruby-ll 2.1.2
Installing ruby-ll 2.1.2 with native extensions
Fetching oga 3.3
Installing oga 3.3 with native extensions
Fetching danger-android_lint 0.0.8
Installing danger-android_lint 0.0.8
Fetching danger-kotlin_detekt 0.0.3
Installing danger-kotlin_detekt 0.0.3
Bundle complete! 3 Gemfile dependencies, 31 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Running danger
$ bundle "exec" "danger" "--fail-on-errors=false"
bundler: failed to load command: danger (/usr/local/bin/danger)
Faraday::ConnectionFailed: Failed to open TCP connection to git.xxxxxxx.com:443 (getaddrinfo: Temporary failure in name resolution)
  /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `initialize'
  /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `open'
  /usr/local/lib/ruby/2.7.0/net/http.rb:960:in `block in connect'
  /usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
  /usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
  /usr/local/lib/ruby/2.7.0/net/http.rb:958:in `connect'
  /usr/local/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
  /usr/local/lib/ruby/2.7.0/net/http.rb:932:in `start'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:144:in `request_via_get_method'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:135:in `request_with_wrapped_block'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:128:in `perform_request'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:70:in `block in call'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/adapter.rb:61:in `connection'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/adapter/net_http.rb:68:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/response.rb:11:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/response.rb:11:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
  /usr/local/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/request/retry.rb:148:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/rack_builder.rb:154:in `build_response'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/connection.rb:492:in `run_request'
  /usr/local/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/connection.rb:198:in `get'
  /usr/local/lib/ruby/gems/2.7.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
  /usr/local/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/connection.rb:156:in `request'
  /usr/local/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/connection.rb:19:in `get'
  /usr/local/lib/ruby/gems/2.7.0/gems/octokit-4.19.0/lib/octokit/client/pull_requests.rb:33:in `pull_request'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.1/lib/danger/request_sources/github/github.rb:121:in `fetch_details'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.1/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.1/lib/danger/danger_core/dangerfile.rb:276:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.1/lib/danger/danger_core/executor.rb:29:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.1/lib/danger/commands/runner.rb:73:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.1/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:23:in `load'
  /usr/local/bin/danger:23:in `<top (required)>'
Failed to run bundle exec danger, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | danger (exit code: 1)                                         | 12.77 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-danger/issues        |
| Source: https://github.com/bitrise-steplib/steps-danger                      |
+---+---------------------------------------------------------------+----------+
```

I'm used to work with Danger from Gitlab 
That's my first conf with github

I setup a bot with written right on the repo
I tried with 3 levels of personnel token rights (up to full access)

## What did you expect to happen?

I expect to get connection

## What happened instead?

 Temporary failure in name resolution

## Your Environment

* Which CI are you running on? Bitrise
The github repo is private, in SAAS mode
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

issue seems to be before running the dangerfile.

**Comment by orta** [comment]
This is likely a config setup issue in your bitwise/github

**Comment by afaucogney** [comment]
@orta Why do you thinks that would be the case ?
The step is trivial:
```yaml
    steps:
      - danger:
          inputs:
            - additional_options: "--fail-on-errors=false"
            - github_api_token: "$DANGER_GITHUB_API_TOKEN"
```

Bitrise succeed to clone git branches
I used also curl to get branches to test the token. This is working (from my place)

What else could be wrong ?

**Comment by afaucogney** [comment]
This was configuration issue. I use DAnger own EnvVar for setting up the Bitrise step, this was triggering conflict !
