### ISSUE TITLE
danger conflicts with danger-gitlab

### ISSUE THREAD

**Issue by okainov** [danger/danger#1300]
# Report

## What did you do?

    docker run --rm -it ruby bash
    > gem install danger danger-gitlab
    > touch Dangerfile
    > DANGER_GITLAB_API_TOKEN=qqq GIT_URL=https://gitlab.qqq.com/qq.git CHANGE_ID=123 JENKINS_URL=qq danger

## What did you expect to happen?

Danger runs

## What happened instead?

```
/usr/local/lib/ruby/3.0.0/rubygems/specification.rb:2241:in `raise_if_conflicts': Unable to activate gitlab-4.17.0, because terminal-table-3.0.0 conflicts with terminal-table (~> 1.5, >= 1.5.1) (Gem::ConflictError)
        from /usr/local/lib/ruby/3.0.0/rubygems/specification.rb:1364:in `activate'
        from /usr/local/lib/ruby/3.0.0/rubygems.rb:215:in `try_activate'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/request_sources/gitlab.rb:37:in `client'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/request_sources/gitlab.rb:151:in `fetch_details'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/dangerfile.rb:280:in `run'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/executor.rb:29:in `run'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/commands/runner.rb:73:in `run'
        from /usr/local/bundle/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
        from /usr/local/bundle/gems/danger-8.2.3/bin/danger:5:in `<top (required)>'
        from /usr/local/bundle/bin/danger:23:in `load'
        from /usr/local/bundle/bin/danger:23:in `<main>'
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- gitlab (LoadError)
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/request_sources/gitlab.rb:37:in `client'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/request_sources/gitlab.rb:151:in `fetch_details'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/environment_manager.rb:52:in `fill_environment_vars'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/dangerfile.rb:280:in `run'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/executor.rb:29:in `run'
        from /usr/local/bundle/gems/danger-8.2.3/lib/danger/commands/runner.rb:73:in `run'
        from /usr/local/bundle/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
        from /usr/local/bundle/gems/danger-8.2.3/bin/danger:5:in `<top (required)>'
        from /usr/local/bundle/bin/danger:23:in `load'
        from /usr/local/bundle/bin/danger:23:in `<main>'
root@f797875e1de1:/tmp#

```

In my team we're using both Github and Gitlab and I need Docker image for Danger which will be able to work with both Github and Gitlab repos. Apparently it seems to be not compatible...

**Comment by orta** [comment]
I'd take a PR updating our terminal-table, ideally in a way that allows for 1.x, 2.x and 3.x - I doubt we use their API extensively so it should be pretty reasonable to support all versions
