### ISSUE TITLE
[BUG] `slug_ssh': undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Carlos-Ot** [danger/danger#1304]
# Report

## What did you do?

ℹ Please replace this with what you did.
I've run `bundle exec danger` on my Jenkins Pipeline

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
Running my Dangerfile without it crashing.

## What happened instead?

ℹ Please replace this with of what happened instead.
I got the following error:
```ruby
/home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/ci_source/jenkins.rb:100:in `slug_ssh': undefined method `match' for nil:NilClass (NoMethodError)
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/ci_source/jenkins.rb:87:in `repo_slug'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/ci_source/jenkins.rb:82:in `initialize'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/danger_core/environment_manager.rb:30:in `new'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/danger_core/executor.rb:25:in `new'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/danger_core/executor.rb:25:in `run'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/lib/danger/commands/runner.rb:73:in `run'
	from /home/jenkins/.gem/ruby/2.5.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /home/jenkins/.gem/ruby/2.5.0/gems/danger-8.2.3/bin/danger:5:in `<top (required)>'
	from /home/jenkins/.gem/ruby/2.5.0/bin/danger:23:in `load'
	from /home/jenkins/.gem/ruby/2.5.0/bin/danger:23:in `<main>'
```

## Your Environment

* Which CI are you running on?
> Jenkins Pipeline
* Are you running the latest version of Danger?
> Yes, 8.2.3
* What is your Dangerfile?

```ruby
 ## METHODS DECLARATION ##
def checkForFileAndroid(file)
    ext = File.extname(file)
    case ext
    # Warn when a file .gradle is modified
    when ".gradle"
      message("`#{file}` was modified")
    end
    # Warn when a FileManifest.xml is modified
    message("`#{file}` was modified") if file =~ /AndroidManifest\.xml/
  end
  
  def exceptionMessages(file)
    if File.file?(file)
      message "Something went wrong checking `#{file}`. Check your Dangerfile"
    else
      message "One of modified files could not be read, does it really exist?"
    end
  end
  
  # Sometimes it's a README fix, or something like that - which isn't relevant for
  # including in a project's CHANGELOG for example
  declared_trivial = github.pr_title.include? "#trivial"
  
  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  if github.pr_title.include? "[WIP]"
      warn("PR is classed as Work in Progress")
  end
  
  # Warn when there is a big PR
  if git.lines_of_code > 500
      warn("Big PR")
  end
  
  # If these are all empty something has gone wrong, better to raise it in a comment
  if git.modified_files.empty? && git.added_files.empty? && git.deleted_files.empty?
    warn "This PR has no changes at all, this is likely an issue during development."
  end
  
  # Ensure a clean commits history
  if git.commits.any? { |c| c.message =~ /^Merge branch '#{github.branch_for_base}'/ }
    warn "Please rebase to get rid of the merge commits in this PR"
  end
  
  # Mainly to encourage writing up some reasoning about the PR, rather than
  # just leaving a title
  if github.pr_body.length < 120
    warn "Please provide a summary in the Pull Request description"
  end
  
  # Ensure that the PR title follows the convention
  if !(github.pr_title =~ /TASK-([0-9])+:(.*)/)
    warn "The Pull Request title does not follow the convention TASK-0000: PR Title text"
  end
  
  #Check modified files, apply rules to them
  git.modified_files.each do |file|
    begin
      checkForFileAndroid(file)
    rescue
      exceptionMessages(file)
    end
  end

  github.dismiss_out_of_range_messages
  
  # ktlint
  checkstyle_format.base_path = Dir.pwd
  checkstyle_format.report "./../build/reports/ktlint/ktlint-report.xml"
  
  # AndroidLint
  android_lint.report_file = "./../build/reports/lint/lint-report.xml"
  android_lint.filtering = true
  android_lint.severity = "Error"
  android_lint.lint(inline_mode: true)
  ```

**Comment by orta** [comment]
Looks like it failed to get your repo address from: https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L126

**Comment by Carlos-Ot** [comment]
> Looks like it failed to get your repo address from: https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L126

I see that. The problem is that I've added the CHANGE_URL variable to my Jenkins Job but I'm still getting this error.

**Comment by marcus-martins** [comment]
> Just found what I did wrong. I'll close this issue.

Could you share what the problem was? I'm having the same error here.
