### ISSUE TITLE
`bundle exec danger pr <PR url>` freezes after it prints "Info:"

### ISSUE THREAD

**Issue by rogerluan** [danger/danger#1313]
# Report

## What did you do?

`bundle exec danger pr <PR url>`

## What did you expect to happen?

It should analyze the given PR.

## What happened instead?

It prints this:

```
Running your Dangerfile against this PR - <the PR URL that I passed>
Turning on --verbose

Info:

```

Then freezes. After pressing ctrl + C  once, this is the stack trace that I get:

```
^CTraceback (most recent call last):
    38: from /Users/rogerluan/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
    37: from /Users/rogerluan/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
    36: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/exe/bundle:37:in `<top (required)>'
    35: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
    34: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/exe/bundle:49:in `block in <top (required)>'
    33: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/cli.rb:24:in `start'
    32: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    31: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/cli.rb:30:in `dispatch'
    30: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    29: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    28: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    27: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/cli.rb:494:in `exec'
    26: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/cli/exec.rb:28:in `run'
    25: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/cli/exec.rb:63:in `kernel_load'
    24: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.14/lib/bundler/cli/exec.rb:63:in `load'
    23: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/bin/danger:23:in `<top (required)>'
    22: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/bin/danger:23:in `load'
    21: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/bin/danger:5:in `<top (required)>'
    20: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    19: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/commands/pr.rb:63:in `run'
    18: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/commands/local_helpers/local_setup.rb:43:in `setup'
    17: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/commands/pr.rb:64:in `block in run'
    16: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/danger_core/dangerfile.rb:287:in `run'
    15: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/danger_core/dangerfile.rb:179:in `parse'
    14: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/danger_core/dangerfile.rb:167:in `print_known_info'
    13: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/cork-0.3.0/lib/cork/board.rb:184:in `section'
    12: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/danger-8.3.1/lib/danger/danger_core/dangerfile.rb:171:in `block in print_known_info'
    11: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/cork-0.3.0/lib/cork/board.rb:67:in `puts'
    10: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/cork-0.3.0/lib/cork/board.rb:67:in `puts'
     9: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `render'
     8: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `map'
     7: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/table.rb:142:in `block in render'
     6: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/row.rb:40:in `render'
     5: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/row.rb:40:in `map'
     4: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/row.rb:41:in `block in render'
     3: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/row.rb:41:in `map'
     2: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/row.rb:42:in `block (2 levels) in render'
     1: from /Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/cell.rb:62:in `render'
/Users/rogerluan/Documents/Projects/redacted/.vendor/ruby/2.6.0/gems/terminal-table-1.8.0/lib/terminal-table/cell.rb:52:in `lines': Interrupt
```

## Your Environment

I'm running this locally, on a M1 machine running macOS 11.4.

* Are you running the latest version of Danger? Yes
* What is your Dangerfile? - Irrelevant, I tried with an empty Dangerfile.

**Comment by orta** [comment]
Strange! No idea off the top of my head (and from that stack)

**Comment by BobbyMcWho** [comment]
Mine hangs there, but will work _eventually_ if you wait for it. The table output looks a mess though in `pr` comapared to  `local`

**Comment by Nirma** [comment]
I am seeing this issue as well. Hmm... Any updates?

Machine being used is an arm64 (M2) box and the version of danger I am using is `9.4.3`.

Command being run is `bundle exec pr <URL>` and it is a private repo but `DANGER_GITHUB_API_TOKEN` is properly set.
