### ISSUE TITLE
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by rogerluan** [danger/danger#1336]
# Report

## What did you do?

`bundle exec danger dry_run`

## What did you expect to happen?

Execute a dry run of danger.

## What happened instead?

```sh
fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
bundler: failed to load command: danger (/Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/bin/danger)
Traceback (most recent call last):
    25: from /Users/rogerluan/.rbenv/versions/2.6.5/bin/bundle:23:in `<main>'
    24: from /Users/rogerluan/.rbenv/versions/2.6.5/bin/bundle:23:in `load'
    23: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
    22: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
    21: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
    20: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:25:in `start'
    19: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    18: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:31:in `dispatch'
    17: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    16: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    15: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    14: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:478:in `exec'
    13: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:23:in `run'
    12: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:58:in `kernel_load'
    11: from /Users/rogerluan/.rbenv/versions/2.6.5/lib/ruby/site_ruby/2.6.0/bundler/cli/exec.rb:58:in `load'
    10: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/bin/danger:25:in `<top (required)>'
     9: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/bin/danger:25:in `load'
     8: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/bin/danger:5:in `<top (required)>'
     7: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
     6: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/commands/dry_run.rb:44:in `run'
     5: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:284:in `run'
     4: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/danger_core/dangerfile.rb:273:in `setup_for_running'
     3: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/danger_core/environment_manager.rb:58:in `ensure_danger_branches_are_setup'
     2: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/request_sources/local_only.rb:35:in `setup_danger_branches'
     1: from /Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/request_sources/local_only.rb:35:in `each'
/Users/rogerluan/Documents/Projects/redacted/.bundle/ruby/2.6.0/gems/danger-8.4.2/lib/danger/request_sources/local_only.rb:36:in `block in setup_danger_branches': Specified commit 'origin/master' not found (RuntimeError)
```

The catch here is that this repository doesn't have an `origin/master` branch (there's no `master` branch at all and the default branch has another name). I find it very curious that I couldn't find any information online (or in this repo's issues) about this crash though, because many people have default branches such as `main` or `develop` nowadays.

## Your Environment

* Which CI are you running on? **_I'm attempting to run locally_**
* Are you running the latest version of Danger? **_8.4.2_**
* What is your Dangerfile? **_Not applicable (this is irrelevant to reproduce this issue)_**

**Comment by orta** [comment]
Happy to have dry-run also look for a main/develop branch first 👍🏻

**Comment by rogerluan** [comment]
@orta I think that solution also wouldn't work in all cases. Why doesn't it run against the repository's default branch? There're a few techniques here https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch

**Comment by orta** [comment]
I'm happy for that to happen instead 👍🏻 ( note that some of these features seem to require a recent copy of git, so you might need to handle the case where it can't be looked up)

**Comment by rogerluan** [comment]
@orta could you point me to where this check is currently being made? I couldn't spot it in the code (searched for origin/master) 😬 
I'll open a PR if I can figure this out 💪

**Comment by rogerluan** [comment]
Hah! I just learned about `DANGER_LOCAL_BASE` 😄 Is this documented somewhere?

**Comment by manicmaniac** [comment]
You can use `--base` option too, like `danger --base=main dry_run`. Hope it works.

Let me close this issue. Feel free to open this one if you want to improve logic to look up head commit.
