### ISSUE TITLE
Azure pipeline ci running Danger returns `setup_danger_branches': undefined method `sub' for nil:NilClass

### ISSUE THREAD

**Issue by douglastaquary** [danger/danger#1341]
# Report

## What did you do?

Hey guys,
All right with you? Hope so :) First thanks for sharing this awesome tool!

Need help. I'm getting an error running Danger.

I'm runnig `gem install danger --version '~> 8.2.3' && danger --verbose` in Azure CI.
In mid-October I started configuring Danger to run on Azure Pipelines
I set `DANGER_VSTS_API_TOKEN` and `DANGER_VSTS_HOST` as environment variables. 
I runned and it worked magically. Amazing. 🥳

We are currently in error when trying to run danger. 

```
⚠️ Important detail: 

When I ran Danger and it worked, before that step the unit tests were run and then we ran Danger. 

We are currently trying to run Danger without running the unit tests first (no unit tests configured in the pipeline yet). 

☝🏼Doubt: 

Do I always need to run unit tests before running Danger to work properly?
```

## What did you expect to happen?

Run the danger without running the unit tests first and it commits the comment in PR

## What happened instead?

Running Danger is currently in error:

```
/usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/lib/danger/request_sources/vsts.rb:56:in `setup_danger_branches': undefined method `sub' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/lib/danger/danger_core/environment_manager.rb:58:in `ensure_danger_branches_are_setup'
	from /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/lib/danger/danger_core/dangerfile.rb:273:in `setup_for_running'
	from /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/lib/danger/danger_core/dangerfile.rb:284:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/lib/danger/danger_core/executor.rb:29:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/lib/danger/commands/runner.rb:73:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/danger-8.2.3/bin/danger:5:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/danger:25:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/danger:25:in `<main>'
##[error]Bash exited with code '1'.
```

## Environment

* Which CI are you running on?

Azure Pipelines
Image: macOS-10.15

* Are you running the latest version of Danger?
No. 
I ran Danger `8.2.3` because it was the version that worked before. 
I tried to run with the latest version `8.4.2` but the error is the same.

* What is your Dangerfile?
```
has_app_changes = !git.modified_files.grep(/ProjectName/).empty?
has_test_changes = !git.modified_files.grep(/ProjectNameTests/).empty?

if has_app_changes && !has_test_changes
  warn("Os testes não foram atualizados", sticky: false)
end

#warn "This PR does not have any assignees yet." unless vsts.pr_json["reviewers"].length == 0

#WARN WHEN A PR IS CLASSED AS WORK IN PROGRESS
warn "Este PR está classificado como `in Progress`." if vsts.pr_title.include? "[WIP]"

# Warn when there is a big PR
warn("Big PR 🤯") if git.lines_of_code > 200

# ENSURE THERE IS A SUMMARY FOR A PR
failure "Por gentileza, certifique-se de que haja um resumo para o PR." if vsts.pr_body.length < 5
```

  ```ruby

Ruby Version: 2.7.0

  ```

**Comment by douglastaquary** [comment]
Hello everyone, everything good ?

I'm closing this PR because I solved the problem. I updated the personal access token and it worked.
