### ISSUE TITLE
Error installing and running danger (There is a circular dependency between faraday-patron and faraday)

### ISSUE THREAD

**Issue by sombrerosheep** [danger/danger#1342]
# Report

## What did you do?

We're using drone for ci/cd. Pr's include a step to run danger:
```
gem install danger
danger
```

## What did you expect to happen?

danger to install and run properly

## What happened instead?

Explosions:
We're using drone for ci/cd and today began getting the following error:
```
2: Pulling from library/ruby
Digest: sha256:7667608a9fc0ec9ee434a1957f21e981ccdde4b60c2c3d86b19cf87e4d300f70
Status: Downloaded newer image for ruby:2
+ gem install danger
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between faraday-patron and faraday
```

Faraday seems to be the cause (v `1.9`) specifically. Prior builds that pulled in `1.8` of Faraday worked.
I attempted to override (`gem install danger:8.4.1 faraday:1.8`) but was unsuccessful (perhaps my unfamiliarity with ruby or inability to override transitive dependencies). The output of that is here:
```
2: Pulling from library/ruby
Digest: sha256:7667608a9fc0ec9ee434a1957f21e981ccdde4b60c2c3d86b19cf87e4d300f70
Status: Downloaded newer image for ruby:2
+ gem install danger:8.4.1 faraday:1.8
Successfully installed claide-1.0.3
Successfully installed open4-1.3.4
Successfully installed colored2-3.1.2
Successfully installed cork-0.3.0
Successfully installed nap-1.1.0
Successfully installed claide-plugins-0.9.2
Successfully installed rchardet-1.8.0
Successfully installed git-1.10.1
Successfully installed faraday-em_http-1.0.0
Successfully installed faraday-em_synchrony-1.0.0
Successfully installed faraday-excon-1.1.0
Successfully installed httpclient-2.8.3
Successfully installed faraday-httpclient-2.0.1
Successfully installed multipart-post-2.1.1
Successfully installed faraday-multipart-1.0.1
Successfully installed faraday-net_http-2.0.1
Successfully installed connection_pool-2.2.5
Successfully installed net-http-persistent-4.0.1
Successfully installed faraday-net_http_persistent-2.0.1
Building native extensions. This could take a while...

Thank you for installing Patron. On OSX, make sure you are using libCURL with OpenSSL.
SecureTransport-based builds might cause crashes in forking environment.

For more info see https://github.com/curl/curl/issues/788
Successfully installed patron-0.13.3
Successfully installed faraday-patron-2.0.1
Successfully installed faraday-rack-1.0.0
Successfully installed faraday-retry-1.0.2
Successfully installed ruby2_keywords-0.0.5
Successfully installed faraday-1.9.0
Successfully installed faraday-http-cache-2.2.0
Successfully installed kramdown-2.3.1
Successfully installed kramdown-parser-gfm-1.1.0
Successfully installed public_suffix-4.0.6
Successfully installed addressable-2.8.0
Successfully installed sawyer-0.8.2
Successfully installed octokit-4.21.0
Successfully installed unicode-display_width-2.1.0
Successfully installed terminal-table-3.0.2
Successfully installed no_proxy_fix-0.1.2
Successfully installed danger-8.4.1
Successfully installed faraday-httpclient-1.0.1
Successfully installed faraday-net_http-1.0.1
Successfully installed faraday-net_http_persistent-1.2.0
Successfully installed faraday-patron-1.0.0
Successfully installed faraday-1.8.0
41 gems installed
+ danger
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- /usr/local/bundle/gems/faraday-1.9.0/lib/faraday/request/retry (LoadError)
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:28:in `block in <module:Default>'
	from /usr/local/bundle/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:76:in `build'
	from /usr/local/bundle/gems/faraday-1.9.0/lib/faraday/rack_builder.rb:65:in `initialize'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:27:in `new'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:27:in `<module:Default>'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:9:in `<module:Octokit>'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit/default.rb:6:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/octokit-4.21.0/lib/octokit.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger/request_sources/github/github.rb:5:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger/ci_source/local_git_repo.rb:6:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger/commands/init.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger/commands/runner.rb:3:in `<class:Runner>'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger/commands/runner.rb:2:in `<module:Danger>'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger/commands/runner.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/danger-8.4.1/lib/danger.rb:4:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	from /usr/local/bundle/gems/danger-8.4.1/bin/danger:4:in `<top (required)>'
	from /usr/local/bundle/bin/danger:23:in `load'
	from /usr/local/bundle/bin/danger:23:in `<main>'
```

## Your Environment

* Which CI are you running on? Drone (v 2.7.3)
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

```ruby
#!/usr/bin/env ruby
require 'yaml'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
REDACTED_WEB_PATH = 'REDACTED-web/src/main/'
MANAGED_FILE_REPOSITORY_FILE = "#{REDACTED_WEB_PATH}java/com/REDACTED/REDACTED/REDACTED/REDACTED.java"

def warn_if_sensitive_files_changed (path, warning_reason)
  if (git.modified_files.include?("#{path}") | git.deleted_files.include?("#{path}"))
    warn("Are you sure you want to change or delete files in #{path} :cold_sweat:\nWarning reason- #{warning_reason}")
  end
end

def fail_if_sensitive_files_changed (path, reviewer, failed_reason)
  if (git.modified_files.include?("#{path}") | git.deleted_files.include?("#{path}"))
    fail("Files in #{path} are changed or deleted. #{reviewer} will need to approve this PR; please add one or both as a reviewer..\nFailed reason- #{failed_reason}")
  end
end

def get_list_of_files_touched_by_extension(extension)
  touched_files = (git.added_files | git.modified_files).select {|file| file.end_with? extension}
end

def validate_json_files
  files = get_list_of_files_touched_by_extension('.json')
  files.each do |json_file|
    contents = IO.read(json_file)
    unless valid_json?(contents)
      fail "Failed to validate #{json_file} :no_entry_sign:"
    end
  end
end

def valid_json?(json)
  JSON.parse(json)
  return true
rescue JSON::ParserError => e
  return false
end

def find_managed_file_string_on_file
  #files = get_list_of_files_touched_by_extension('.java')
  #files.each do |java_file|
  #  begin
  #      File.foreach(java_file).with_index do |line|
  #        if line[/(managed)(.)(file)/i]
  #          warn "You have changed #{java_file} which contains some combination of the phrase, 'managed_file'. In order to protect against failed
  #                deployments, @REDACTED @REDACTED or @REDACTED will need to approve this PR; please add one or more as a reviewer."
  #          break
  #        end
  #      end
  #  else
  #      warn "problem reading file #{java_file}. Probably because it moved"
  #  end
  #end
end

find_managed_file_string_on_file
validate_json_files

warn_if_sensitive_files_changed("#{REDACTED_WEB_PATH}resources/META-INF/saml/*", "Changes to the files will impact to the authentication of health pages.")
warn_if_sensitive_files_changed("#{REDACTED_WEB_PATH}resources/META-INF/spring/logback.groovy","Changes to logging, notify Logcentral Admin @REDACTED @Deprecating - so please make sure to add the configuration in docker.")

warn_if_sensitive_files_changed("docker/*","Changes to the files may impact service configuration in server. REDACTED/REDACTED-support ")

fail_if_sensitive_files_changed("MANAGED_FILE_REPOSITORY_FILE", "@REDACTED @REDACTED or @REDACTED","Changes to these files may impact to performance")
fail_if_sensitive_files_changed("scripts/run_flyway*", "REDACTED/REDACTED-support","Changes to this file may impact database")
fail_if_sensitive_files_changed("REDACTED-db/src/resources/flyway-*", "REDACTED/REDACTED-support","Changes to this file may impact database")

```

**Comment by sombrerosheep** [comment]
It looks like the Faraday maintainers are aware and working on a fix while I was submitting this: https://github.com/lostisland/faraday/issues/1369
