### ISSUE TITLE
`danger local` broken

### ISSUE THREAD

**Issue by jeroenvisser101** [danger/danger#140]
I can't seem to run `danger local` anymore :(

```
Running your Dangerfile against this PR - https://github.com/danger/danger/pull/135
Turning on --verbose

bundler: failed to load command: danger (/usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/danger)
Git::GitExecuteError: git '--git-dir=/Users/jeroenvisser/Projects/danger/danger/.git' '--work-tree=/Users/jeroenvisser/Projects/danger/danger' diff '--numstat' 'c'  2>&1:fatal: ambiguous argument 'c': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:861:in `command_lines'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:362:in `diff_stats'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/diff.rb:113:in `cache_stats'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/diff.rb:34:in `lines'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/scm_source/git_repo.rb:31:in `lines_of_code'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/dangerfile_dsl.rb:64:in `method_missing'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/dangerfile.rb:30:in `block in print_known_info'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/dangerfile.rb:28:in `each'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/dangerfile.rb:28:in `print_known_info'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/dangerfile.rb:62:in `parse'
  /Users/jeroenvisser/Projects/danger/danger/lib/danger/commands/local.rb:50:in `run'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
  /Users/jeroenvisser/Projects/danger/danger/bin/danger:5:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/danger:23:in `load'
  /usr/local/opt/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/danger:23:in `<top (required)>'
```

Could it be, by any chance, that ruby-git doesn't support newer versions of git? (`git version 2.7.2`)

**Comment by jeroenvisser101** [comment]
Actually, seems to be related to using ZSH

**Comment by orta** [comment]
```
/Users/orta/.rvm/gems/ruby-2.1.3/gems/git-1.2.9.1/lib/git/lib.rb:917:in `command': git '--git-dir=/Users/orta/dev/ruby/libs/danger/.git' '--work-tree=/Users/orta/dev/ruby/libs/danger' diff '--numstat' 'c'  2>&1:fatal: ambiguous argument 'c': unknown revision or path not in the working tree. (Git::GitExecuteError)
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
	from /Users/orta/.rvm/gems/ruby-2.1.3/gems/git-1.2.9.1/lib/git/lib.rb:846:in `command_lines'
	from /Users/orta/.rvm/gems/ruby-2.1.3/gems/git-1.2.9.1/lib/git/lib.rb:362:in `diff_stats'
``` 

I get it too

**Comment by jeroenvisser101** [comment]
Working on a fix!
