### ISSUE TITLE
Local run fails because of ambiguous arguments

### ISSUE THREAD

**Issue by mrackwitz** [danger/danger#192]
Is that broken or am I'm doing something wrong?

```shell
$ bundle exec danger local
Running your Dangerfile against this PR - https://github.com/CocoaPods/CocoaPods/pull/5219
Turning on --verbose

fatal: ambiguous argument 'danger_base': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'danger_head': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

## Tested versions

Danger 0.7.3, 0.7.2
Git 2.8.1, 2.6.4

**Comment by orta** [comment]
I'm seeing it too

![screen shot 2016-05-03 at 14 52 45](https://cloud.githubusercontent.com/assets/49038/14985286/ba1a17a0-113e-11e6-8539-c0330522917d.png)

( It does run my Dangerfile though )

**Comment by jeroenvisser101** [comment]
It could be related to the git version, we had issues with that before.

**Comment by orta** [comment]
I think we need to re-rewrite the git diff parser again, I don't like where this current one is. It _works_ but it has weird side effects like that. Perhaps its simplest that we write our own diff ASCII output parser.

**Comment by jeroenvisser101** [comment]
We could base it [on this library](https://github.com/packsaddle/ruby-git_diff_parser)

**Comment by jeroenvisser101** [comment]
I'm going to debug this in 4 hours

**Comment by jeroenvisser101** [comment]
#134 should fix this

**Comment by jeroenvisser101** [comment]
*Sorry, posted this on the wrong issue* 😕

so this is actually because [the call that's being done in `runner.rb`](https://github.com/danger/danger/blob/342dac4dc17dd3bc575ab0f0384c736a2ba6023a/lib/danger/commands/runner.rb#L39) isn't in the local runner, and that call sets up the branches.

**Comment by orta** [comment]
This should be fixed in `0.7.4` @mrackwitz which just got released

**Comment by daniel-beard** [comment]
I'm running into this issue, not calling with local though running on CI.

```
/Users/builduser/.rvm/gems/ruby-2.2.2/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/Users/builduser/jenkins/workspace/mobile-consumer/mobile-iphone-consumer/.git' '--work-tree=/Users/builduser/jenkins/workspace/mobile-consumer/mobile-iphone-consumer' diff '--numstat' 'master' 'dbeard_danger_implement_warning_for_nst_event_changes'  2>&1:fatal: ambiguous argument 'dbeard_danger_implement_warning_for_nst_event_changes': unknown revision or path not in the working tree. (Git::GitExecuteError)
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/git-1.3.0/lib/git/lib.rb:861:in `command_lines'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/git-1.3.0/lib/git/lib.rb:362:in `diff_stats'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/git-1.3.0/lib/git/diff.rb:113:in `cache_stats'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/git-1.3.0/lib/git/diff.rb:34:in `lines'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/scm_source/git_repo.rb:33:in `lines_of_code'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/dangerfile_dsl.rb:124:in `method_missing'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/dangerfile.rb:29:in `block in print_known_info'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/dangerfile.rb:28:in `each'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/dangerfile.rb:28:in `print_known_info'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/dangerfile.rb:58:in `parse'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/commands/runner.rb:48:in `run'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/bin/danger:5:in `<top (required)>'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/bin/danger:23:in `load'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/bin/danger:23:in `<main>'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/builduser/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment]
Closing as fixed 👍
