### ISSUE TITLE
GHE does not seem to work

### ISSUE THREAD

**Issue by daniel-beard** [danger/danger#206]
- I've been trying to point to a GHE instance, but even when specifying `DANGER_GITHUB_HOST` for the `local` action, it still tries to point to api.github.com rather than the GHE instance.
- Is this a known issue, or am I missing something here?
- Here's a stack trace, the 401 is because it's pointing to github.com rather than my GHE instance.

```
/Users/dbeard/.rvm/gems/ruby-2.2.4/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/myorg/myrepo/pulls/15130: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/danger-0.7.4/lib/danger/request_sources/github.rb:35:in `fetch_details'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/danger-0.7.4/lib/danger/commands/local.rb:52:in `run'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4@global/gems/danger-0.7.4/bin/danger:5:in `<top (required)>'
	from /Users/dbeard/.rvm/rubies/ruby-2.2.4/bin/danger:23:in `load'
	from /Users/dbeard/.rvm/rubies/ruby-2.2.4/bin/danger:23:in `<main>'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dbeard/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jeroenvisser101** [comment]
I've got no experience with GitHub Enterprise myself, but @dbgrandi might be able to help you out with this :)

**Comment by jeroenvisser101** [comment]
([you might want to try setting DANGET_GITHUB_API_HOST too](https://github.com/danger/danger/blob/master/lib/danger/request_sources/github.rb#L17-L19))

**Comment by daniel-beard** [comment]
Ah, yes, `DANGER_GITHUB_API_HOST` get me further

**Comment by daniel-beard** [comment]
That was what I needed. Thanks for the super quick reply @jeroenvisser101 !

**Comment by jeroenvisser101** [comment]
@daniel-beard that's cool! :)

**Comment by jeroenvisser101** [comment]
@daniel-beard if you are allowed to, please do share your Dangerfile with the public, we'd love to see some in-the-wild usages of it :)

**Comment by daniel-beard** [comment]
I don't have anything quite useful yet, as I'm just starting to experiment. Once I have something up and working, I'll make sure to :D

**Comment by jeroenvisser101** [comment]
@daniel-beard that's great, thanks! Hope you have some fun implementing it :)
