### ISSUE TITLE
Danger local doesn't work for private repos

### ISSUE THREAD

**Issue by starsirius** [danger/danger#231]
```
$ bundle exec danger local
Running your Dangerfile against this PR - https://github.com/starsirius/superposition/pull/37
Turning on --verbose

/Users/starsirius/.rvm/gems/ruby-2.2.2/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/starsirius/superposition/pulls/37: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/request_sources/github.rb:35:in `fetch_details'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/lib/danger/commands/local.rb:52:in `run'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/gems/danger-0.7.4/bin/danger:5:in `<top (required)>'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/bin/danger:23:in `load'
	from /Users/starsirius/.rvm/gems/ruby-2.2.2/bin/danger:23:in `<main>'
```

**Comment by justMaku** [comment]
It should work if you provide the GitHub API token in `DANGER_GITHUB_API_TOKEN` environment variable.

**Comment by orta** [comment]
Aye, I think we should make this a proper error, and give that advice - thanks @justMaku

**Comment by justMaku** [comment]
This has been resolved in #233.

**Comment by kylejm** [comment]
I've just had a case where this error did not appear for me and I got a 404 as above. The problem was that the token didn't have access to private repos, just as this error would explain. Using version 3.1.0. Reopen?

**Comment by cojoj** [comment]
Hmmm, I've configured everything correctly (I guess):

+ I have _bot_ account with **write** permissions and **Personal access token**
+ I have `Dangerfile`
+ I've set `DANGER_GITHUB_API_TOKEN`

And still I can't make `danger` work for me.
When I call `danger local` I get something like:
```
Running your Dangerfile against this PR - https://github.com/cojoj/iOS/pull/788
Turning on --verbose

/usr/local/lib/ruby/gems/2.3.0/gems/danger-3.2.1/lib/danger/request_source/github.rb:68:in `fetch_details': Repo moved or renamed, make sure to update the git remote (RuntimeError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/danger-3.2.1/lib/danger/commands/local.rb:96:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/danger-3.2.1/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'
```

When I run regular `danger` I get:
```
Could not find the type of CI for Danger to run on.
```

I'v tried to create a new `lane`, call it manually... Still nothing. Especially, I don't understand the error for the `local` call...

**Comment by orta** [comment]
Can you explain the environment in which you're running Danger? You've not said the type of CI for example? I'm not really sure what you mean by `lane` either?

**Comment by cojoj** [comment]
Hah, of course @orta 😅
I'm trying to skip CI at all and go with fastlane only. I that case, when I fire our custom `lane` eg. `fastlane ios test_lane` I also want it to produce fire sublane which will fire `danger` command.
I don't know if it's cleaner now or you want even more details. I can reference to twitter, as we've _discussed_ that matter: https://twitter.com/cojoj/status/771649891093221376

**Comment by orta** [comment]
Danger really isn't well built for doing anything outside of running on CI (`danger`), and testing existing PRs against the current rules (`danger local` ) - there's work on-going that would make what it sounds like you want possible ( https://github.com/danger/danger/pull/518 ) but it's not going to be a quick one - for now, you might be fighting an uphill battle to make anything work

**Comment by cojoj** [comment]
Hah, so looks like I was just going a little bit too far for the current state of the project 😅
Gonna stick around and wait for this local thing, since we have some problems with CI server right now and we wanted to move at least a bit of it's responsibilities to local.
Thank you very much for clarifications and keep it real! 💪
