### ISSUE TITLE
Class.singleton_class? is not available on ruby 2.0.0

### ISSUE THREAD

**Issue by orta** [danger/danger#240]
See https://travis-ci.org/realm/jazzy/builds/134747812

```sh
The command "bundle exec rake spec" exited with 0.
3.45s$ bundle exec danger
bundler: failed to load command: danger (/Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger)
NoMethodError: undefined method `singleton_class?' for Danger::DangerfileGitHubPlugin:Class
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:87:in `block in refresh_plugins'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:86:in `each'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:86:in `refresh_plugins'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/danger_core/dangerfile.rb:79:in `initialize'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/commands/runner.rb:38:in `new'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/lib/danger/commands/runner.rb:38:in `run'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/gems/danger-0.8.0/bin/danger:5:in `<top (required)>'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger:23:in `load'
  /Users/travis/build/realm/jazzy/vendor/bundle/ruby/2.0.0/bin/danger:23:in `<top (required)>'

```

**Comment by segiddins** [comment]
We should probably test on 2.0 then....

**Comment by orta** [comment]
Agree 👍
