### ISSUE TITLE
Error running bundle exec danger local: No recent pull requests found for this repo

### ISSUE THREAD

**Issue by kennethlynne** [danger/danger#276]
Related to https://github.com/danger/danger/issues/274 ?

```
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
No recent pull requests found for this repo, danger requires at least one PR for the local mode. (RuntimeError)
        /Users/kenneth_lynne/.bundle/ruby/2.3.0/danger-f84c875e6429/lib/danger/ci_source/local_git_repo.rb:52:in `initialize'
        /Users/kenneth_lynne/.bundle/ruby/2.3.0/danger-f84c875e6429/lib/danger/danger_core/environment_manager.rb:12:in `new'
        /Users/kenneth_lynne/.bundle/ruby/2.3.0/danger-f84c875e6429/lib/danger/danger_core/environment_manager.rb:12:in `block in initialize'
        /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/set.rb:306:in `each_key'
        /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/set.rb:306:in `each'
        /Users/kenneth_lynne/.bundle/ruby/2.3.0/danger-f84c875e6429/lib/danger/danger_core/environment_manager.rb:9:in `initialize'
        /Users/kenneth_lynne/.bundle/ruby/2.3.0/danger-f84c875e6429/lib/danger/commands/local.rb:29:in `new'
        /Users/kenneth_lynne/.bundle/ruby/2.3.0/danger-f84c875e6429/lib/danger/commands/local.rb:29:in `run'
```

**Comment by JuanitoFatas** [comment]
`danger local` now actually will find the most recent PR. But [in v3.5.1 we introduced a new command: `danger pr`](https://github.com/danger/danger/blob/master/CHANGELOG.md#351), please try it. Thank you for using danger! <3
