### ISSUE TITLE
bundle exec danger on CircleCI: 404 - Not found

### ISSUE THREAD

**Issue by kennethlynne** [danger/danger#277]
```
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
GET https://api.github.com/repos/EdtechFoundry/groovy-mobile/pulls/20: 404 - Not Found // See: https://developer.github.com/v3 (Octokit::NotFound)
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:154:in `request'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/connection.rb:19:in `get'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/octokit-4.3.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/bundler/gems/danger-f84c875e6429/lib/danger/request_source/github.rb:53:in `fetch_details'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/bundler/gems/danger-f84c875e6429/lib/danger/danger_core/environment_manager.rb:41:in `fill_environment_vars'
	/home/ubuntu/.rvm/gems/ruby-2.3.0/bundler/gems/danger-f84c875e6429/lib/danger/commands/runner.rb:50:in `run'
```

**Comment by orta** [comment]
Do you have your authentication tokens set up correctly? I don't think we do anything too special here

**Comment by kennethlynne** [comment]
Yes, should be set-up, but I will double check that the token is valid, and passed correctly. The feedback can probably be better in this case

**Comment by kennethlynne** [comment]
Yeah, sorry, token set up incorrectly
