### ISSUE TITLE
Danger Local should note that you can use a PR ID when it fails

### ISSUE THREAD

**Issue by orta** [danger/danger#329]
Currently 

```
➜  Quark (danger) danger local
No recent pull requests found for this repo, danger requires at least one PR for the local mode. (RuntimeError)
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/danger-0.9.0/lib/danger/ci_source/local_git_repo.rb:52:in `initialize'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/danger-0.9.0/lib/danger/danger_core/environment_manager.rb:12:in `new'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/danger-0.9.0/lib/danger/danger_core/environment_manager.rb:12:in `block in initialize'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each_key'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/2.1.0/set.rb:263:in `each'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/danger-0.9.0/lib/danger/danger_core/environment_manager.rb:9:in `initialize'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/danger-0.9.0/lib/danger/commands/local.rb:29:in `new'
    /Users/paulofaria/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/danger-0.9.0/lib/danger/commands/local.rb:29:in `run'
```

Which is meh.

This should probably be more like:

```
➜  Quark (danger) danger local
No recent pull requests found for this repo, danger requires at least one merged PR for running locally.
This could be because you are using a rebase flow instead of merges, in this case, you should run:

$ danger local --use-merged-pr=[id]

Which will let you work against an existing PR.
```

**Comment by samdmarshall** [comment]
I ran into this in a brand new repo that has no PRs or other branches yet. It caused a CI failure, which i think should not be a hard failure but instead a message like you have suggested be displayed.

**Comment by Palleas** [comment]
I'm running into this issue as well but I'm not sure how to fix it: 

```
➜  romain-pouclet.com git:(setup-danger) bundle exec danger local
bundler: failed to load command: danger (/usr/local/opt/rbenv/versions/2.2.4/bin/danger)
RuntimeError: No recent pull requests found for this repo, danger requires at least one PR for the local mode
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/ci_source/local_git_repo.rb:40:in `initialize'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/environment_manager.rb:14:in `new'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/environment_manager.rb:14:in `block in initialize'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/environment_manager.rb:9:in `each'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/environment_manager.rb:9:in `initialize'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/commands/local.rb:22:in `new'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/lib/danger/commands/local.rb:22:in `run'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/danger-0.7.3/bin/danger:5:in `<top (required)>'
  /usr/local/opt/rbenv/versions/2.2.4/bin/danger:23:in `load'
  /usr/local/opt/rbenv/versions/2.2.4/bin/danger:23:in `<top (required)>'
```

I've set my `DANGER_GITHUB_API_TOKEN` and I have a couple of opened pull request: https://github.com/Palleas/romain-pouclet.com/pulls. 
Am I in a weird glitch or am I doing something wrong? 😁

**Comment by orta** [comment]
You might be using squash commits, it looks for a specific format of commits that GH make on merges

**Comment by Palleas** [comment]
I don't think I am... It happens that I merge branches without opening a pull request though, could that be the issue? If I understand correctly, `danger local` looks for closed PR to run against?

**Comment by orta** [comment]
Yeah, it looks for commits that GitHub itself makes when you merge a PR, this should be more obvious with #518 when there's no attempts to guess the latest PR, you'd have to provide the link

**Comment by Palleas** [comment]
Oh cool, thanks!

**Comment by JuanitoFatas** [comment]
`danger local` now pick the most recent PR if you don't specify.
