### ISSUE TITLE
Crashes at Step 4 of Easy Install

### ISSUE THREAD

**Issue by forrestfiller** [danger/danger#389]
Crash looks like this:
```
/usr/local/lib/ruby/gems/2.3.0/gems/danger-2.0.1/lib/danger/commands/init.rb:173:in `uses_travis': undefined method `[]' for false:FalseClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.0.1/lib/danger/commands/init.rb:146:in `setup_danger_ci'
	from /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.0.1/lib/danger/commands/init.rb:37:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/danger-2.0.1/bin/danger:5:in `<top (required)>'
	from /usr/local/bin/danger:23:in `load'
	from /usr/local/bin/danger:23:in `<main>'

**Comment by forrestfiller** [comment]
![ortasfixstep4](https://cloud.githubusercontent.com/assets/18606441/17279551/aee397ac-5744-11e6-8f63-8bbc070a91be.gif)
:+1: :+1: :+1: :+1: 
Works Great!

**Comment by orta** [comment]
rock
