### ISSUE TITLE
Undefined local variable or method `modified_files'

### ISSUE THREAD

**Issue by pepibumur** [danger/danger#421]
I'm trying to run Danger but I get the following error when I try to run the command:

> It happens when executed locally and on CI.

#### Error
```
bundler: failed to load command: danger (/usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bin/danger)
Danger::DSLError:
[!] Invalid `temporary_danger.rb` file: undefined local variable or method `modified_files' for #<Danger::Dangerfile:0x007fbc28864840>. Updating the Danger gem might fix the issue.

 #  from /var/folders/gh/0gdypwb52wqck30b67x95_7r0000gp/T/d20160812-40878-12nh46p/temporary_danger.rb:4
 #  -------------------------------------------
 #
 >  has_app_changes = !modified_files.grep(/lib/).empty?
 #  has_test_changes = !modified_files.grep(/spec/).empty?
 #  -------------------------------------------
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/danger_core/dangerfile.rb:65:in `method_missing'
  /var/folders/gh/0gdypwb52wqck30b67x95_7r0000gp/T/d20160812-40878-12nh46p/temporary_danger.rb:4:in `block in parse'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/danger_core/dangerfile.rb:193:in `eval'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/danger_core/dangerfile.rb:193:in `block in parse'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/danger_core/dangerfile.rb:189:in `instance_eval'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/danger_core/dangerfile.rb:189:in `parse'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/commands/local.rb:123:in `check_and_run_org_dangerfile'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/lib/danger/commands/local.rb:110:in `run'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bundler/gems/CLAide-61071679fc96/lib/claide/command.rb:334:in `run'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/danger-2.1.2/bin/danger:5:in `<top (required)>'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bin/danger:23:in `load'
  /usr/local/var/rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/bin/danger:23:in `<top (required)>'
```

#### Dangerfile

```ruby
warn("PR is classed as Work in Progress")
```

Thanks in advance.

**Comment by orta** [comment]
Looks like this hasn't migrated to 2.0 syntax -> https://github.com/danger/danger/blob/master/CHANGELOG.md#200

👍
