### ISSUE TITLE
Danger init crashes during setup

### ISSUE THREAD

**Issue by mtitolo** [danger/danger#441]
I'm troubleshooting my setup and figured I'd use the built in `init` command to see if I missed anything. It crashed. Happy to provide whatever info is relevant to help fix it.

Output:
```
Step 2: Creating a GitHub account

In order to get the most out of Danger, I'd recommend giving her the ability to post in
the code-review comment section.

IMO, it's best to do this by using the private mode of your browser. Create an account like
MyRepoBot, and don't forget a cool robot avatar.

Here are great resources for creative commons images of robots:
 -> https://www.flickr.com/search/?text=robot&license=2%2C3%2C4%2C5%2C6%2C9
 -> https://www.google.com/search?q=robot&tbs=sur:fmc&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjgy8-f95jLAhWI7hoKHV_UD00QsAQIMQ&biw=1265&bih=1359
/Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/lib/danger/commands/init_helpers/interviewer.rb:40:in `sleep': can't convert String into time interval (TypeError)
	from /Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/lib/danger/commands/init_helpers/interviewer.rb:40:in `pause'
	from /Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/lib/danger/commands/init.rb:93:in `setup_github_account'
	from /Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/lib/danger/commands/init.rb:35:in `run'
	from /Users/michele/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /Users/michele/.rvm/gems/ruby-2.3.0/gems/danger-2.1.5/bin/danger:5:in `<top (required)>'
	from /Users/michele/.rvm/gems/ruby-2.3.0/bin/danger:23:in `load'
	from /Users/michele/.rvm/gems/ruby-2.3.0/bin/danger:23:in `<main>'
	from /Users/michele/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michele/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by marcelofabri** [comment]
@mtitolo Could you check if #442 fix the issue for you? (And that there are no other crashes in `init` 😬 )
