### ISSUE TITLE
Some references to GitHub exclusivity still lingering

### ISSUE THREAD

**Issue by connorshea** [danger/danger#458]
There are a few places where GitHub is implied to be the only supported platform so I wanted to note them in an issue to see if I'm misunderstanding and to get them fixed otherwise.

- [`xcode_server.rb`](https://github.com/danger/danger/blob/master/lib/danger/ci_source/xcode_server.rb) includes GitHub as the only supported request source.
- [`init.rb`](https://github.com/danger/danger/blob/master/lib/danger/commands/init.rb#L48) tells the user a GitHub account is necessary.

And on the flipside, [`github_helper.rb`](https://github.com/danger/danger/blob/master/spec/support/github_helper.rb) seems to include a bunch of GitLab references/terminology (e.g. merge requests vs. pull requests).

**Comment by orta** [comment]
In the case of Xcode server, I'm afraid it only supports [Github & BitBucket](https://github.com/czechboy0/Buildasaur#hammer-requirements)

For `danger init`- yeah, that definitely needs a run through, it can probably figure out whether you're on GH/GL based on the remotes and offer better docs. 

WRT the github_helper I'd guess they overwrite each other ATM, and are redundant :)

**Comment by k0nserv** [comment]
I might have copied and pasted a bit for the github_helper so that seems reasonable

**Comment by connorshea** [comment]
@orta that'll work for gitlab.com and github.com, but not self-hosted GitLab or GitHub Enterprise. If it's not obvious what the platform is, I guess the user should be asked to choose from a selection of options.

**Comment by orta** [comment]
Options: booooooo

But, I think that might make sense for the self-hosted/ enterprises. 👍

**Comment by jk** [comment]
I just want to mention another place: I'm doing my first steps with Danger and GitLab+Jenkins right now. I'm just through the `bundle init+install` and `bundle exec danger init` process. When I test it via `bundle exec danger local` without setting any environment variables I get:

```
Danger local requires a repository hosted on GitHub.com or GitHub Enterprise.
/usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/danger-3.0.1/lib/danger/ci_source/local_git_repo.rb:52:in `initialize': No recent pull requests found for this repo, danger requires at least one PR for the local mode. (RuntimeError)
       	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/danger-3.0.1/lib/danger/danger_core/environment_manager.rb:20:in `new'
       	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/danger-3.0.1/lib/danger/danger_core/environment_manager.rb:20:in `initialize'
       	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/danger-3.0.1/lib/danger/commands/local.rb:70:in `new'
       	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/danger-3.0.1/lib/danger/commands/local.rb:70:in `run'
       	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
       	from /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/danger-3.0.1/bin/danger:5:in `<top (required)>'
       	from /usr/local/var/rbenv/versions/2.2.2/bin/danger:23:in `load'
       	from /usr/local/var/rbenv/versions/2.2.2/bin/danger:23:in `<main>'
```

So this is another place where it exclusively mentions GitHub.

**Comment by orta** [comment]
Aye, the scope for local changes are pretty vast #382 - so I wouldn't expect to see those too soon I'm afraid

**Comment by connorshea** [comment]
@orta I'm not a huge fan of options either, I suppose you could also parse the URL and look for `github`/`gitlab`, e.g. `gitlab.colostate.edu` would suggest GitLab. If that doesn't work either it should make the user choose. Should be possible to override as well.

**Comment by connorshea** [comment]
@orta would it be reasonable to have issue labels for issues specific to certain SCM providers, e.g. GitHub, GitLab, Bitbucket?

**Comment by orta** [comment]
Yep, for sure
