### ISSUE TITLE
Danger breaks on non-english locale systems (Jenkins)

### ISSUE THREAD

**Issue by jk** [danger/danger#476]
### Problem
Danger breaks in https://github.com/danger/danger/blob/master/lib/danger/scm_source/git_repo.rb#L26 if the Jenkins job isn't running with an english locale set in `LANG` OR `LC_ALL` since it's expecting git responds in english and matches `Fetch URL`.

```bash
bundler: failed to load command: danger (/var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/bin/danger)
NoMethodError: undefined method `split' for nil:NilClass
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/scm_source/git_repo.rb:26:in `origins'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/request_source/request_source.rb:23:in `validates_as_ci?'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/danger_core/environment_manager.rb:26:in `block in initialize'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/2.2.0/set.rb:283:in `each_key'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/2.2.0/set.rb:283:in `each'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/danger_core/environment_manager.rb:22:in `initialize'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/danger_core/executor.rb:26:in `new'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/danger_core/executor.rb:26:in `run'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/lib/danger/commands/runner.rb:56:in `run'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/gems/danger-3.0.1/bin/danger:5:in `<top (required)>'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/bin/danger:23:in `load'
  /var/lib/jenkins/jobs/playground-danger-php-test/workspace/vendor/bundle/ruby/2.2.0/bin/danger:23:in `<top (required)>'
```

### Workaround
Set your `LANG` before you call danger:
```bash
export LANG=en_US
```

This will run git with an english command line interface.

### Better solution?
I'm no expert in Ruby and its gem ecosystem, but is there an option you can set on the `Git` class to set its locale to english? That would have prevented that bug.

**Comment by orta** [comment]
In theory, [this command](https://github.com/danger/danger/blob/master/lib/danger/scm_source/git_repo.rb#L17) can have that environment var set before executing the git command?

**Comment by jk** [comment]
Could work:

```ruby
    def exec(string)
      `LANG=en_US git #{string}`.strip
    end
```

**Comment by orta** [comment]
Aye

**Comment by k0nserv** [comment]
Is this resolved no that #485 is merged?
