### ISSUE TITLE
Danger failures when CI uses shallow clone, error msg unclear

### ISSUE THREAD

**Issue by jverdi** [danger/danger#535]
# Report

## What did you do?
Setup Danger with Jenkins / Github Enterprise, where Jenkins was configured to do a shallow clone of a large repo.

## What did you expect to happen?
Nothing in docs led me to believe that Danger would have issues when working with shallow clones, but if it's insurmountable, perhaps this could be addressed w/a more useful error message.

## What happened instead?
I received the following error/stacktrace from Danger:
```
Git::GitExecuteError: git '--git-dir=/Users/myuser/.jenkins/workspace/MyProject/.git' '--work-tree=/Users/myuser/.jenkins/workspace/MyProject' cat-file '-t' ''  2>&1:fatal: Not a valid object name

/Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/lib.rb:166:in `object_type'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/git-1.3.0/lib/git/object.rb:301:in `new'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.2.1/lib/danger/scm_source/git_repo.rb:61:in `merge_base'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.2.1/lib/danger/scm_source/git_repo.rb:15:in `diff_for_folder'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.2.1/lib/danger/danger_core/executor.rb:43:in `run'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.2.1/lib/danger/commands/runner.rb:56:in `run'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /Users/myuser/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-3.2.1/bin/danger:5:in `<top (required)>'
  /Users/myuser/.rbenv/versions/2.3.1/bin/danger:22:in `load'
  /Users/myuser/.rbenv/versions/2.3.1/bin/danger:22:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? Jenkins
* Are you running the latest version of Danger? Yes, Danger 3.2.1

**Comment by orta** [comment]
What version of git is running on the machine? I'm not really sure what the error is telling us

**Comment by orta** [comment]
Had a think about this, CircleCI always uses a shallow clone ( with a depth of 50 ) so I'm pretty sure this is not a shallow clone issue

**Comment by JuanitoFatas** [comment]
[The error looks like we need to `git init` first](http://stackoverflow.com/a/9162347/517868).

**Comment by orta** [comment]
I feel like this got fixed, any chance you can try again on 4.0?
