### ISSUE TITLE
kramdown crashes when warn() or message() inside loop.

### ISSUE THREAD

**Issue by masters3d** [danger/danger#540]
# Report

## What did you do?
https://travis-ci.org/exercism/xswift/builds/159039332
I am trying to display warnings from swift lint. 
```ruby
json.each do |object|
   shortFile =  object["file"]
   shortFile ["/Users/travis/build/exercism/xswift/"] = "/"
   warn(message: object["reason"], file: shortFile, line: object["line"])
end
```

https://github.com/exercism/xswift/pull/191
I moved danger to after success so other PR's don't fail for now.  

## What did you expect to happen?

I expected no errors. 

## What happened instead?

```Ruby
/Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/kramdown-1.12.0/lib/kramdown/parser/base.rb:98:in `adapt_source': undefined method `gsub' for #<Hash:0x007fec9a6c0d20> (NoMethodError)
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/kramdown-1.12.0/lib/kramdown/parser/kramdown.rb:89:in `parse'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/kramdown-1.12.0/lib/kramdown/parser/gfm.rb:41:in `parse'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/kramdown-1.12.0/lib/kramdown/parser/base.rb:69:in `parse'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/kramdown-1.12.0/lib/kramdown/document.rb:107:in `initialize'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:14:in `new'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:14:in `markdown_parser'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:51:in `process_markdown'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:74:in `block in table'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:74:in `map'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:74:in `table'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/helpers/comments_helper.rb:112:in `generate_comment'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/request_source/github.rb:133:in `update_pull_request!'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/danger_core/executor.rb:60:in `post_results'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/danger_core/executor.rb:48:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/lib/danger/commands/runner.rb:56:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/danger-3.2.1/bin/danger:5:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/danger:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/danger:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'
```
## Your Environment

* Which CI are you running on?
Travis
* Are you running the latest version of Danger?
3.2.1

**Comment by marcelofabri** [comment]
From the error message, it seems that one of your variables is a Hash and not a String as expected. Could you try printing them?

**Comment by masters3d** [comment]
They print.
```
Limit vertical whitespace to a single empty line  Currently 2
/exercises/accumulate/AccumulateTest.swift
37
```
I changed something. 
Is there a different between 
warn(message: "", file:"", line:1 )
warn( "", file:"", line:1 )

**Comment by masters3d** [comment]
I think the issue is the first argument label that I added is somehow being passed down as an object (perhaps the message() function? ) so when when a string method is call on this object then it cant be found. 

Anyway, the issue is revolved by just removing the extraneous `message` argument label.

**Comment by orta** [comment]
It could be worth adding an extra `to_s` at the start of these functions on the arg passed in so that we don't crash like this unexpectedly?

**Comment by masters3d** [comment]
Another way that it crashes similarly is if the string variable is named the same as the `message` function.

```ruby
...
message = "myString"
message(message, file:"someFile", line:1) 
```

**Comment by orta** [comment]
that's just ruby, you're overriding the existing method in that local scope

**Comment by masters3d** [comment]
Got it :) Thanks for introducing me to Ruby with Danger.
