### ISSUE TITLE
html_link does not work on GitLab

### ISSUE THREAD

**Issue by jk** [danger/danger#543]
# Report

## What did you do?
I tried some of the rules state on http://danger.systems.

## What did you expect to happen?
I expected that Danger creates markdown which links back to the given file in the MR comments.

## What happened instead?
Jenkins build failed when running `bundle exec danger`. Danger fails with the following error message:

```
bundle exec danger
bundler: failed to load command: danger (/var/lib/jenkins/.rbenv/versions/2.2.0/bin/danger)
Danger::DSLError: [31m
[!] Invalid `Dangerfile` file: undefined method `ci_source' for #<Danger::Dangerfile:0x007f7c7cc3e740>[0m
 #  from Dangerfile:4
 #  -------------------------------------------
 #  
 >  message("This file #{ gitlab.html_link('CHANGELOG.md') } ")
 #  
 #  -------------------------------------------

  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:67:in `method_missing'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/plugin_support/plugin.rb:23:in `method_missing'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb:196:in `html_link'
  Dangerfile:4:in `block in parse'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:194:in `eval'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:194:in `block in parse'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:190:in `instance_eval'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:190:in `parse'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/danger_core/executor.rb:46:in `run'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/lib/danger/commands/runner.rb:56:in `run'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /var/lib/jenkins/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/danger-3.2.1/bin/danger:5:in `<top (required)>'
  /var/lib/jenkins/.rbenv/versions/2.2.0/bin/danger:23:in `load'
  /var/lib/jenkins/.rbenv/versions/2.2.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? Jenkins 2.10
* Are you running the latest version of Danger? Yes

**Comment by orta** [comment]
I think we need to prefix it with `env` in the method - surprised tests didn't cover this
