### ISSUE TITLE
Danger breaks when files are moved

### ISSUE THREAD

**Issue by jpsim** [danger/danger#553]
# Report

## What did you do?

I moved a file: https://github.com/SwiftWeekly/swiftweekly.github.io/pull/89/commits/f51ce4759205e31699f59ba6aebfcc2249f88016

https://github.com/SwiftWeekly/swiftweekly.github.io/pull/89

## What did you expect to happen?

I expected Danger to not attempt to lint the file at its previous location, but rather lint it at its new location.

## What happened instead?

💥. Danger tried to lint the file at its old location, causing the following failure:

```
/home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-prose-2.0.3/lib/danger_plugin.rb:63:in `block (2 levels) in lint_files':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: undefined method `[]' for nil:NilClass. Updating the Danger gem might fix the issue. Your Danger version: 3.2.1, latest Danger version: 3.2.2
 #  from Dangerfile:2
 #  -------------------------------------------
 #  # Look for prose issues
 >  prose.lint_files
 #  
 #  -------------------------------------------
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-prose-2.0.3/lib/danger_plugin.rb:63:in `select'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-prose-2.0.3/lib/danger_plugin.rb:63:in `block in lint_files'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-prose-2.0.3/lib/danger_plugin.rb:179:in `with_proselint_disabled'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-prose-2.0.3/lib/danger_plugin.rb:60:in `lint_files'
	from Dangerfile:2:in `block in parse'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:194:in `eval'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:194:in `block in parse'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:190:in `instance_eval'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/lib/danger/danger_core/dangerfile.rb:190:in `parse'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/lib/danger/danger_core/executor.rb:46:in `run'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/lib/danger/commands/runner.rb:56:in `run'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/gems/danger-3.2.1/bin/danger:5:in `<top (required)>'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/bin/danger:23:in `load'
	from /home/travis/build/SwiftWeekly/swiftweekly.github.io/vendor/bundle/ruby/2.1.0/bin/danger:23:in `<main>'
```

## Your Environment

* Which CI are you running on?

Travis, though I don't think that's related. Here's the failing build: https://travis-ci.org/SwiftWeekly/swiftweekly.github.io/builds/160181293

* Are you running the latest version of Danger?

Running 3.2.1, but looking at the diff between that and `master`, nothing that's landed since would have fixed this.

**Comment by JuanitoFatas** [comment]
[Log](https://travis-ci.org/SwiftWeekly/swiftweekly.github.io/builds/160181293#L265-L302) looks like a bug in https://github.com/dbgrandi/danger-prose.

**Comment by JuanitoFatas** [comment]
Need to figure out how to remove the deleted file from [here](https://github.com/dbgrandi/danger-prose/blob/master/lib/danger_plugin.rb#L187).

**Comment by orta** [comment]
> The root cause is that there is no diff (`@git.diff` is `nil`), so these methods are failing:

nice find, that's really interesting!

**Comment by orta** [comment]
Should be easy to write a test for at least

**Comment by JuanitoFatas** [comment]
More cases: https://travis-ci.org/danger/danger/builds/160615933 from #558.

**Comment by orta** [comment]
A test case I've been working with:

```
        it "handles moving a file correctly" do
          run_in_repo_with_diff do |git|
            `mv file1 file2`
            `git add .`
            `git checkout -b new-branch-2 --quiet`
            `git commit -m "moved file"`

            # now check the changes for the moved file
            diff = git.diff("new-branch")
            stats = diff.stats
            # allow(@repo).to receive(:diff).and_return(diff)
            
            require 'pry'
            binding.pry

            expect(@dsl.modified_files).to eq([])
          end
```

This is tricky, because it is literally git which gives us the "bad" details, I wonder if we need to do a pre-parse of the stats dictionary to ensure that all files exist, and if they don't to chuck them in removed files

<img width="968" alt="screen shot 2016-09-17 at 15 24 38" src="https://cloud.githubusercontent.com/assets/49038/18610458/e20fdbba-7cea-11e6-8101-d536a15f187f.png">

**Comment by JuanitoFatas** [comment]
Our code actually works:

```ruby
context "SwiftWeekly/swiftweekly.github.io #89" do
  def reproduce_pull_request_89(dir, spec_root)
    Dir.chdir dir do
      # create SwiftWeekly/swiftweekly.github.io master
      `git init`
      `echo "swiftweekly.github.io" > README.md`
      `mkdir _drafts _posts`
      `git add .`
      `git commit -m "Init master"`

      # Create 2016-09-15-issue-38.md
      `git checkout -b jp-issue-38 --quiet`
      IO.write("_drafts/2016-09-15-issue-38.md", "init 2016-09-15-issue-38.md")
      `git add _drafts/2016-09-15-issue-38.md`
      `git commit -m "flesh out issue 38 based on suggestions from #75, #79"`

      # Update 2016-09-15-issue-38.md
      IO.write("_drafts/2016-09-15-issue-38.md", "update 2016-09-15-issue-38.md")
      `git add _drafts/2016-09-15-issue-38.md`
      `git commit -m "address first round of review feedback"`

      # Move 2016-09-15-issue-38.md from _drafts/ to _posts/
      `git mv _drafts/2016-09-15-issue-38.md _posts/2016-09-15-issue-38.md`
      `git add .`
      `git commit -m "move issue 38 to _posts"`
    end
  end

  it "handles moved file correctly" do
    require "danger/core_ext/file_list"
    require "danger/scm_source/git_repo"

    spec_root = Dir.pwd

    Dir.mktmpdir do |dir|
      Dir.chdir dir do
        reproduce_pull_request_89(dir, spec_root)

        git = Danger::GitRepo.new
        git.diff_for_folder(".", from: "master", to: "jp-issue-38")

        added_files = Danger::FileList.new(git.diff.select { |diff| diff.type == "new" }.map(&:path))

        expect(added_files).to eq ["_posts/2016-09-15-issue-38.md"]
      end
    end
  end
end
```

I think we missed to do `git.diff_for_folder(".", from: "master", to: "jp-issue-38")` somewhere.
