### ISSUE TITLE
Danger breaks on travis-ci/pr

### ISSUE THREAD

**Issue by JuanitoFatas** [danger/danger#562]
# Report

## What did you do?

https://travis-ci.org/danger/danger/jobs/160680411

See #561 & #560, only travis-ci/pr failed, travis-ci/push works.

## What did you expect to happen?

danger runs without error

## What happened instead?

```
$ bundle exec danger --verbose
bundler: failed to load command: danger (/home/travis/build/danger/danger/bundle/ruby/2.3.0/bin/danger)
RuntimeError: Could not find a Request Source for Danger::Travis
  /home/travis/build/danger/danger/lib/danger/danger_core/environment_manager.rb:31:in `initialize'
  /home/travis/build/danger/danger/lib/danger/danger_core/executor.rb:30:in `new'
  /home/travis/build/danger/danger/lib/danger/danger_core/executor.rb:30:in `run'
  /home/travis/build/danger/danger/lib/danger/commands/runner.rb:56:in `run'
  /home/travis/build/danger/danger/bundle/ruby/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /home/travis/build/danger/danger/bin/danger:5:in `<top (required)>'
  /home/travis/build/danger/danger/bundle/ruby/2.3.0/bin/danger:23:in `load'
  /home/travis/build/danger/danger/bundle/ruby/2.3.0/bin/danger:23:in `<top (required)>'
The command "bundle exec danger --verbose" exited with 1.
```

## Your Environment

* Which CI are you running on? => Travis 👷 
* Are you running the latest version of Danger? Yup

**Comment by JuanitoFatas** [comment]
I think this bug introduced by #558.

**Comment by orta** [comment]
Yeah, that does look like it - I wonder if there was some code auto-loading al request sources at the old path?

**Comment by JuanitoFatas** [comment]
Fixed in https://github.com/danger/danger/pull/564.
