### ISSUE TITLE
Danger crashes when running on PR between feature branches

### ISSUE THREAD

**Issue by darrarski** [danger/danger#660]
# Report

Danger crashes when running on PR between feature branches. It works like expected when PR is from feature-branch to master.

## What did you do?

Run Danger from CI on PR from one feature-branch to another (not to master branch).

## What did you expect to happen?

Not to crash.

## What happened instead?

Danger crashed with error:
```
fatal: --unshallow on a complete repository does not make sense
bundler: failed to load command: danger (/usr/local/bin/danger)
RuntimeError: Commit 98f1d936 doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed.
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/scm_source/git_repo.rb:58:in `raise_if_we_cannot_find_the_commit'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/scm_source/git_repo.rb:43:in `ensure_commitish_exists!'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/request_sources/github.rb:77:in `setup_danger_branches'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/danger_core/environment_manager.rb:57:in `ensure_danger_branches_are_setup'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/danger_core/dangerfile.rb:258:in `setup_for_running'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/danger_core/dangerfile.rb:269:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/danger_core/executor.rb:27:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/lib/danger/commands/runner.rb:66:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/danger-4.0.0/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:23:in `load'
  /usr/local/bin/danger:23:in `<top (required)>'
```
## Your Environment

* Bitrise CI
* macOS 10.12 Sierra
* Ruby 2.3.1p112
* Danger 4.0.0
* Dangerfile:
  ```ruby
  # Make it more obvious that a PR is a work in progress and shouldn't be merged yet
  warn("PR is classed as Work in Progress", sticky: true) if github.pr_title.include? "[WIP]"

  # Warn when there is a big PR
  warn("Big PR", sticky: true) if git.lines_of_code > 500

  # Only accept prs to the master branch
  fail "Please re-submit this PR to master, we may have already fixed your issue." if github.branch_for_base != "master"

  # Ensure that all prs have and assignee
  warn "This PR does not have any assignees yet." unless github.pr_json["assignee"]

  # Don't let testing shortcuts get into master by accident
  test_directory = "MyAppTests"

  fail("fit left in tests", sticky: true) if `grep -rI "fit(" #{test_directory}/`.length > 1
  fail("fdescribe left in tests", sticky: true) if `grep -r fdescribe #{test_directory}/`.length > 1
  fail("fcontext left in tests", sticky: true) if `grep -r fcontext #{test_directory}/`.length > 1

  fail("xit left in tests", sticky: true) if `grep -rI "xit(" #{test_directory}/`.length > 1
  fail("xdescribe left in tests", sticky: true) if `grep -r xdescribe #{test_directory}/`.length > 1
  fail("xcontext left in tests", sticky: true) if `grep -r xcontext #{test_directory}/`.length > 1

  # Stop skipping some manual testing
  warn("Needs testing on a Phone if change is non-trivial", sticky: true) if git.lines_of_code > 50 && !github.pr_title.include?("📱")

  # Run SwiftLint
  swiftlint.directory = 'MyApp'
  swiftlint.lint_files
  swiftlint.directory = 'MyAppTests'
  swiftlint.lint_files
  ```

**Comment by orta** [comment]
Got any clues? 

Off-hand I'm not really sure, the commits Danger is looking for doesn't seem to be there, could it be specific to Bitrise?

**Comment by darrarski** [comment]
It could be Bitrise issue. From my observations, Danger crashes on each PR from feature branch to another feature branch, but the same crash happened once on PR from feature branch to master. More than 50  builds on PR from feature branch to master passed without Danger crashing in the meantime.

It's hard for me to give more details right now. @orta if you have some hints what could be helpful in solving the issue, like logs etc - let me know, but I am not sure if I will be able to get those from Bitrise.

**Comment by orta** [comment]
@darrarski - want to give #662 a shot, this might fix it 👯‍♂️

**Comment by mokagio** [comment]
Great to find this PR! We've been bumping into this error on and off a number of times. We'll run with #662 for a week or so and report 👍 .

**Comment by mattdelves** [comment]
Any update on this? We're still running into the issue after doing a rebase and force push. (I work on the same app as Gio).

**Comment by orta** [comment]
Would recommend looking at the PR changes in #662 and seeing what could be still causing problems, we don't have a reproducible case to be able to test it on I'm afraid

**Comment by mokagio** [comment]
@orta @JuanitoFatas @darrarski the @iflix-letsplay iOS team has been rolling with the version from #622 for the past 25 days (see my comment above), and haven't seen the `fatal: --unshallow on a complete repository does not make sense` ever since. 👍

**Comment by mokagio** [comment]
Scratch that 😩. My team mate @mattdelves pointed out that he did see an `---unshallow` failure, which didn't make sense to me because the version of Danger in #662 does not make an unshallow clone.

Well... Turns out I don't know how to Ruby Gem, and that to actually fetch the PR branch I had to do this:

```diff
-gem 'danger', branch: 'jf/deep-fetch'
+gem 'danger', git: 'git@github.com:danger/danger.git', branch: 'jf/deep-fetch'
```

🤦‍♂️ 

Back to square one. We'll report back in a few weeks.

**Comment by mokagio** [comment]
Hi, just an update on this. We've been using the changes in https://github.com/danger/danger/pull/662, _for real this time_, for the last two months and haven't had any issues and with more team members doing frequent rebases on PR branches.

😄 .

**Comment by orta** [comment]
hah, nice, OK, rebased it and if it greens it can be merged
