### ISSUE TITLE
"undefined method `name' for nil:NilClass" when running "danger plugins"

### ISSUE THREAD

**Issue by barbosa** [danger/danger#688]
danger.systems's [build](https://gitlab.com/danger-systems/danger.systems/builds/7637957) is breaking due to an error on `danger plugins` command. It executes `bundle exec rake generate`, which internally calls `bundle exec danger plugins json <plugin-name>` for each external plugin.

Investigating a little bit, I was able to find that [this return statement](https://github.com/danger/danger/blob/master/lib/danger/plugin_support/gems_resolver.rb#L19) is being called outside of the `Dir.chdir(dir)` block, which makes `paths` and `gems` methods run out of the temp dir scope. The solution could be either call `Dir.chdir(dir)` on both methods or pass the temporary dir as an argument.

# Report

## What did you do?

Run `bundle exec danger plugins json danger-prose`

## What did you expect to happen?

Output correct plugin metadata

## What happened instead?

```
bundler: failed to load command: danger (/Users/gustavo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bin/danger)
NoMethodError: undefined method `name' for nil:NilClass
  /Users/gustavo/Developer/danger/lib/danger/plugin_support/gems_resolver.rb:60:in `gem_metadata'
  /Users/gustavo/Developer/danger/lib/danger/plugin_support/gems_resolver.rb:47:in `block in gems'
  /Users/gustavo/Developer/danger/lib/danger/plugin_support/gems_resolver.rb:47:in `map'
  /Users/gustavo/Developer/danger/lib/danger/plugin_support/gems_resolver.rb:47:in `gems'
  /Users/gustavo/Developer/danger/lib/danger/plugin_support/gems_resolver.rb:19:in `call'
  /Users/gustavo/Developer/danger/lib/danger/plugin_support/plugin_file_resolver.rb:18:in `resolve'
  /Users/gustavo/Developer/danger/lib/danger/commands/plugins/plugin_json.rb:30:in `run'
  /Users/gustavo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /Users/gustavo/Developer/danger/bin/danger:5:in `<top (required)>'
  /Users/gustavo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bin/danger:23:in `load'
  /Users/gustavo/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? Local environment
* Are you running the latest version of Danger? Yes (4.0.3)
* What is your Dangerfile? N/A

**Comment by barbosa** [comment]
My pleasure!
