### ISSUE TITLE
Better handling of long comments

### ISSUE THREAD

**Issue by marcelofabri** [danger/danger#698]
# Report

## What did you do?

Run `danger` and it generated lots of violations. See https://circleci.com/gh/realm/SwiftLint/114

## What did you expect to happen?

Danger handled long comments by creating a gist and posted the link in the comments. Bonus if it showed some violations and then trimmed with the link in the end.

## What happened instead?

```
Octokit::UnprocessableEntity: PATCH https://api.github.com/repos/realm/SwiftLint/issues/comments/269234658: 422 - Validation Failed
Error summary:
  resource: IssueComment
  code: custom
  field: body
  message: body is too long (maximum is 65536 characters) // See: https://developer.github.com/v3/issues/comments/#edit-a-comment
```

## Your Environment

* Which CI are you running on? Circle
* Are you running the latest version of Danger? No, 4.0.3 (but according to CHANGELOG nothing changed in this area)
* What is your Dangerfile? https://github.com/realm/SwiftLint/blob/master/Dangerfile

**Comment by suchow** [comment]
Another possibilitiy might be partitioning the response into the smallest number of comments that's under the message-length limit?

**Comment by orta** [comment]
I thought we handled this ( https://github.com/danger/danger/blob/master/spec/lib/danger/helpers/comments_helper_spec.rb#L394 )

I do like the idea of a gist though, that'd be better than the current implementation 👍

**Comment by marcelofabri** [comment]
Can we keep this open to track an even better solution? 😅

**Comment by nderkach** [comment]
This seems to still be an issue with Danger 6.0.9

**Comment by esgrano** [comment]
Hi, any updated on this?
Got the same issue today:
```
Traceback (most recent call last):
	25: from /usr/local/bundle/bin/danger:23:in `<main>'
	24: from /usr/local/bundle/bin/danger:23:in `load'
	23: from /usr/local/bundle/gems/danger-8.2.3/bin/danger:5:in `<top (required)>'
	22: from /usr/local/bundle/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	21: from /usr/local/bundle/gems/danger-8.2.3/lib/danger/commands/runner.rb:73:in `run'
	20: from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/executor.rb:29:in `run'
	19: from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/dangerfile.rb:292:in `run'
	18: from /usr/local/bundle/gems/danger-8.2.3/lib/danger/danger_core/dangerfile.rb:264:in `post_results'
	17: from /usr/local/bundle/gems/danger-8.2.3/lib/danger/request_sources/github/github.rb:200:in `update_pull_request!'
	16: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/client/issues.rb:284:in `add_comment'
	15: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/connection.rb:28:in `post'
	14: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
	13: from /usr/local/bundle/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
	12: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/connection.rb:279:in `post'
	11: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/connection.rb:492:in `run_request'
	10: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/rack_builder.rb:154:in `build_response'
	 9: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/request/retry.rb:148:in `call'
	 8: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	 7: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:75:in `perform_with_redirection'
	 6: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/response.rb:59:in `on_complete'
	 5: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:79:in `block in perform_with_redirection'
	 4: from /usr/local/bundle/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	 3: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/middleware.rb:18:in `call'
	 2: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/response.rb:59:in `on_complete'
	 1: from /usr/local/bundle/gems/faraday-1.4.1/lib/faraday/middleware.rb:19:in `block in call'
/usr/local/bundle/gems/octokit-4.20.0/lib/octokit/response/raise_error.rb:14:in `on_complete': POST https://api.github.com/repositories/83337682/issues/7116/comments: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: IssueComment
  code: unprocessable
  field: data
  message: Body is too long (maximum is 65536 characters) // See: https://docs.github.com/rest/reference/issues#create-an-issue-comment
```

**Comment by orta** [comment]
No update, you're welcome to look at it
