### ISSUE TITLE
Travis CI - bundler: failed to load command: danger

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [danger/danger#718]
@danger

----

# Report
> * My pull request: https://github.com/bunto/bunto/pull/103
> * The Travis CI log: https://travis-ci.org/bunto/bunto/jobs/198288413

## What did you do?
Run `danger local`:
```powershell
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

Das Laden von persönlichen und Systemprofilen dauerte 3500 ms.
~\Documents\GitHub\bunto [danger ≡]> danger local
Running your Dangerfile against this PR - https://github.com/bunto/bunto/pull/102
Turning on --verbose

Info:

+------------------+----------------------------------------------------------------------------------+
|                                            Danger v4.2.1                                            |
|                                           DSL Attributes                                            |
+------------------+----------------------------------------------------------------------------------+
|    status_report |                                                                                  |
| violation_report |                                                                                  |
|              --- | ---                                                                              |
|     scm_provider | github                                                                           |
|      added_files | []                                                                               |
|    deleted_files | []                                                                               |
|   modified_files | .travis.yml                                                                      |
|    lines_of_code | 3                                                                                |
|        deletions | 0                                                                                |
|       insertions | 3                                                                                |
|          commits | bdbcadbff9a259432f2e85e4f219be5e67d427dd                                         |
|              api | Octokit::Client                                                                  |
|          pr_json | [Skipped JSON]                                                                   |
|          mr_json | [Skipped JSON]                                                                   |
|          pr_diff | [Skipped Diff]                                                                   |
|           review | #<Danger::RequestSources::GitHubSource::Review:0x00000004ae6588>                 |
|         pr_title | Add Slack notification                                                           |
|          pr_body | Add the Slack notification for Travis CI.                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | ---                                                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | ``` powershell                                                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> gem install travis |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: faraday_middleware-0.10.0.gem (100%)                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed faraday_middleware-0.10.0                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: backports-3.6.8.gem (100%)                                             |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed backports-3.6.8                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: connection_pool-2.2.0.gem (100%)                                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed connection_pool-2.2.0                                     |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: net-http-persistent-3.0.0.gem (100%)                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed net-http-persistent-3.0.0                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: net-http-pipeline-1.0.1.gem (100%)                                     |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed net-http-pipeline-1.0.1                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: gh-0.14.0.gem (100%)                                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed gh-0.14.0                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: ethon-0.9.1.gem (100%)                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed ethon-0.9.1                                               |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: typhoeus-0.8.0.gem (100%)                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed typhoeus-0.8.0                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: websocket-1.2.3.gem (100%)                                             |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed websocket-1.2.3                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: pusher-client-0.6.2.gem (100%)                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed pusher-client-0.6.2                                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: travis-1.8.2.gem (100%)                                                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed travis-1.8.2                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for faraday_middleware-0.10.0                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for faraday_middleware-0.10.0                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for backports-3.6.8                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for backports-3.6.8                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for connection_pool-2.2.0                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for connection_pool-2.2.0                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for net-http-persistent-3.0.0                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for net-http-persistent-3.0.0                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for net-http-pipeline-1.0.1                                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for net-http-pipeline-1.0.1                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for gh-0.14.0                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for gh-0.14.0                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for ethon-0.9.1                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for ethon-0.9.1                                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for typhoeus-0.8.0                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for typhoeus-0.8.0                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for websocket-1.2.3                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for websocket-1.2.3                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for pusher-client-0.6.2                                    |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for pusher-client-0.6.2                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for travis-1.8.2                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for travis-1.8.2                                     |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Done installing documentation for faraday_middleware, backports, connection_pool |
|                  | , net-http-persistent, net-http-pipeline, gh, ethon, typhoeus, websocket, pusher |
|                  | -client, travis after 54 seconds                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | 11 gems installed                                                                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> travis encrypt "bu |
|                  | nto:<secret integration token>" --add notifications.slack                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Detected repository as bunto/bunto, is this correct? |yes| yes                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> git status         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | On branch slack                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Your branch is up-to-date with 'origin/slack'.                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Changes not staged for commit:                                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | (use "git add <file>..." to update what will be committed)                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | (use "git checkout -- <file>..." to discard changes in working directory)        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | modified:   .travis.yml                                                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | no changes added to commit (use "git add" and/or "git commit -a")                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> git add *          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 ~]> git status         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | On branch slack                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Your branch is up-to-date with 'origin/slack'.                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Changes to be committed:                                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | (use "git reset HEAD <file>..." to unstage)                                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | modified:   .travis.yml                                                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 ~]> git commit -S -m " |
|                  | Add Slack notification"                                                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Sie benötigen eine Passphrase, um den geheimen Schlüssel zu entsperren.          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Benutzer: "suriyaa <isc.suriyaa@gmail.com>"                                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | 2048-Bit RSA Schlüssel, ID FDDD96B0, erzeugt 2016-04-08                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | [slack bdbcadb] Add Slack notification                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | 1 file changed, 3 insertions(+)                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ↑]> git push                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Counting objects: 3, done.                                                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Delta compression using up to 4 threads.                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Compressing objects: 100% (3/3), done.                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Writing objects: 100% (3/3), 882 bytes | 0 bytes/s, done.                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Total 3 (delta 2), reused 0 (delta 0)                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | remote: Resolving deltas: 100% (2/2), completed with 2 local objects.            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | To https://github.com/bunto/bunto.git                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | d96baa7..bdbcadb  slack -> slack                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡]>                               |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | ```                                                                              |
|        pr_author | SuriyaaKudoIsc                                                                   |
|        pr_labels | slack                                                                            |
|                  | travis                                                                           |
|  branch_for_base | master                                                                           |
|  branch_for_head | slack                                                                            |
|      base_commit | d96baa737549e75c91d8a4c86dd137d569e5fe3a                                         |
|      head_commit | bdbcadbff9a259432f2e85e4f219be5e67d427dd                                         |
|         mr_title | Add Slack notification                                                           |
|          mr_body | Add the Slack notification for Travis CI.                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | ---                                                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | ``` powershell                                                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> gem install travis |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: faraday_middleware-0.10.0.gem (100%)                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed faraday_middleware-0.10.0                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: backports-3.6.8.gem (100%)                                             |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed backports-3.6.8                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: connection_pool-2.2.0.gem (100%)                                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed connection_pool-2.2.0                                     |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: net-http-persistent-3.0.0.gem (100%)                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed net-http-persistent-3.0.0                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: net-http-pipeline-1.0.1.gem (100%)                                     |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed net-http-pipeline-1.0.1                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: gh-0.14.0.gem (100%)                                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed gh-0.14.0                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: ethon-0.9.1.gem (100%)                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed ethon-0.9.1                                               |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: typhoeus-0.8.0.gem (100%)                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed typhoeus-0.8.0                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: websocket-1.2.3.gem (100%)                                             |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed websocket-1.2.3                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: pusher-client-0.6.2.gem (100%)                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed pusher-client-0.6.2                                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Fetching: travis-1.8.2.gem (100%)                                                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Successfully installed travis-1.8.2                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for faraday_middleware-0.10.0                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for faraday_middleware-0.10.0                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for backports-3.6.8                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for backports-3.6.8                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for connection_pool-2.2.0                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for connection_pool-2.2.0                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for net-http-persistent-3.0.0                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for net-http-persistent-3.0.0                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for net-http-pipeline-1.0.1                                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for net-http-pipeline-1.0.1                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for gh-0.14.0                                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for gh-0.14.0                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for ethon-0.9.1                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for ethon-0.9.1                                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for typhoeus-0.8.0                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for typhoeus-0.8.0                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for websocket-1.2.3                                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for websocket-1.2.3                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for pusher-client-0.6.2                                    |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for pusher-client-0.6.2                              |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Parsing documentation for travis-1.8.2                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Installing ri documentation for travis-1.8.2                                     |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Done installing documentation for faraday_middleware, backports, connection_pool |
|                  | , net-http-persistent, net-http-pipeline, gh, ethon, typhoeus, websocket, pusher |
|                  | -client, travis after 54 seconds                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | 11 gems installed                                                                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> travis encrypt "bu |
|                  | nto:<secret integration token>" --add notifications.slack                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Detected repository as bunto/bunto, is this correct? |yes| yes                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> git status         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | On branch slack                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Your branch is up-to-date with 'origin/slack'.                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Changes not staged for commit:                                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | (use "git add <file>..." to update what will be committed)                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | (use "git checkout -- <file>..." to discard changes in working directory)        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | modified:   .travis.yml                                                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | no changes added to commit (use "git add" and/or "git commit -a")                |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 !]> git add *          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 ~]> git status         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | On branch slack                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Your branch is up-to-date with 'origin/slack'.                                   |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Changes to be committed:                                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | (use "git reset HEAD <file>..." to unstage)                                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | modified:   .travis.yml                                                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡ +0 ~1 -0 ~]> git commit -S -m " |
|                  | Add Slack notification"                                                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Sie benötigen eine Passphrase, um den geheimen Schlüssel zu entsperren.          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Benutzer: "suriyaa <isc.suriyaa@gmail.com>"                                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | 2048-Bit RSA Schlüssel, ID FDDD96B0, erzeugt 2016-04-08                          |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | [slack bdbcadb] Add Slack notification                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | 1 file changed, 3 insertions(+)                                                  |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ↑]> git push                      |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Counting objects: 3, done.                                                       |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Delta compression using up to 4 threads.                                         |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Compressing objects: 100% (3/3), done.                                           |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Writing objects: 100% (3/3), 882 bytes | 0 bytes/s, done.                        |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | Total 3 (delta 2), reused 0 (delta 0)                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | remote: Resolving deltas: 100% (2/2), completed with 2 local objects.            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | To https://github.com/bunto/bunto.git                                            |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | d96baa7..bdbcadb  slack -> slack                                                 |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | C:\Users\Suriyaa\Documents\GitHub\bunto [slack ≡]>                               |
|                  |                                                                                  |
|                  |                                                                                  |
|                  | ```                                                                              |
|        mr_author | SuriyaaKudoIsc                                                                   |
|        mr_labels | slack                                                                            |
|                  | travis                                                                           |
|              --- | ---                                                                              |
|              SCM | Danger::GitRepo                                                                  |
|           Source | Danger::LocalGitRepo                                                             |
|         Requests | Danger::RequestSources::GitHub                                                   |
|      Base Commit | commit d96baa737549e75c91d8a4c86dd137d569e5fe3a                                  |
|                  | Author: suriyaa <isc.suriyaa@gmail.com>                                          |
|                  | Date:   Mon Aug 29 16:06:21 2016 +0200                                           |
|                  |                                                                                  |
|                  |     Fix 'Could not find gem bunto-sass-converter (>= 3.0) ruby' error            |
|                  |                                                                                  |
|                  |     Fixes issue #101.                                                            |
|      Head Commit | commit bdbcadbff9a259432f2e85e4f219be5e67d427dd                                  |
|                  | Author: suriyaa <isc.suriyaa@gmail.com>                                          |
|                  | Date:   Sun Oct 30 13:24:45 2016 +0100                                           |
|                  |                                                                                  |
|                  |     Add Slack notification                                                       |
+------------------+----------------------------------------------------------------------------------+
Warnings:
- [ ] Before submitting a Pull Request, please create an issue on GitHub to discuss the change. Please add a link to the issue in the PR body.
~\Documents\GitHub\bunto [danger ≡]>
```

Results in Travis:
```travis
e:end:19a49070:start=1486202496609422675,finish=1486202496614325237,duration=4902562

$ bundle exec danger
bundler: failed to load command: danger (/home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/bin/danger)

Danger::DSLError: 
[!] Invalid `Dangerfile` file: undefined local variable or method `pr_author' for #<Danger::Dangerfile:0x00000001348fe0>
 #  from Dangerfile:11
 #  -------------------------------------------
 #  if github.pr_body.length < 5
 >    warn("Please provide a changelog summary in the Pull Request description @#{pr_author}")
 #  end
 #  -------------------------------------------
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:68:in `method_missing'
  Dangerfile:11:in `block in parse'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:199:in `eval'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:195:in `parse'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:272:in `run'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/executor.rb:27:in `run'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/lib/danger/commands/runner.rb:66:in `run'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/gems/danger-4.2.1/bin/danger:5:in `<top (required)>'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/bin/danger:23:in `load'
  /home/travis/build/bunto/bunto/vendor/bundle/ruby/2.3.0/bin/danger:23:in `<top (required)>'

The command "bundle exec danger" failed and exited with 1 during .
Your build has been stopped.
```

## What did you expect to happen?
Running your Dangerfile without it crashing.

## What happened instead?
💥

## Your Environment

* Which CI are you running on? **Travis CI**
* Are you running the latest version of Danger? **Yes**
* What is your Dangerfile?

```ruby
# We generally try to avoid big PRs
warn("Big PR") if git.lines_of_code > 500

# Show a warning for PRs that are Work In Progress
if (github.pr_body + github.pr_title).include?("WIP")
  warn("Pull Request is Work in Progress")
end

# Contributors should always provide a changelog when submitting a PR
if github.pr_body.length < 5
  warn("Please provide a changelog summary in the Pull Request description @#{pr_author}")
end

# We want contributors to create an issue first before submitting a PR
# Exceptions are version bumps
if !github.pr_title.downcase.include?('version bump') &&
   !github.pr_body.include?("https://github.com/bunto/bunto/issues/") &&
   github.pr_body.match(/#\d+/).nil?
  warn("Before submitting a Pull Request, please create an issue on GitHub to discuss the change. Please add a link to the issue in the PR body.")
end
 ```

*Cheers,*
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by hanneskaeufler** [comment]
Doesn't it have to be `github.pr_author` rather than `pr_author` in the following line?

```ruby
  warn("Please provide a changelog summary in the Pull Request description @#{pr_author}")
```

**Comment by SuriyaaKudoIsc** [comment]
@hanneskaeufler 👍 Thank you! It works!
