### ISSUE TITLE
The last version of Danger (4.2.1) doesn't seem to work fine with GitHub Enterprise

### ISSUE THREAD

**Issue by vincentisambart** [danger/danger#725]
# Report

## What did you do?

Run `danger local`

## What did you expect to happen?

Display some status. And it does it I use version 4.0.5

## What happened instead?

An exception was raised.

```
Running your Dangerfile against this PR - https://ghe.xxxxx.xx/myorg/myrepo/pull/9999
Turning on --verbose

/Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://ghe.xxxxx.xx/api/v3/repos/myorg/myrepo/pulls/9999/reviews?per_page=100: 404 - Not Found // See: https://developer.github.com/enterprise/2.8/v3 (Octokit::NotFound)
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:290:in `fetch'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:195:in `process'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:142:in `call!'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-http-cache-2.0.0/lib/faraday/http_cache.rb:115:in `call'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/octokit-4.6.2/lib/octokit/connection.rb:84:in `paginate'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/request_sources/github/octokit_pr_review.rb:34:in `pull_request_reviews'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/request_sources/github/github.rb:69:in `review'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/plugins/dangerfile_github_plugin.rb:111:in `review'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:132:in `block (2 levels) in method_values_for_plugin_hashes'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:120:in `map'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:120:in `block in method_values_for_plugin_hashes'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:116:in `each'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:116:in `flat_map'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:116:in `method_values_for_plugin_hashes'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:149:in `print_known_info'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/danger_core/dangerfile.rb:173:in `parse'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/lib/danger/commands/local.rb:109:in `run'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Users/vincent-isambart/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/danger-4.2.1/bin/danger:5:in `<top (required)>'
	from /Users/vincent-isambart/.rbenv/versions/2.3/bin/danger:22:in `load'
	from /Users/vincent-isambart/.rbenv/versions/2.3/bin/danger:22:in `<main>'
```

## Your Environment

* Which CI are you running on?

Running locally.

* Are you running the latest version of Danger?

Yes (4.2.1)

* What is your Dangerfile?

```ruby
message("Hello, this worked")
```

**Comment by vincentisambart** [comment]
Note that GitHub Enterprise currently does not have an API for reviews, so it's not surprising to get a 404 when trying to access it.
If I was using `github.review` I would indeed be expecting an error, I'm not and but the error seems to be in the initialization code.
