### ISSUE TITLE
danger pr fails: cannot find your git remote

### ISSUE THREAD

**Issue by php-coder** [danger/danger#744]
I'm trying `danger pr` and it doesn't work:
```console
$ danger pr 
Ignoring eventmachine-1.0.8 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.8
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring yajl-ruby-1.2.1 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.1
/home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/ci_source/support/pull_request_finder.rb:33:in `check_if_any_pull_request!': No recent Pull Requests found for this repo, danger requires at least one Pull Request for the local mode. (RuntimeError)
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/ci_source/support/pull_request_finder.rb:15:in `call'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/ci_source/local_git_repo.rb:100:in `found_pull_request'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/ci_source/local_git_repo.rb:45:in `initialize'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/environment_manager.rb:30:in `new'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/pr.rb:48:in `new'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/pr.rb:48:in `run'
	from /home/coder/.gem/ruby/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/bin/danger:5:in `<top (required)>'
	from /home/coder/bin/danger:22:in `load'
	from /home/coder/bin/danger:22:in `<main>'
```

When I'm trying to see available options it fails with error:
```console
$ danger pr -h
Ignoring eventmachine-1.0.8 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.8
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring yajl-ruby-1.2.1 because its extensions are not built.  Try: gem pristine yajl-ruby --version 1.2.1
/home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/ci_source/local_git_repo.rb:61:in `raise_error_for_missing_remote': danger cannot find your git remote, please set a remote. And the repository must host on GitHub.com or GitHub Enterprise. (RuntimeError)
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/ci_source/local_git_repo.rb:43:in `initialize'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/environment_manager.rb:30:in `new'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/pr.rb:48:in `new'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/pr.rb:48:in `run'
	from /home/coder/.gem/ruby/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/bin/danger:5:in `<top (required)>'
	from /home/coder/bin/danger:22:in `load'
	from /home/coder/bin/danger:22:in `<main>'
```

Why she couldn't find remote? There is `origin` that she could use:
```console
$ git remote --verbose show 
Shkarin	https://github.com/Shkarin/mystamps-1 (fetch)
Shkarin	https://github.com/Shkarin/mystamps-1 (push)
bodom91	https://github.com/bodom91/mystamps (fetch)
bodom91	https://github.com/bodom91/mystamps (push)
origin	git@github.com:php-coder/mystamps.git (fetch)
origin	git@github.com:php-coder/mystamps.git (push)
```

**Comment by AnandWalvekar** [comment]
I have cloned the repo from bitbucket and getting same error.
