### ISSUE TITLE
How to fix "Commit xyz doesn't exist"

### ISSUE THREAD

**Issue by php-coder** [danger/danger#745]
`danger local` started to fails for me with the following error:
```console
$ danger local 
Running your Dangerfile against this PR - https://github.com/php-coder/mystamps/pull/533
Turning on --verbose

fatal: --unshallow on a complete repository does not make sense
/home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/scm_source/git_repo.rb:58:in `raise_if_we_cannot_find_the_commit': Commit 2a98ef46 doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed. (RuntimeError)
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/scm_source/git_repo.rb:43:in `ensure_commitish_exists!'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/request_sources/github/github.rb:89:in `setup_danger_branches'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/environment_manager.rb:57:in `ensure_danger_branches_are_setup'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/dangerfile.rb:258:in `setup_for_running'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/danger_core/dangerfile.rb:269:in `run'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/local.rb:50:in `block in run'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/local_helpers/local_setup.rb:38:in `setup'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/lib/danger/commands/local.rb:49:in `run'
	from /home/coder/.gem/ruby/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /home/coder/.gem/ruby/gems/danger-4.2.2/bin/danger:5:in `<top (required)>'
	from /home/coder/bin/danger:22:in `load'
	from /home/coder/bin/danger:22:in `<main>'
```
Yes, I did a rebase and yes this commit doesn't exist but what to do now? I tried to specify option `--clear-http-cache` but it didn't help. How to fix this error? Where danger found this commit?

**Comment by orta** [comment]
This commit  reference `2a98ef46` would have come from the GitHub API as being either the [base or the head](https://github.com/danger/danger/blob/master/lib/danger/request_sources/github/github.rb#L84-L87) sha for your PR. Danger would [have looked](https://github.com/danger/danger/blob/master/lib/danger/scm_source/git_repo.rb#L65) for these inside the local git repo, and try to update if she can't find one

**Comment by orta** [comment]
Closing due to inactivity.

**Comment by fcy** [comment]
I'm having this problem but on Jenkins and not locally. I know why but not how to fix it, so I'm posting here to see if maybe help someone in the future.

As orta mentioned the commit is coming from GH API, in my case the missing one is the base. The base is the most recent `master` commit but when Jenkins checkout the PR it only fetches the branch to be tested so any commits in `master` that are newer than the branch being tested are not in the local clone.

I'm trying to find a way to make Jenkins include `master` on the checkout as well. I'll update here if I find anything.

I'm on Danger 5.3.4.

**Comment by zdenektopic** [comment]
Any change? I have this issue too with Jenkins and bitbucket

**Comment by fcy** [comment]
@zdenektopic I solved it by making Jenkins checkout master as well as the PR it is going to build. I'm on leave right now, I don't recall the exact setting but it was related to manually specifying extra ref specs and adding master to it.

**Comment by zdenektopic** [comment]
I have got past that now, I am stuck on:
> /Library/Ruby/Gems/2.0.0/gems/danger-5.4.0/lib/danger/scm_source/git_repo.rb:104:in `find_merge_base': Cannot find a merge base between 26f1d51abbf3c41362179254cd7c3e8e37ff752b and 890f88879b43d3e7feba10e7837f796e8fc9fa01. (RuntimeError)
