### ISSUE TITLE
bundle install failed .. 

### ISSUE THREAD

**Issue by leverdeterre** [danger/danger#766]
# Report

## What did you do?

ℹ Please replace this with what you did.
I follow the installation 
`git clone https://github.com/danger/danger.git`
`cd danger`
`bundle install`

## What did you expect to happen?

I was expected a full installation.

## What happened instead?

[!] There was an error parsing Gemfile: There was a RuntimeError while loading danger.gemspec: 
can t modify frozen String from /Users/me/danger/danger.gemspec:8:in block in <main>
. Bundler cannot continue.

  from /Users/me/danger/Gemfile:3  
  >  gemspec
  gem "danger-gitlab"

## Your Environment

* Running on macOSX Bundler version 1.10.6
* Bundler version 1.10.6
* ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

**Comment by orta** [comment]
Interesting! 

Can you try update bundler ( `gem install bundler` ) and see if that fixes it? I just tested on my machine with the same instructions and it installed ( Ruby: `ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin16.0]` bundler: `Bundler version 1.13.2`)

**Comment by leverdeterre** [comment]
I' have made some tests.

`gem install bundler`
>
Fetching: bundler-1.14.6.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

>> that smell bad ... but why not ?

`sudo chown -R jeromemorissard /Library/Ruby/Gems/`
`gem install bundler`
>
Fetching: bundler-1.14.6.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.
>> that smell very bad ... 


`gem install bundler -n /usr/local/bin`
Successfully installed bundler-1.14.6
Parsing documentation for bundler-1.14.6
1 gem installed
>> Ok cool, but after that bundle install keep failing.

`bundle -v`
Bundler version 1.10.6

`/usr/local/bin/bundle -v`
Bundler version 1.14.6

So I try to install bundle using this specific bin 
`/usr/local/bin/bundle install`
>> Bundle complete! 18 Gemfile dependencies, 70 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

Run the tests (555 exemples, 4 failed)
`/usr/local/bin/bundle exec rake spec`

Randomized with seed 26553

Danger::Bitrise
  #new
    sets the pull_request_id
    sets the repo_url
    sets the repo_slug
  .validates_as_pr?
    validates when the required env variables are set
    does not validate when the required env variables are not set
    does not validate when there isn't a PR
  supported_request_sources
    supports GitLab
    supports GitHub
  .validates_as_ci?
    does not validate when the required env variables are not set
    validates even when there is no PR
    validates when the required env variables are set

Danger::FindRepoInfoFromURL
  GitHub
    http with www works
    https works
  GitLab
    works with trailing slash
  #call
    no match
      returns nil
  Bitbucket
    bitbucket.com
      works with http + trailing slash
    bitbucket.org
      works

Danger::Local
  .options
    contains extra options for local command
  default options
    pr number is nil and clear_http_cache defaults to false
  prints help
    danger local -h prints help (FAILED - 1)
    danger local --help flag prints help (FAILED - 2)

Danger
  has a version number

Danger::DangerfileBitbucketServerPlugin
  plugin
    #pr_link
      has a fetched link to it self
    #base_commit
      has a fetched base commit
    #markdown_link
      creates a usable markdown link
    #html_link
      creates a usable html link (PENDING: Atlassian disabled inline HTML support for Bitbucket Server)
      handles #XX line numbers in the same format a the other plugins (PENDING: Atlassian disabled inline HTML support for Bitbucket Server)
    #head_commit
      has a fetched head commit
    #branch_for_base
      has a fetched branch for base
    #branch_for_head
      has a fetched branch for head
    #pr_author
      has a fetched author
    #pr_title
      has a fetched title
    #pr_json
      has a non empty json

Danger::GitRepo
  #diff_for_folder
    fetches if cannot find commits, raises if still can't find after fetched
  #exec
    run command with our env set
  lines of code
    handles code deletions as expected
    handles code insertions as expected
    #commits
      returns the commits
  with files
    handles adding a new file to a git repo
    handles modified as expected
    handles file deletions as expected
  Return Types
    #modified_files returns a FileList object
    #deleted_files returns a FileList object
    #added_files returns a FileList object

Danger::CircleCI
  .validates_as_ci?
    validates when the `CI_PULL_REQUEST` is not legit
    validates when all required env variables are set
    validates when the `CI_PULL_REQUEST` is missing
    does not validate when all required env variables are not set
  #supported_request_sources
    supports GitHub
  .validates_as_pr?
    does not validate if `CI_PULL_REQUEST` is empty
    doest not validate when required env variables are not set
    validates when required env variables are set
    with missing `CI_PULL_REQUEST`
      validates when required env variables are set
  #new
    does not get a PR id when it has a bad PR url
    sets the repo_slug
    sets the repo_url
    sets the pull_request_id
    with missing `CI_PULL_REQUEST`
      sets the repo_slug
      sets the pull_request_id

String
  #danger_pluralize
    returns '2 errors' when count = 2
    returns '0 errors' when count = 0
    returns '1 error' when count = 1
  #danger_truncate
    does not truncate strings that are on the limit
    does not truncate strings that are within the limit
    truncates strings exceeding the limit
  #danger_underscore
    converts properly

Danger::PrySetup
  #setup_pry
    doesn't copy a nonexistant Dangerfile
    copies the Dangerfile and appends bindings.pry
    warns when the pry gem is not installed

Danger::RequestSources::GitLab
  scm
    Sets up the scm
  the GitLab API endpoint
    allows the GitLab API endpoint to be overidden with `DANGER_GITLAB_API_BASE_URL`
    sets the default GitLab API endpoint
  validation
    does no validate as an API source when the API token is empty
    does no validate as an API source when there is no API token
    validates as an API source
  the GitLab host
    sets the default GitLab host
    allows the GitLab host to be overidden
  the GitLab API client
    respects overriding the API endpoint
    set the default API endpoint
    sets the provide token
  valid server response
    determines the correct base_commit
    sets its ignored_violations_from_pr
    sets its commits_json
    set its mr_json
    setups the danger branches
    #update_pull_request!
      creates a new comment when there is not one already
      existing comment
        creates a new comment instead of updating the existing one if --new-comment is provided
        updates the existing comment instead of creating a new one
      existing comment with no sticky messages
        removes the previous danger comment if there are no new messages

Danger::PluginLint
  runs the command

Danger::Jenkins
  with multibranch pipeline
    .validates_as_ci?
      validates even when `CHANGE_ID` is missing
      doesn't validate when require env variables are not set
      validates even when `CHANGE_ID` is empty
      validates when requierd env variables are set
    #new
      sets the pull_request_id
      sets the repo_url
    .validates_as_pr?
      doesn't validate_as_pr if pull_request_repo is the empty string
      validates when the required variables are set
      doesn't validate if `CHANGE_ID` is missing
    .repo_url()
      gets the BitBucket Server url
      gets the GitHub url
      gets the GitLab url
      gets the BitBucket url
  with GitLab
    .validates_as_pr?
      doesn't validate if `gitlabMergeRequestId` is missing
      doesn't validate_as_pr if pull_request_repo is the empty string
      validates when the required variables are set
      #new
        sets the pull_request_id
    .validates_as_ci?
      validates when required env variables are set
      doesn't validate when require env variables are not set
      validates even when `gitlabMergeRequestId` is missing
      validates even when `gitlabMergeRequestId` is empty
  #supported_request_sources
    supports GitLab
    supports BitBucket Cloud
    supports GitHub
    supports BitBucket Server
  #new
    repo slug
      gets out a repo slug from a BitBucket Server
      gets out a repo slug from a git+ssh repo
      get out a repo slug from a repo with dot in name
      gets out a repo slug from a https repo
      get out a repo slug from a repo with .git in name
  Multiple remotes support
    gets out the repo slug from GIT_URL_1
  with GitHub
    .validates_as_pr?
      validates when the required variables are set
      doesn't validate if `ghprbPullId` is missing
      doesn't validate_as_pr if pull_request_repo is the empty string
    #new
      sets the pull_request_id
    .validates_as_ci?
      doesn't validate when require env variables are not set
      validates even when `ghprbPullId` is empty
      validates when requierd env variables are set
      validates even when `ghprbPullId` is missing

Danger::TeamCity
  with GitLab
    .validates_as_pr?
      doesn't validate if `GITLAB_PULL_REQUEST_ID` is missing
      doesn't validate_as_pr if pull_request_repo is the empty string
      validates when the required variables are set
    #new
      sets the repo_slug
      sets the pull_request_id
      sets the repo_url
    .validates_as_ci?
      validates even when `GITLAB_PULL_REQUEST_ID` is missing
      doesn't validate when required env variables are not set
      validates even when `GITLAB_PULL_REQUEST_ID` is empty
      validates when required env variables are set
  with GitHub
    #new
      sets the repo_slug
      sets the pull_request_id
      sets the repo_url
    .validates_as_ci?
      validates even when `GITHUB_PULL_REQUEST_ID` is empty
      validates when required env variables are set
      validates even when `GITHUB_PULL_REQUEST_ID` is missing
      doesn't validate when require env variables are not set
    .validates_as_pr?
      doesn't validate_as_pr if pull_request_repo is the empty string
      validates when the required variables are set
      doesn't validate if `GITHUB_PULL_REQUEST_ID` is missing
  #supported_request_sources
    supports GitHub
    supports GitLab

Danger::FindRepoInfoFromLogs
  #call
    returns repo slug from logs
    specify remote in https
      returns repo slug from logs
    specify GitHub Enterprise URL
      returns repo slug from logs

Danger::Plugin
  should forward unknown method calls to the dangerfile
  creates an instance name based on the class name

Danger::PluginParser
  handles outputting a warning
  creates a set of warnings for fixtured plugins
  creates a set of errors for fixtured plugins
  fails when there are errors

Danger::Dangerfile
  keeps track of the original Dangerfile
  runs the ruby code inside the Dangerfile
  raises elegantly with bad ruby code inside the Dangerfile
  respects ignored violations
  verbose
    outputs metadata when verbose
    does not print metadata by default
  #post_results
    delegates to corresponding request source
  #print_results
    Prints out 3 lists
  #setup_for_running
    ensure branches setup and generate diff
  printing verbose metadata
    exposes no external attributes by default
    exposes core attributes
    exposes all external plugin attributes by default
    table metadata
      creates a table from a selection of external plugins DSL attributes info
      skips raw PR/MR JSON, and diffs
      creates a table from a selection of core DSL attributes info
  initializing plugins
    should add a plugin to the @plugins array
    should add an instance variable to the dangerfile

Danger::Drone
  does not validate when DRONE is not set
  validates when DRONE variable is set
  does not validate  PRwhen DRONE_PULL_REQUEST is set to non positive int value
  does not validate PR when DRONE_PULL_REQUEST is set to non int value
  gets the pull request ID
  gets out a repo slug and pull request number
  gets the repo address

Danger::CI
  .available_ci_sources
    returns list of CI subclasses

Danger::RequestSources::RequestSource
  the base request source
    validates when passed a corresponding repository with custom host
    doesn't validate when passed a wrong repository
    validates when passed a corresponding repository
  .source_name
    BitbucketCloud
      returns the name of request source
    GitHub
      returns the name of request source
    BitbucketCloud
      returns the name of request source
    GitLab
      returns the name of request source
  .available_source_names_and_envs
    returns list of items contains source name and envs

Danger::GemsResolver
  #call
    create gemfile, bundle, and returns

Danger::RequestSources::GitHubSource::ReviewResolver
  should_submit?
    when submission body is different to review body
      returns true
    when submission body the same as review has
      returns false

Danger::XcodeServer
  supported_request_sources
    supports GitHub
  .validates_as_pr?
    does not validate when the required env variables are not set
    validates when the required env variables are set
    does not validate when XCS_BOT_NAME does not contain BuildaBot
  #new
    sets the repo_url
    sets the repo_slug
    sets the pull_request_id
  .validates_as_ci?
    does not validate when the required env variables are not set
    validates when the required env variables are set
    validates when `XCS_BOT_NAME` does not contain `BuildaBot`

Danger::Runner
  default options
    sets instance variables accrodingly
  #run
    invokes Executor
    with custom CLI options passed in
      overrides default options
  without Dangerfile
    raises error

Danger::RequestSources::BitbucketServer
  #host
    sets the host specified by `DANGER_BITBUCKETSERVER_HOST`
  #pr_json
    has a non empty pr_json after `fetch_details`
    #pr_json[:title]
      has fetched the pull requests title
    #pr_json[:id]
      has fetched the same pull request id as ci_sources's `pull_request_id`
  #validates_as_api_source
    validates_as_api_source for non empty `DANGER_BITBUCKETSERVER_USERNAME` and `DANGER_BITBUCKETSERVER_PASSWORD`
  #new
    should not raise uninitialized constant error

GetIgnoredViolation
  #call
    Without specific ignore sentence
      returns empty array
    With specific ignore sentence
      returns content in the quotes
    With specific ignore sentence contains escapted quote
      returns content in the quotes

Danger::PluginFileResolver
  #resolve
    Given list of gems
      resolves for gems

Danger::RequestSources::GitHub
  valid server response
    raises an exception when the repo was moved from the git remote
    sets the ignored violations
    sets its pr_json
    sets its issue_json
    #organisation
      no valid value available doesn't crash
      valid value available
    commit status update
      fails when no head commit is set
      aborts when access to setting the status was denied but there were errors
      uses danger_id as context of status
      warns when access to setting the status was denied but no errors were reported
    #parse_message_from_row
      handles pulling out links that include the file / line when in the main Danger comment
      handles pulling out file info from an inline Danger comment
    branch setup
      setups the danger branches
      fetches when the branches are not in the local store
    #file_url
      returns a valid URL with more parameters
      returns a valid URL with the minimum parameters
    issue creation
      deletes existing comments if danger doesnt need to say anything and a custom danger_id is provided
      creates a new comment instead of updating the issue if --new-comment is provided
      updates the issue if no danger comments exist
      creates a comment if no danger comments exist
      deletes existing comments if danger doesnt need to say anything
      updates the issue if no danger comments exist and a custom danger_id is provided
    review
      when ask for review first time
        when there are danger review for PR
          returns the last review from danger
        when there are no danger review for PR
          returns a newly created review
      when running against github enterprise which doesn't support reviews
        returns an unsupported review instance
      when already asked for review
        returns the same review
    inline issues
      crosses out sticky comments
      removes inline comments if they are not included
      ingores out of range inline comments when in dismiss mode
      adds main comment when inline out of range
      adds new comments inline
      deletes all inline comments if there are no violations at all
    status message
      Shows an error messages when there are errors
      Deals with singualars in messages when errors and warnings
      Shows an error message when errors and warnings
      Shows a success message when no errors/warnings
  the github host
    sets a default GitHub host
    allows the GitHub host to be overridden
    #api_url
      allows the GitHub API host to be overridden with `DANGER_GITHUB_API_HOST` for backwards compatibility
      allows the GitHub API host to be overridden with `DANGER_GITHUB_API_BASE_URL`

Danger::Helpers::CommentsHelper
  #generate_comment
    supports markdown only without a table
    produces the expected comment when there are newlines
    some warnings with markdown, no errors
    produces the expected comment
    supports markdown code below the summary table
    no warnings, no errors, no messages
    a multiline warning with markdown, no errors
    counts only unresolved violations on the title
    uncrosses violations that were on the list and happened again
    needs to include generated_by_danger
    produces HTML that a CommonMark parser will accept inline
    deduplicates previous violations
    truncates comments which would exceed githubs maximum comment length
    some warnings, no errors
    sets data-sticky to true when a violation is sticky
    sets data-sticky to false when a violation is not sticky
    handles a custom danger_id
    crosses resolved violations and changes the title
    includes a random compliment
    produces a comment containing a summary
    some warnings, some errors
  #markdown_parser
    is a Kramdown::Document instance
  #parse_comment
    parses a comment with error and warnings removing strike tag
    ignores non-sticky violations when parsing a comment
    parse violations by kind
    parses a comment with error and warnings
    parses a comment with error
    handles data-danger-table to identify danger tables
  #violations_from_table
    finds violations
  #parse_tables_from_comment
    splits a single table comment
    splits a multi table comment
  #table
    produces table data
  #generate_description
    Handles no errors or warnings
    handles multiple errors and warning with pluralisation
    handles a single error and a single warning
  #table_kind_from_title
    errors
      handles singular
      handles lowercase
      handles plural
    warnings
      handles singular
      handles plural
      handles lowercase
    messages
      handles singular
      handles lowercase
      handles plural

Danger::Travis
  .validates_as_pr?
    validates when all Travis PR environment vars are set and Josh K says so
    does not validate when `TRAVIS_REPO_SLUG` is empty
    does not validate when `TRAVIS_PULL_REQUEST` is missing
    does not validate when `TRAVIS_PULL_REQUEST` is empty
    does not validate if `TRAVIS_PULL_REQUEST` is empty
    dost not validate when `TRAVIS_PULL_REQUEST` is `false`
    does not validate when `TRAVIS_REPO_SLUG` is missing
  #supported_request_sources
    supports GitHub
  .validates_as_ci?
    does not validate when Josh K is not around
    validates when `TRAVIS_REPO_SLUG` is empty
    validates when `TRAVIS_REPO_SLUG` is missing
    validates when `TRAVIS_PULL_REQUEST` is missing
    validates when all Travis environment vars are set and Josh K says so
    validates when `TRAVIS_PULL_REQUEST` is empty
  #new
    sets the repo_url
    sets the repo_slug
    sets the pull_request_id

Danger::FileList
  #include?
    returns false if nothing was found
    supports exact matches
    supports * for wildcards
    supports ? for single chars

Danger::PullRequestFinder
  #call
    merged and squash-and-merged both present
      returns the most recent one
    specify Pull Request ID
      squash and merge type Pull Request
        returns correct Pull Request ID and SHA1
      merge pull request type Pull Request
        returns correct Pull Request ID and SHA1
    with open Pull Request
      returns the opened Pull Request info
    specify api endpoint of octokit client
      By DANGER_GITHUB_API_HOST
      fallbacks to DANGER_GITHUB_API_BASE_URL
    not specified Pull Request ID
      merge pull request type Pull Request
        returns correct Pull Request ID and SHA1
      squash and merge type Pull Request
        returns correct Pull Request ID and SHA1
  #new
    translates $remote into boolean

Danger::DangerfileGitHubPlugin
  dsl
    html_link
      works with 3+ paths
      can show just a path
      works with 2 paths
      works with a single path

Danger::RequestSources::GitHubSource::Review
  when initialized with review json
    body
      returns a body from request review json
    status
      returns a status from request review json
    id
      returns an id of request review
  submit
    submits review request with correct body
    when there are no errors
      sapproves the pr
    when there are only markdowns
      approves the pr
    when there are errors
      suggests changes to the pr
    when there are only messages
      approves the pr
    when there are only warnings
      approves the pr
    when there are only errors
      suggests changes to the pr
  when initialized without review json
    body
      returns an empty string
    status
      returns a pending status
    id
      nil

Danger::CircleAPI
  uses Circle CI API to grab the url if available
  uses the new token DANGER_CIRCLE_CI_API_TOKEN if available
  gets out a repo slug, pull request number and commit refs when PR url is not found
  uses Circle CI API to and can tell you it's not a PR'

Danger::DangerfileGitLabPlugin
  #mr_json
    has the expected keys
    is set
  #mr_title
    sets the correct mr_title
  #branch_for_head
    sets the correct branch_for_head
  #branch_for_merge
    sets the correct branch_for_merge
  #mr_diff
    sets the mr_diff
  #mr_author
    sets the correct mr_author
  #html_link
    should render a html link to the given file
  #branch_for_base
    sets the correct branch_for_base
  #mr_body
    sets the correct mr_body
  #mr_labels
    sets the correct mr_labels

Danger::LocalGitRepo
  validates_as_ci?
    validates when run by danger local
    does not validate when run by danger local
  #new
    sets the pull_request_id
    squash and merge PR
      works
    no incorrect PR id
      raise an exception
    repo_slug
      gets the repo slug when it starts with git://
      does not set a repo_slug if the repo has a non-gh remote
      gets the repo slug when it uses git@
      gets the repo slug when it uses https
      gets the repo slug when it contains .git
      enterprise github repos
        does not set a repo_slug if provided with a github_host that is different from the remote
        does set a repo slug if provided with a github enterprise host
    forked PR
      works
    no PRs
      raise an exception
    multiple PRs
      handles finding the resulting PR

Danger::DangerfileGitPlugin
  fails init if the dangerfile's request source is not a GitRepo
  dsl
    gets deletions
    gets commits
    gets lines_of_code
    gets added_files
    gets modified_files
    gets deleted_files
    gets insertions
    getting info for a specific file
      returns file info when it exists
      returns nil when specific info does not exist
    getting diff for a specific file
      returns nil when a specific diff does not exist
      gets a specific diff

Danger::Semaphore
  #supported_request_sources
    supports GitHub
  .validates_as_pr?
    does not validate if `SEMAPHORE_REPO_SLUG` is missing
    does not validate if `PULL_REQUEST_NUMBER` is empty
    does not validate if `PULL_REQUEST_NUMBER` is missing
    validates when the expected valid_env variables are set
    does not validate if `SEMAPHORE_REPO_SLUG` is empty
  .validates_as_ci
    does not validated when some expected valid_env variables are missing
    validates when `SEMAPHORE_REPO_SLUG` is missing
    validates when the expected valid_env variables are set
    validates when `PULL_REQUEST_NUMBER` is missing
  #new
    sets the repo_url
    sets the pull_request_id
    sets the repo_slug

Danger::Buildkite
  #new
    sets the pull request id
    repo slug
      gets out a repo slug from a git+ssh repo
      gets out a repo slug from a https repo
  .validates_as_pr?
    validates when the required variables are set
    doesn't validate_as_pr if pull_request_repo is the empty string
    doesn not validate if `BUILDKITE_PULL_REQUEST_REPO` is missing
  .validates_as_ci?
    validates when required env variables are set
    validates even when `BUILDKITE_PULL_REQUEST_REPO` is empty
    validates even when `BUILDKITE_PULL_REQUEST_REPO` is missing
    doesnt validate when require env variables are not set
  #supported_request_sources
    supports GitHub
    supports GitLab

Danger::RubyGemsClient
  .latest_danger_version
    user does not have network connection
      returns dummy version
    rubygems.org is operational
      returns latest danger version
    rubygems.org is not operational
      returns dummy version
    rubygems.org returns wrong data
      returns dummy version

Danger::LocalSetup
  #setup
    exits when no applicable ci source was identified
    informs the user and runs the block
    turns on verbose if arguments wasn't passed
    does not evaluate Dangerfile if local repo wasn't found on github

Danger::GitLabCI
  valid envrionment
    .validates_as_pr?
      is valid
    #initialize
      sets the repo_slug
      sets the pull_request_id
    #supported_request_sources
      it is gitlab
    .validates_as_ci?
      is valid

Danger::EnvironmentManager
  stores circle in the source
  stores travis in the source
  skips push runs and only runs for pull requests
  creates a GitHub attr
  uses local git repo and github when running locally
  .local_ci_source
    loads Travis
    loads TeamCity
    loads Buildkite
    does not return a CI source with no ENV deets
    loads GitLab CI
    loads Semaphore
    loads Surf
    loads Jenkins
    loads Drone
    loads Circle
    loads Local Git Repo
    loads Xcode Server
    loads Bitrise
  .danger_head_branch
    returns danger_head
  #clean_up
    delete danger branches
  #meta_info_for_head
    returns last commit of danger head branch
  #pr?
    returns true if has a ci source
  Without API tokens
    includes all your env var keys
    handles throwing out all kinds of info when the repo url isnt recognised
    handles providing useful bitbucket info when the repo url is bitbuckety
    handles providing useful github info when the repo url is github
    handles providing useful gitlab info when the repo url is gitlab
    prints travis note in subtitle
    cannot find request source
      raises error
  .pr?
    loads Circle
    loads Local Git Repo
    loads Surf
    loads Xcode Server
    does not return a CI source with no ENV deets
    loads Travis
    loads Buildkite
    loads Drone
    loads TeamCity
    loads GitLab CI
    loads Semaphore
    loads Jenkins
    loads Bitrise
  #meta_info_for_base
    returns last commit of danger base branch
  .danger_base_branch
    returns danger_base

Danger::RequestSources::BitbucketCloud
  #new
    should not raise uninitialized constant error
  #pr_json
    has a non empty pr_json after `fetch_details`
    #pr_json[:id]
      has fetched the same pull request id as ci_sources's `pull_request_id`
    #pr_json[:title]
      has fetched the pull requests title
  #validates_as_api_source
    validates_as_api_source for non empty `DANGER_BITBUCKETCLOUD_USERNAME` and `DANGER_BITBUCKETCLOUD_PASSWORD`

Danger::RequestSources::BitbucketServerAPI
  #inspect
    masks password on inspect

Danger::PR
  takes the first argument as PR URL
    works
  prints help
    danger pr -h prints help (FAILED - 3)
    danger pr --help flag prints help (FAILED - 4)
  .options
    dangerfile can be set
    contains extra options for PR command
  default options
    pr url is nil and clear_http_cache defaults to false
  .summary
    returns the summary for PR command

Danger::PluginJSON
  outputs a plugins documentation as json

Danger::Comment
  .from_github
    initializes with GitHub comment data structure
  .from_gitlab
    initializes with Gitlab comment data structure
  #generated_by_danger?
    returns false when body NOT contains generated_by_{identifier}
    returns true when body contains generated_by_{identifier}

Danger::PluginReadme
  runs the command

Danger::Dangerfile::DSL
  #scm_provider
    GitHub
      is `:github`
    Bitbucket Server
      is `:bitbucket_server`
    GitLab
      is `:gitlab`
  #import
    #import_url
      rejects unencrypted plugins
      downloads a remote .rb file
    #import_local
      supports file globbing
      supports exact paths
      not raises an error when calling a plugin that's a subclass of Plugin
      raises an error when calling a plugin that's not a subclass of Plugin
  #import_dangerfile
    gitlab: 'repo/name', branch: 'custom-branch', path: 'path/to/Dangefile'
    github: 'repo/name'
    github: 'repo/name', branch: 'custom-branch', path: 'path/to/Dangefile'
    gem: 'name'
    defaults to org/repo and warns of deprecation
    path: 'path'
    gitlab: 'repo/name'

Danger::Executor
  a test for SwiftWeekly #89
    works
  #validate!
    NOT a PR
      exits with clear message
    without CI
Could not find the type of CI for Danger to run on.
      raises error with clear message
    with CI + is a PR
      not raises error on Xcode Server
      not raises error on Circle
      not raises error on Drone
      not raises error on Local Git Repo
      not raises error on Travis
      not raises error on Jenkins (GitLab)
      not raises error on Jenkins (GitHub)
      not raises error on TeamCity (GitLab)
      not raises error on GitLab CI
      not raises error on Surf
      not raises error on Bitrise
      not raises error on TeamCity (GitLab)
      not raises error on Buildkite
      not raises error on Semaphore

Danger::HTTPCache
  will default to a 300 second cache expiry
  will open a previous file by default
  will delete a key
  will allow setting a custom cache expiry
  will honor the TTL when a read attempt is made
  will write a key and timestamp
  will delete a previous file if told to

Danger::RequestSources::BitbucketCloudAPI
  #inspect
    masks password on inspect

Danger
  .danger_outdated?
    latest danger > local danger version
    latest danger < local danger version
  .gem_path
    when danger gem found
      returns danger gem path
    when danger gem folder not found
      raises an error
  when installed danger is outdated and an error is raised
    prints an upgrade message

Danger::Surf
  #new
    sets the repo_slug
    sets the pull_request_id
    sets the repo_url
  #supported_request_sources
    supports GitHub
  .validates_as_pr?
    validates when the expected valid_env variables are set
    does not validated when some expected valid_env variables are missing
  .validates_as_ci?
    validates when the expected valid_env variables are set
    does not validated when some expected valid_env variables are missing

Danger::PluginParser
  skips non-subclasses of Danger::Plugin
  outputs JSON for well documented subclasses of Danger::Plugin
  outputs JSON for badly documented subclasses of Danger::Plugin
  find subclasses of Danger::Plugin
  finds classes from inside the file
  creates method descriptions that make sense
  includes an example plugin

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Danger::DangerfileBitbucketServerPlugin plugin #html_link creates a usable html link
     # Atlassian disabled inline HTML support for Bitbucket Server
     # ./spec/lib/danger/plugins/dangerfile_bitbucket_server_plugin_spec.rb:65

  2) Danger::DangerfileBitbucketServerPlugin plugin #html_link handles #XX line numbers in the same format a the other plugins
     # Atlassian disabled inline HTML support for Bitbucket Server
     # ./spec/lib/danger/plugins/dangerfile_bitbucket_server_plugin_spec.rb:73


Failures:

  1) Danger::Local prints help danger local -h prints help
     Failure/Error: expect(stdout).to include "Usage"
       expected "" to include "Usage"
     # ./spec/lib/danger/commands/local_spec.rb:13:in `block (3 levels) in <top (required)>'

  2) Danger::Local prints help danger local --help flag prints help
     Failure/Error: expect(stdout).to include "Usage"
       expected "" to include "Usage"
     # ./spec/lib/danger/commands/local_spec.rb:8:in `block (3 levels) in <top (required)>'

  3) Danger::PR prints help danger pr -h prints help
     Failure/Error: expect(stdout).to include "Usage"
       expected "" to include "Usage"
     # ./spec/lib/danger/commands/pr_spec.rb:13:in `block (3 levels) in <top (required)>'

  4) Danger::PR prints help danger pr --help flag prints help
     Failure/Error: expect(stdout).to include "Usage"
       expected "" to include "Usage"
     # ./spec/lib/danger/commands/pr_spec.rb:8:in `block (3 levels) in <top (required)>'

Finished in 15.71 seconds (files took 1.32 seconds to load)
555 examples, 4 failures, 2 pending

Failed examples:

rspec ./spec/lib/danger/commands/local_spec.rb:11 # Danger::Local prints help danger local -h prints help
rspec ./spec/lib/danger/commands/local_spec.rb:6 # Danger::Local prints help danger local --help flag prints help
rspec ./spec/lib/danger/commands/pr_spec.rb:11 # Danger::PR prints help danger pr -h prints help
rspec ./spec/lib/danger/commands/pr_spec.rb:6 # Danger::PR prints help danger pr --help flag prints help

Randomized with seed 26553

**Comment by orta** [comment]
Yeah I feel like your Ruby install is borked, I'd recommend installing with a ruby version manager - either rvm/rbenv will do you fine.
