### ISSUE TITLE
Utilizing --verbose flag from bundle

### ISSUE THREAD

**Issue by Tristan-zimmerman** [danger/danger#774]
# Report

## Quick Note:
This less of a bug report and more of a feature request for more output if the `--verbose` flag is passed to bundler. Danger was working on some of our PRs, but not others, so I assume it might be something in our own configuration. I was hoping to be able to see what the out put to Github would have been so I could maybe identify the `UnprocessableEntity` it was complaining about.

Either way, thanks! Danger has been a very helpful tool. 👍 

## What did you do?
Ran `bundle exec danger` / `bundle exec danger --verbose` from Travis.

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
Expected it to run danger and report back to the Github PR.

## What happened instead?

ℹ Please replace this with of what happened instead.
Received an `UnprocessableEntity` error from Octokit:

```shell
2.56s$ bundle exec danger --verbose
/home/travis/.rvm/gems/ruby-2.3.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://api.github.com/repos/localmotors/forth/pulls/340/comments: 422 - Validation Failed (Octokit::UnprocessableEntity)
Error summary:
  resource: PullRequestReviewComment
  code: invalid
  field: position // See: https://developer.github.com/v3/pulls/comments/#create-a-comment
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.0.1/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.0.1/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.0.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.0.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.0.1/lib/faraday/connection.rb:386:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/faraday-0.12.0.1/lib/faraday/connection.rb:186:in `post'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/octokit-4.6.2/lib/octokit/connection.rb:28:in `post'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/octokit-4.6.2/lib/octokit/client/pull_requests.rb:211:in `create_pull_request_comment'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/request_sources/github/github.rb:316:in `block in submit_inline_comments_for_kind!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/request_sources/github/github.rb:331:in `reject!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/request_sources/github/github.rb:331:in `submit_inline_comments_for_kind!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/request_sources/github/github.rb:243:in `submit_inline_comments!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/request_sources/github/github.rb:153:in `update_pull_request!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/danger_core/dangerfile.rb:277:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/danger_core/executor.rb:27:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/lib/danger/commands/runner.rb:66:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/danger-4.3.1/bin/danger:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/danger:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/danger:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
The command "bundle exec danger --verbose" exited with 1.
Done. Your build exited with 1.
```

## Your Environment

* Which CI are you running on: *Travis*
* Are you running the latest version of Danger? *Yes, 4.3.1*
* What is your Dangerfile?

```ruby
require 'open3'

# Add lm-dev link
message "View this on LM-Dev at <a href=\"https://#{github.branch_for_head}.lm-dev.com\">https://#{github.branch_for_head}.lm-dev.com</a>"

# Check for PR status labels
has_status_label = false
github.pr_labels.each do |label|
  has_status_label = true if label.start_with?('STATUS:')
end
warn "Please use a STATUS label on this PR to reflect its status" if !has_status_label

# Does pull add migrations?
are_migrations_added = false
git.added_files.each { |fn| are_migrations_added = true if fn.include?('/migrations/') }

# Any model changes that don't have migrations?
Open3.popen3('git status --porcelain') do |stdin, stdout, stderr, wait_thr|
  exit_status = wait_thr.value
  unmade_migrations = false
  stdout.readlines.each do |line|
    unmade_migrations = true if line =~ /\?\? .*\/migrations\//
  end

  fail "There are model changes without committed migrations. Run `makemigrations`" if unmade_migrations
end

# package.json updated without yarn.lock?
if git.modified_files.include?('forth/package.json') && !git.modified_files.include?('forth/yarn.lock')
  fail "package.json modified without Yarn lockfile regenerated. Run `yarn`"
end

# Python linter
python_files = (git.added_files + git.modified_files).select{ |file| file.end_with? 'py' }.uniq
python_files.reject! { |file| file.match(/migrations\/\d+_auto_/) != nil }   # Don't lint auto migrations
if !python_files.empty?
  flake8 = "flake8 --ignore=E501,E221,E241 #{python_files.join(' ')}"
  Open3.popen3(flake8) do |stdin, stdout, stderr, wait_thr|
    exit_status = wait_thr.value

    stdout.readlines.each do |line|
      filename, lineno, pos, lint = line.split(':', 4)
      lint.strip!
      if lint =~ /^F\d\d\d /
        fail "(flake8) #{lint}", file: filename, line: lineno
      else
        warn "(flake8) #{lint}", file: filename, line: lineno
      end
    end
  end
end
```

**Comment by orta** [comment]
This sounds like a good idea, I wonder if we can wrap the parts of commenting on an issue with our own error handler that provides more info.

**Comment by litmon** [comment]
It error caused me too.
I tried to find the cause, but I could not found because of no more information.
I want to be able to see the error detail, and also I want to not fail to the CI job.
I propose the solution, [the code](https://github.com/danger/danger/blob/cec33ff1016b6612163799fa939d813cdc24c87f/lib/danger/request_sources/github/github.rb#L332-L333
) will change like below. How about this? @orta

```diff
if matching_comments.empty?
- client.create_pull_request_comment(ci_source.repo_slug, ci_source.pull_request_id, 
-     body, head_ref, m.file, position)
+ begin
+   client.create_pull_request_comment(ci_source.repo_slug, ci_source.pull_request_id,
+       body, head_ref, m.file, position)
+ rescue Octokit::UnprocessableEntity => e
+   // TODO show some error detail. ex. body, file, head_ref, and position
+   // sorry I don't know how to ouput logs in Danger project...
+
+   next false // next false(=not reject) because this comment has not completed
+ end
else
  # Remove the surviving comment so we don't strike it out
```

**Comment by orta** [comment]
That does sound good - I think in Danger we just use puts ( or maybe [Cork](https://github.com/CocoaPods/Cork) ) - that is fine. Yeah, this seems like a good idea to me @litmon 👍

**Comment by litmon** [comment]
Thanks😄 I will make the Pull Request.
