### ISSUE TITLE
Encoding::InvalidByteSequenceError

### ISSUE THREAD

**Issue by netbe** [danger/danger#826]
# Report

## What did you do?

Run `bundle exec danger`

## What did you expect to happen?

Running swiftlint and comment on PR on BitBucket Server (Stash)

## What happened instead?

```
bundler: failed to load command: danger (/Users/jenkins/.rbenv/versions/2.3.1/bin/danger)
Encoding::InvalidByteSequenceError: "\xE2" on US-ASCII
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/request_sources/bitbucket_server_api.rb:51:in `encode'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/request_sources/bitbucket_server_api.rb:51:in `to_json'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/request_sources/bitbucket_server_api.rb:51:in `post_comment'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/request_sources/bitbucket_server.rb:80:in `update_pull_request!'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/danger_core/dangerfile.rb:277:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/lib/danger/commands/runner.rb:66:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/danger-5.2.2/bin/danger:5:in `<top (required)>'
  /Users/jenkins/.rbenv/versions/2.3.1/bin/danger:23:in `load'
  /Users/jenkins/.rbenv/versions/2.3.1/bin/danger:23:in `<top (required)>'
Build step 'Execute shell' marked build as failure
```

## Your Environment

* Which CI are you running on? Jenkins ver. 2.62
* Are you running the latest version of Danger? yes, 5.2.2
* What is your Dangerfile?

  ```ruby
   message("Hello, this worked")

   swiftlint.lint_files
   wiftlint.lint_files inline_mode: true
  ```

**Comment by netbe** [comment]
Here's the body of the comment that fails:

```
"All green. Well done.\n\n| | 1 Message |\n|---|---|\n| \xE2\x9C\xA8 | Hello, this worked |\n\n\n\nGenerated by [Danger](https://danger.systems/ \"generated_by_danger\")\n"
```

**Comment by sleekybadger** [comment]
@netbe Hi, Thank you for reporting this issue. 

I created commit that can fix this. Can you please re run your build, but using latest commit from my fork? 

Here's how your `Gemfile.rb` should look like for this:

```
 gem 'danger', github: 'sleekybadger/danger',
                         branch: 'hotfix/invalid-encoding',
                         ref: 'e8b25040f98cca260a5a49a2504baed5898caf85'
```

**Comment by netbe** [comment]
@sleekybadger  thx, it does not crash anymore and publish to bitbucket.

However as you can see below, some characters are not posted correctly, not sure where the encoding should be modify to have the proper effect:

<img width="652" alt="screen shot 2017-05-29 at 10 22 24 am" src="https://cloud.githubusercontent.com/assets/254198/26534664/11533b7a-4459-11e7-91d0-98f9da63ae0c.png">

**Comment by sleekybadger** [comment]
@netbe yep, can you check your ruby encoding on jenkins server?

You can do this like this:

```
~ rbenv shell 2.3.1
~ irb
> __ENCODING__.to_s
> exit
~ rbenv shell --unset
```

If `__ENCODING__.to_s` will return something different than `UTF-8`, then this is the problem.

**Comment by netbe** [comment]
@sleekybadger it seems fine:

```
irb(main):001:0> __ENCODING__.to_s
=> "UTF-8"
irb(main):002:0>
```

Using ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14] with rbenv

**Comment by sleekybadger** [comment]
@netbe I want to try to enforce encoding when danger runs to `UTF-8` and then reset it to what it was before.

Can you update `Gemfile`?

```
gem 'danger', github: 'sleekybadger/danger', 
              branch: 'hotfix/invalid-encoding', 
              ref: '12e049770916dfd905abda099502efee9b1c5b67'
```

**Comment by netbe** [comment]
@sleekybadger that looks better:
<img width="448" alt="screen shot 2017-05-30 at 11 28 09 am" src="https://cloud.githubusercontent.com/assets/254198/26567100/255e6dba-452b-11e7-85eb-309b6060df35.png">

**Comment by netbe** [comment]
@sleekybadger  Ok I got a new error in `update_pull_request`:

```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and US-ASCII
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/danger-12e049770916/lib/danger/request_sources/bitbucket_server.rb:78:in `update_pull_request!'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/danger-12e049770916/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/danger-12e049770916/lib/danger/danger_core/dangerfile.rb:280:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/danger-12e049770916/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/danger-12e049770916/lib/danger/commands/runner.rb:66:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/danger-12e049770916/bin/danger:5:in `<top (required)>'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/danger:23:in `load'
  /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bin/danger:23:in `<top (required)>'
```

**Comment by sleekybadger** [comment]
@netbe unfortunately I did not find a way to reproduce your issue, but I found [thread](https://github.com/jruby/jruby/issues/290) about this problem on MRI and jruby. Looks like you can try to set locale to `en_US.UTF-8`.

More info about locale:
- https://linux.die.net/man/1/locale
- https://www.shellhacks.com/linux-define-locale-language-settings/

Hope this will help you 🙏 

P.S. I think you can use `danger` from rubygems again, cause not sure that I'll be able to work on this issue on rest of this week.

**Comment by sleekybadger** [comment]
@netbe P.S.S.
The only way in which i reproduced this:

```
~ irb
> "\xE2\x9C\xA8".encode("UTF-8")
=> "✨"

~ LANG=en_US.US-ASCII irb
> "\xE2\x9C\xA8".encode("UTF-8")
=> Encoding::UndefinedConversionError
```

**Comment by lukaskukacka** [comment]
I was getting a similar crash running Danger with Bitbucket Server on Jenkins.

This topic + the fact it worked fine locally on macOS was a hint is just locale issue.

So to get rid of the crash, just:

    export LC_ALL="en_US.UTF-8"

before you call Danger.

**Comment by omgitsbillryan** [comment]
I was able to use [`.scrub`](https://ruby-doc.org/core-2.4.0/String.html#method-i-scrub) to clean my output before calling `failure` or `warn`, e.g.

```
# Dangerfile

msg = "blah"
warn(msg.scrub('_'))
```
