### ISSUE TITLE
Invalid `Dangerfile` file: unknown keywords: organisation, repository, branch, path

### ISSUE THREAD

**Issue by adam-moss** [danger/danger#877]
# Report

## What did you do?
```sh
danger --verbose
```

## What did you expect to happen?

Danger runs local Dangerfile, importing and running shared Dangerfile

## What happened instead?
```sh
/home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:157:in `import_dangerfile_from_github': (Danger::DSLError)
[!] Invalid `Dangerfile` file: unknown keywords: organisation, repository, branch, path
 #  from Dangerfile:3
 #  -------------------------------------------
 #  
 >  danger.import_dangerfile(gitlab: "org/repo", branch: "branch/name")
 #  
 #  -------------------------------------------
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb:80:in `import_dangerfile'
	from Dangerfile:3:in `block in parse'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/dangerfile.rb:199:in `eval'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/dangerfile.rb:199:in `block in parse'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/dangerfile.rb:195:in `instance_eval'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/dangerfile.rb:195:in `parse'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/dangerfile.rb:272:in `run'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/danger_core/executor.rb:27:in `run'
	from /home/user/.gem/ruby/gems/danger-5.3.4/lib/danger/commands/runner.rb:66:in `run'
	from /usr/local/share/gems/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /home/user/.gem/ruby/gems/danger-5.3.4/bin/danger:5:in `<top (required)>'
	from /home/user/bin/danger:23:in `load'
	from /home/user/bin/danger:23:in `<main>'
ERROR: Job failed: exit status 1
```

## Your Environment

* Which CI are you running on?
GitLab CI
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?

  ```ruby
    message("Hello from local Dangerfile")
    danger.import_dangerfile(gitlab: "org/repo", branch: "branch/name")
  ```
  ```ruby
    message("Hello from shared Dangerfile")
  ```

**Comment by orta** [comment]
Interesting, I wonder if the GitLab request source doesn't support [the same options as GitHubs](https://github.com/danger/danger/blob/master/lib/danger/danger_core/plugins/dangerfile_danger_plugin.rb#L157) - want to take a look?

**Comment by adam-moss** [comment]
Looks like the method for GitLab is `file_contents` rather than `contents`, but when I put that in I then get `[!] Invalid `Dangerfile` file: undefined method `nil' for nil:NilClass`.

**Comment by fauzee93** [comment]
Please unknow

**Comment by koffeinfrei** [comment]
The method `def file_url(organisation: nil, repository: nil, branch: nil, path: nil)` is not overwritten in https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb. It uses the "abstract" one from https://github.com/danger/danger/blob/master/lib/danger/request_sources/request_source.rb#L76-L78:

```ruby
def file_url(_organisation: nil, _repository: nil, _branch: "master", _path: nil)
  raise "Subclass and overwrite file_url"
end
```
