### ISSUE TITLE
git revision fails

### ISSUE THREAD

**Issue by josete89** [danger/danger#904]
# Report

## What did you do?

danger

## What did you expect to happen?

 Running your Dangerfile without it crashing.

## What happened instead?

+ danger
sh: 2: 83182330e5aaf0f046323f8dfe6377ea63d75159^{commit}: not found
You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead
/usr/local/bundle/gems/git-1.3.0/lib/git/lib.rb:937:in `command': [31m (Danger::DSLError)
[!] Invalid `Dangerfile` file: git '--git-dir=/opt/jenkins/workspace/tration_feature_persistency-QZMBLPRGAKDHVA7NPFO6YBZLTO2TYAOSQBFS4F5NEVKXT7VA6S5A/.git' '--work-tree=/opt/jenkins/workspace/tration_feature_persistency-QZMBLPRGAKDHVA7NPFO6YBZLTO2TYAOSQBFS4F5NEVKXT7VA6S5A' diff '-p' 'bf63ba14b8c56055a5c0ee27bd6858dd9d80ab38
83182330e5aaf0f046323f8dfe6377ea63d75159' 'danger_head'  2>&1:fatal: ambiguous argument 'bf63ba14b8c56055a5c0ee27bd6858dd9d80ab38
83182330e5aaf0f046323f8dfe6377ea63d75159': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'[0m
 #  from Dangerfile:123
 #  -------------------------------------------
 #  
 >  if git.modified_files.include?("swagger.yml")
 #    warn("Swagger modified!")
 #  -------------------------------------------
	from /usr/local/bundle/gems/git-1.3.0/lib/git/lib.rb:351:in `diff_full'
	from /usr/local/bundle/gems/git-1.3.0/lib/git/diff.rb:103:in `cache_full'
	from /usr/local/bundle/gems/git-1.3.0/lib/git/diff.rb:108:in `process_full'
	from /usr/local/bundle/gems/git-1.3.0/lib/git/diff.rb:68:in `each'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb:75:in `select'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/plugins/dangerfile_git_plugin.rb:75:in `modified_files'
	from Dangerfile:123:in `block in parse'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/dangerfile.rb:200:in `eval'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/dangerfile.rb:196:in `parse'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/dangerfile.rb:273:in `run'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/danger_core/executor.rb:27:in `run'
	from /usr/local/bundle/gems/danger-5.4.3/lib/danger/commands/runner.rb:66:in `run'
	from /usr/local/bundle/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
	from /usr/local/bundle/gems/danger-5.4.3/bin/danger:5:in `<top (required)>'
	from /usr/local/bundle/bin/danger:23:in `load'
	from /usr/local/bundle/bin/danger:23:in `<main>'
## Your Environment

* Which CI are you running on? Jenkins
* Are you running the latest version of Danger? 5.5.0
* What is your Dangerfile?

  ```
if git.modified_files.include?("swagger.yml")
  warn("Swagger modified!")
end

fail("Big PR") if git.lines_of_code > 500
fail "Please re-submit this PR to develop, we may have already fixed your issue." if bitbucket_server.branch_for_base != "develop"

  ```

**Comment by JuanitoFatas** [comment]
> You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead

Could you try using `message` instead? Thanks!

**Comment by josete89** [comment]
this fixed the problem :) thanks

**Comment by josete89** [comment]
If want to use puts or something for debug that doesn't show in the pull request, what should I use?

**Comment by orta** [comment]
I'm a little surprised that removing `puts` fixed it - `puts` should work as normal, it's just that we wanted people to know it wouldn't appear in the danger message
