### ISSUE TITLE
URI::BadURIError: both URI are relative when running danger pr

### ISSUE THREAD

**Issue by Nef10** [danger/danger#925]
# Report

## What did you do?

Run `DANGER_GITHUB_API_HOST=MYTOKEN LOCAL_GIT_PR_URL=https://github.com/Nef10/MyProjectName/pull/8 bundle exec danger pr`

## What did you expect to happen?

Running my Dangerfile without crashing.

## What happened instead?

```
MyUsernames-MacBook-Pro-3:MyProjectName MyUsername$ DANGER_GITHUB_API_HOST=MYTOKEN LOCAL_GIT_PR_URL=https://github.com/Nef10/MyProjectName/pull/8 bundle exec danger pr
bundler: failed to load command: danger (/Users/MyUsername/.rbenv/versions/2.2.3/bin/danger)

URI::BadURIError: both URI are relative
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1100:in `rescue in merge'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1097:in `merge'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/connection.rb:416:in `build_exclusive_url'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:194:in `build_env'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.7.0/lib/octokit/connection.rb:19:in `get'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.7.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:68:in `remote_pull_request'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:49:in `pull_request'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:29:in `check_if_any_pull_request!'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:15:in `call'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/local_git_repo.rb:93:in `found_pull_request'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/local_git_repo.rb:45:in `initialize'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/danger_core/environment_manager.rb:30:in `new'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/commands/pr.rb:57:in `new'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/commands/pr.rb:57:in `run'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/MyUsername/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/bin/danger:5:in `<top (required)>'
  /Users/MyUsername/.rbenv/versions/2.2.3/bin/danger:23:in `load'
  /Users/MyUsername/.rbenv/versions/2.2.3/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? None, running local
* Are you running the latest version of Danger? Yes, `5.5.5`
* What is your Dangerfile?

  ```ruby
  xcov.report(minimum_coverage_percentage: 100.00)
  xcode_summary.report 'build/reports/errors.json'
  jazzy.check fail: :all
  ```
* **PR number 8 is not merged yet**

**Comment by orta** [comment]
I thought the URL for the PR went at the end of the command?

**Comment by Nef10** [comment]
`DANGER_GITHUB_API_HOST= MYTOKEN bundle exec danger pr https://github.com/Nef10/MyProjectName/pull/9` also leads to 
```
bundler: failed to load command: danger (/Users/Steffen/.rbenv/versions/2.2.3/bin/danger)
URI::BadURIError: both URI are relative
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1100:in `rescue in merge'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/2.2.0/uri/generic.rb:1097:in `merge'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/connection.rb:416:in `build_exclusive_url'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:194:in `build_env'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.7.0/lib/octokit/connection.rb:19:in `get'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/octokit-4.7.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:68:in `remote_pull_request'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:49:in `pull_request'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:29:in `check_if_any_pull_request!'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/support/pull_request_finder.rb:15:in `call'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/local_git_repo.rb:93:in `found_pull_request'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/ci_source/local_git_repo.rb:45:in `initialize'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/danger_core/environment_manager.rb:30:in `new'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/danger_core/environment_manager.rb:30:in `initialize'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/commands/pr.rb:57:in `new'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/lib/danger/commands/pr.rb:57:in `run'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/Steffen/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/danger-5.5.5/bin/danger:5:in `<top (required)>'
  /Users/Steffen/.rbenv/versions/2.2.3/bin/danger:23:in `load'
  /Users/Steffen/.rbenv/versions/2.2.3/bin/danger:23:in `<top (required)>'
```
