### ISSUE TITLE
Danger crash on Ruby 2.4.3

### ISSUE THREAD

**Issue by mylifeasdog** [danger/danger#933]
# Report

## What did you do?

`bundle exec danger`

## What did you expect to happen?

Running your Dangerfile without it crashing.

## What happened instead?

```
bundler: failed to load command: danger (/Users/distiller/project/vendor/bundle/ruby/2.4.0/bin/danger)
MultiJson::AdapterError: Did not recognize your adapter specification (dlopen(/Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext/parser.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.2.dylib
  Referenced from: /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext/parser.bundle
  Reason: image not found - /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext/parser.bundle).
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext.rb:7:in `require'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext.rb:7:in `<module:Ext>'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext.rb:6:in `<module:JSON>'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/json-2.1.0/lib/json/ext.rb:3:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json/adapters/json_gem.rb:1:in `require'

  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json/adapters/json_gem.rb:1:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:157:in `require'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:157:in `load_adapter_from_string_name'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:101:in `load_adapter'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:103:in `load_adapter'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:91:in `use'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:73:in `adapter'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:133:in `current_adapter'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/multi_json-1.12.2/lib/multi_json.rb:120:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/serializer.rb:62:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/serializer.rb:62:in `decode'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:125:in `decode_body'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/response.rb:18:in `initialize'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:107:in `new'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:107:in `call'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/octokit-4.7.0/lib/octokit/connection.rb:19:in `get'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/octokit-4.7.0/lib/octokit/client/pull_requests.rb:31:in `pull_request'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-5.5.5/lib/danger/request_sources/github/github.rb:117:in `fetch_details'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-5.5.5/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-5.5.5/lib/danger/danger_core/dangerfile.rb:266:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-5.5.5/lib/danger/danger_core/executor.rb:27:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-5.5.5/lib/danger/commands/runner.rb:66:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/gems/danger-5.5.5/bin/danger:5:in `<top (required)>'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/bin/danger:23:in `load'
  /Users/distiller/project/vendor/bundle/ruby/2.4.0/bin/danger:23:in `<top (required)>'
Exited with code 1
```

## Your Environment

* Which CI are you running on?
CircleCI
* Are you running the latest version of Danger?
Yes (5.5.5)
* What is your Dangerfile?

 ```ruby
  # Warn about develop branch
warn("Please target PRs to `develop` branch") if github.branch_for_base != "develop"

# Make it more obvious that a PR is a work in progress and shouldn't be merged yet
warn("PR is classed as Work in Progress") if github.pr_title.include? "[WIP]"

# Warn no CHANGELOG
#warn("No CHANGELOG changes made") if git.lines_of_code > 50 && !git.modified_files.include?("CHANGELOG.md")

# Warn essential files changes
warn(".gitignore changed") if git.modified_files.include?(".gitignore")
warn(".swiftlint.yml changed") if git.modified_files.include?(".swiftlint.yml")
warn(".circleci changed") if !git.modified_files.grep(/\.circleci/).empty?
warn("Cartfile changed") if git.modified_files.include?("Cartfile")
warn("Cartfile.resolved changed") if git.modified_files.include?("Cartfile.resolved")
warn("codecov.yml changed") if git.modified_files.include?("codecov.yml")
warn("Dangerfile changed") if git.modified_files.include?("Dangerfile")
warn("fastlane changed") if !git.modified_files.grep(/fastlane/).empty?
warn("Gemfile changed") if git.modified_files.include?("Gemfile")
warn("Gemfile.lock changed") if git.modified_files.include?("Gemfile.lock")
warn("Podfile changed") if git.modified_files.include?("Podfile")
warn("Podfile.lock changed") if git.modified_files.include?("Podfile.lock")

# Warn summary on pull request
if github.pr_body.length < 5
warn "Please provide a summary in the Pull Request description"
end

# If these are all empty something has gone wrong, better to raise it in a comment
if git.modified_files.empty? && git.added_files.empty? && git.deleted_files.empty?
fail "This PR has no changes at all, this is likely a developer issue."
end

# Warn when there is a big PR
warn("Big PR") if git.lines_of_code > 500

has_AnalyticService_changes = !git.modified_files.grep(/AnalyticService/).empty?
has_ApolloService_changes = !git.modified_files.grep(/ApolloService/).empty?
has_CredentialService_changes = !git.modified_files.grep(/CredentialService/).empty?
has_Entity_changes = !git.modified_files.grep(/Entity/).empty?
has_Interactor_changes = !git.modified_files.grep(/Interactor/).empty?
has_PaymentService_changes = !git.modified_files.grep(/PaymentService/).empty?
has_Utility_changes = !git.modified_files.grep(/Utility/).empty?

has_AnalyticService_tests_updated = !git.modified_files.grep(/AnalyticServiceTests/).empty?
has_ApolloService_tests_updated = !git.modified_files.grep(/ApolloServiceTests/).empty?
has_CredentialService_tests_updated = !git.modified_files.grep(/CredentialServiceTests/).empty?
has_Entity_tests_updated = !git.modified_files.grep(/EntityTests/).empty?
has_Interactor_tests_updated = !git.modified_files.grep(/InteractorTests/).empty?
has_PaymentService_tests_updated = !git.modified_files.grep(/PaymentServiceTests/).empty?
has_Utility_tests_updated = !git.modified_files.grep(/UtilityTests/).empty?

if has_AnalyticService_changes && !has_AnalyticService_tests_updated
    warn("The AnalyticService files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the AnalyticService changes.")
end
if has_ApolloService_changes && !has_ApolloService_tests_updated
warn("The ApolloService files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the ApolloService changes.")
end
if has_CredentialService_changes && !has_CredentialService_tests_updated
warn("The CredentialService files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the CredentialService changes.")
end
if has_Entity_changes && !has_Entity_tests_updated
warn("The Entity files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the Entity changes.")
end
if has_Interactor_changes && !has_Interactor_tests_updated
warn("The Interactor files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the Interactor changes.")
end
if has_PaymentService_changes && !has_PaymentService_tests_updated
warn("The PaymentService files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the PaymentService changes.")
end
if has_Utility_changes && !has_Utility_tests_updated
warn("The Utility files were changed, but the tests remained unmodified. Consider updating or adding to the tests to match the Utility changes.")
end

swiftlint.verbose = true
swiftlint.config_file = '/Users/distiller/project/.swiftlint.yml'
swiftlint.lint_files

junit.parse "fastlane/test_output/report.junit"
junit.report
```

**Comment by mylifeasdog** [comment]
Problem still occurred on Danger 5.5.6

**Comment by JuanitoFatas** [comment]
@mylifeasdog Hi, I saw an error: `MultiJson::AdapterError: Did not recognize your adapter specification`, could you [try to install any json engine](https://github.com/Restream/redmine_resque/issues/1#issuecomment-61710064)? Thank you.

**Comment by manicmaniac** [comment]
Since Danger has dropped support for Ruby <= 2.6, let me close this issue.
Feel free to reopen this issue if the problem still occurs with the latest Danger.
