### ISSUE TITLE
danger/ci_source/jenkins.rb:74:in `initialize': undefined method `match' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by dbwest** [danger/danger#935]
# Report

## What did you do?

ℹ Please replace this with what you did.
Kicked off a 'merge request' after following instructions to set up Danger with Jenkins and Gitlab

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
No stack trace

## What happened instead?

ℹ Please replace this with of what happened instead.
A stack trace.
Of interest:
c:/Ruby23/lib/ruby/gems/2.3.0/gems/danger-5.5.5/lib/danger/ci_source/jenkins.rb:74:in `initialize': undefined method `match' for nil:NilClass (NoMethodError)

## Your Environment

* Which CI are you running on?
Jenkins
* Are you running the latest version of Danger?
Yes
* What is your Dangerfile?

Fakefile below :):`

  ```ruby
CODE_COVERAGE_MINIMUM = 70 # percent
STYLE_VIOLATION_THRESHOLD = 10 # violations
CODE_QUALITY_GRADE_TO_MEET = 'A'.freeze # nothing less :)

ACCEPTABLE_GRADES = ['A'].freeze

def style_violation_count
  5
end

def code_coverage_percent
  70
end

def code_quality_letter_grade
  'A'
end

exceeds_style_violation_threshold = style_violation_count ? style_violation_count <= 10 : true
meets_code_coverage_standard = code_coverage_percent ? code_coverage_percent >= 70 : false
meets_code_quality_standard = code_quality_letter_grade ? ACCEPTABLE_GRADES.include?(code_quality_letter_grade) : false

fail('Too Many Style Violations') if exceeds_style_violation_threshold
fail('Code Coverage Not Above 70%') unless meets_code_coverage_standard
fail("Does not have a code quality of 'A'") unless meets_code_quality_standard

  ```
* What is your Jenkinsfile? :)
  ```
properties([
  [$class: 'GitLabConnectionProperty', gitLabConnection: 'gitlab'],
  buildDiscarder(
    logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '1', daysToKeepStr: '', numToKeepStr: '')
  )
])

node {

  println "Your ENV:"
  println env.dump
  println "Your params:"
  println params.dump

  checkout (changelog: true, poll: true, scm: [
           $class: 'GitSCM',
           branches: [[name: "danger"]],
           doGenerateSubmoduleConfigurations: false,
           extensions: [[
                   $class: 'PreBuildMerge',
                   options: [
                     fastForwardMode: 'FF',
                     mergeRemote: 'origin',
                     mergeStrategy: 'default',
                     mergeTarget: "master"
                   ]
           ]],
           submoduleCfg: [],
           userRemoteConfigs: [
                 [
                    credentialsId: '[my secret id is here]',
                    name: 'origin',
                    url: 'http://[my secret url is here]'
                 ]
           ]
  ])

  stage('bundle') {
    bat(/uru admin rm 233 && uru admin add c:\ruby23\bin/)
    bat(/uru 233 && gem install bundler/)
    bat(/uru 233 && chmod -R +w . && set HOME=c:\ && bundle/)
  }
  stage('rubocop') {
    bat(script: /bundle exec rubocop/, returnStatus: true)
  }
  stage('rubycritic') {
    bat(script: /bundle exec rubycritic --no-browser/, returnStatus: true)
  }
  stage('rspec') {
    bat(script: /bundle exec rspec/, returnStatus: true)
  }
  stage('danger') {
    env.gitlabMergeRequestIid = '1'
    bat(script: /bundle exec danger/, returnStatus: true)
  }
}

  ```

**Comment by orta** [comment]
Looks like an issue with pulling out your project URL: https://github.com/danger/danger/blob/a528a08e8c4b62b3417572dddecffd7858fd9eb4/lib/danger/ci_source/jenkins.rb#L74

Anything special there?

**Comment by dbwest** [comment]
looking

**Comment by dbwest** [comment]
does it get that use env vars?

**Comment by orta** [comment]
That sounds like it then, we could do with some better error handling here
