### ISSUE TITLE
Danger failing on VSTS

### ISSUE THREAD

**Issue by bsameh** [danger/danger#943]
# Report

## What did you do?
Ran 'danger --verbose' on VSTS CI

## What did you expect to happen?
Danger to report status successfully

## What happened instead?
Danger failed with the following error:
```bash
2018-01-17T14:46:31.8240680Z [command]/usr/local/bin/danger --verbose
2018-01-17T14:46:32.8259210Z /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '<html><head><title>Object moved</title></head><body>
2018-01-17T14:46:32.8276580Z  (JSON::ParserError)
2018-01-17T14:46:32.8298040Z <h2>Object moved to <a href="URL_OMITTED">here</a>.</h2>
2018-01-17T14:46:32.8320120Z </body></html>
2018-01-17T14:46:32.8339590Z '
2018-01-17T14:46:32.8364160Z 	from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/json/common.rb:156:in `parse'
2018-01-17T14:46:32.8385280Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/request_sources/vsts_api.rb:99:in `fetch_json'
2018-01-17T14:46:32.8406760Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/request_sources/vsts_api.rb:51:in `fetch_pr_json'
2018-01-17T14:46:32.8428070Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/request_sources/vsts.rb:52:in `fetch_details'
2018-01-17T14:46:32.8449510Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
2018-01-17T14:46:32.8470810Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/danger_core/dangerfile.rb:266:in `run'
2018-01-17T14:46:32.8491800Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/danger_core/executor.rb:27:in `run'
2018-01-17T14:46:32.8512770Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/lib/danger/commands/runner.rb:66:in `run'
2018-01-17T14:46:32.8533640Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
2018-01-17T14:46:32.8554510Z 	from /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.5.6/bin/danger:5:in `<top (required)>'
2018-01-17T14:46:32.8574840Z 	from /usr/local/bin/danger:23:in `load'
2018-01-17T14:46:32.8594870Z 	from /usr/local/bin/danger:23:in `<main>'
2018-01-17T14:46:32.8721100Z ##[error]/usr/local/bin/danger failed with return code: 1
2018-01-17T14:46:32.8771110Z ##[error]/usr/local/bin/danger failed with error: /usr/local/bin/danger failed with return code: 1
```
## Your Environment

* Which CI are you running on? **VSTS**
* Are you running the latest version of Danger? **Yes**
* What is your Dangerfile?

  ```ruby
  warn(“This is a test warning”)
  ```

I've provided both the DANGER_VSTS_API_TOKEN (permission is set to Code (read/write) and the DANGER_VSTS_HOST. 

I tried opening the omitted URL from the logs in a browser and it's landing me on a login page. It seems that they've changed something with the redirection flow? Unfortunately, I cannot provide the URL as it's private. 

Any help would be appreciated.

Thanks!

**Comment by orta** [comment]
I'm afraid this one is gonna be on you to debug and fix as I don't have a VSTS setup. Would recommend looking at either supporting some sort of redirect, or figuring out if you have the wrong URL in your ENV vars

**Comment by bsameh** [comment]
I've double checked the URL, it seems to be the correct one. I tried pointing it to the host itself as well as use the exact repository URL, neither worked.

I understand that support for VSTS was added via a PR, so I don't expect much support, was just wondering if anyone else has come across this.

Thanks @orta! :) Great library, by the way, works seamlessly on GitHub.

**Comment by orta** [comment]
Thanks - so the VSTS API is built entirely [inside Danger](https://github.com/danger/danger/blob/master/lib/danger/request_sources/vsts_api.rb) so maybe the answer is to try seeing if you can CURL some of the requests its making manually to verify they do what's expected?

**Comment by bsameh** [comment]
Will try that. Thanks!
