### ISSUE TITLE
Unable to load issue_comments when pull request is created from a fork

### ISSUE THREAD

**Issue by hujiko** [danger/danger#944]
# Report

## What did you do?

Running Danger on Jenkins when a Pull-Request was touched using this commands:
```
+ export GIT_URL=git@github.enterprise:myorg/myapp.git
+ export DANGER_GITHUB_HOST=github.enterprise
+ export DANGER_GITHUB_API_TOKEN=<our-api-token>
+ bundle exec danger
```

Given the prerequisites that:
The origin repo is public.
It has a fork, that is also public.
Somebody creates a pull request from the fork to the original repo.

## What did you expect to happen?

I expect Danger to load the comments belonging to the pull request using the correct URL containing not the forkers name in the url but the org that owns the repo.

## What happened instead?

Using Dangers method `issue_comments` Danger crashes like this:

> 
> [!] Invalid `Dangerfile` file: [31m
> [!] Invalid `Dangerfile` file: GET https://github.enterprise/api/v3/repos/< forking-person >/< my-repo >/issues/441/comments?per_page=100: 404 - Not Found // See: https://developer.github.com/enterprise/2.10/v3[0m
>  #  from /home/vagrant/.gem/ruby/2.4.0/gems/< internal-gem >/config/danger/Dangerfile:29
>  #  -------------------------------------------
>  #  # Add a reminder on how to skip QA
>  >  unless danger_check.skip_qa_reminder?
>  #  
>  #  -------------------------------------------
> [0m
>  #  from /home/vagrant/.gem/ruby/2.4.0/gems/< internal-gem >/config/danger/Dangerfile:29
>  #  -------------------------------------------
>  #   >   #  
>  #  -------------------------------------------
> 
>   /home/vagrant/.gem/ruby/2.4.0/gems/octokit-4.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
>   /home/vagrant/.gem/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:9:in `block in call'
>   /home/vagrant/.gem/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
>   /home/vagrant/.gem/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'

## Your Environment

* Which CI are you running on?
** I am using Jenkins CI
* Are you running the latest version of Danger?
** I am using Danger version 5.5.6
* What is your Dangerfile?

```ruby
require_relative "danger_check"
danger_check = DangerCheck.new(github, git)

# Check Jira reference
unless danger_check.ticket_reference?
  warn("Please reference the ticket number in your PR")
end

# Warn when there is a big PR
if danger_check.pr_too_big?
  warn("Your PR is pretty big. Consider splitting it.")
end

# Make it obvious that a PR is a work in progress and shouldn't be merged yet
fail("PR is classed as Work in Progress") if danger_check.wip?

# Add a reminder on how to skip QA
unless danger_check.skip_qa_reminder?

  github.api.add_comment(
    danger_check.repo,
    danger_check.issue_number,
    danger_check.skip_qa_reminder
  )

end

# And the skip_qa_reminder method looks like this:
def skip_qa_reminder?
  issue_comments.any? { |comment| comment[:body] == skip_qa_reminder }
end
```

My assumption:
Instead of loading the comments from here:
`https://github.enterprise/api/v3/repos/< forking-person >/< my-repo >/issues/441/comments?per_page=100`
It should try loading the comments from here:
`https://github.enterprise/api/v3/repos/< owning-org >/< my-repo >/issues/441/comments?per_page=100`

**Comment by orta** [comment]
Nice yeah, looks good, wanna try fix it? Wonder where it's picking up the wrong URL - we're not seeing this on regular GH
