### ISSUE TITLE
Gitlab html_link broken in v5.5.11

### ISSUE THREAD

**Issue by JanStevens** [danger/danger#969]
# Report

## What did you do?
Upgrade danger from v5.5.10 to v5.5.11

## What did you expect to happen?
It would run my danger file without crashing

## What happened instead?

```ruby
$ bundle exec danger --verbose --fail-on-errors=true
bundler: failed to load command: danger (/home/gitlab-runner/.ruby/vendor/ruby/2.5.0/bin/danger)
Danger::DSLError: 
[!] Invalid `Dangerfile` file: no implicit conversion of nil into String
 #  from Dangerfile:50
 #  -------------------------------------------
 #    if git.modified_files.include? file_to_mention
 >      warn "#{gitlab.html_link(file_to_mention)} was edited."
 #    end
 #  -------------------------------------------

  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb:196:in `+'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/plugins/dangerfile_gitlab_plugin.rb:196:in `html_link'
  Dangerfile:50:in `block (2 levels) in parse'
  Dangerfile:48:in `each'
  Dangerfile:48:in `block in parse'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/dangerfile.rb:200:in `eval'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/dangerfile.rb:196:in `instance_eval'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/dangerfile.rb:196:in `parse'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/dangerfile.rb:274:in `run'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/executor.rb:28:in `run'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/lib/danger/commands/runner.rb:68:in `run'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/gems/danger-5.5.11/bin/danger:5:in `<top (required)>'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/bin/danger:23:in `load'
  /home/gitlab-runner/.ruby/vendor/ruby/2.5.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on? Gitlab CI
* Are you running the latest version of Danger? Yes
* What is your Dangerfile?

 ```ruby
files_to_mention = ["Dangerfile", "Gemfile", "Gemfile.lock", '.rubocop.yml', '.rubocop_todo.yml', '.gitlab-ci.yml']
files_to_mention.each do |file_to_mention|
  if git.modified_files.include? file_to_mention
    warn "#{gitlab.html_link(file_to_mention)} was edited."
  end
end
 ```

It seems that following MR https://github.com/danger/danger/pull/963 broke it

**Comment by rymai** [comment]
I think that was probably broken before that. I will fix this bug.
