### ISSUE TITLE
GitLab EE: too many commits give ArgumentError: wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by bonkey** [danger/danger#976]
# Report

## What did you do?

We're using GitLab EE and just setting up Danger. Currently, the setup is basic and works totally perfect, until there are too many commits in merge request (possibly when they exceed 1 page / 20 elements). 

## What did you expect to happen?

Danger should work no matter how many commits are in a merge request.

## What happened instead?

After some time working with a merge request I saw danger started crashing without any obvious reason. Stack trace directed me to potentially amount of commits, as it was related to `paginated_response.rb`, and this way I reproduced behaviour just by committing dummy commits to a merge request:

```zsh
for i in {1..50} ; do
  date > .dummy-commit
  git commit -a -m "Commit #${i} ($(date))"
  git push
  sleep 60 # a job takes the most ~45 seconds to finish
done
```

This way I created 20 jobs which passed correctly:

```
Running with gitlab-runner 10.5.0 (80b03db9)
[...]
HEAD is now at a8ef5b5 Commit #17 (Wed Mar 28 11:10:47 CEST 2018)
[...]
$ export LANG=en_US.UTF-8
$ export LANGUAGE=en_US:en
$ export LC_ALL=en_US.UTF-8
$ brew update && brew install rbenv jq 2> /dev/null
[...]
$ rbenv install -s 2.5.0
$ eval "$(rbenv init -)"
$ rbenv shell 2.5.0
$ gem install --silent --no-document bundler
$ bundle install
[...]
Bundle complete! 5 Gemfile dependencies, 100 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle exec pod install
[...]
Pod installation complete! There are 34 dependencies from the Podfile and 36 total pods installed.
$ export PULL_REQUEST_ID=$(git ls-remote -q origin merge-requests\*\head | grep $CI_COMMIT_SHA | sed 's/.*refs\/merge-requests\/\([0-9]*\)\/head/\1/g')
$ bundle exec danger --verbose
Using config file: /Users/builder/builds/d744534e/0/team-x/app-ios-experiments/.swiftlint.yml
Swiftlint will be run from /Users/builder/builds/d744534e/0/team-x/app-ios-experiments
Swiftlint will lint the following files: 
linting with options: {:config=>"/Users/builder/builds/d744534e/0/team-x/app-ios-experiments/.swiftlint.yml", :reporter=>"json", :quiet=>true, :pwd=>"/Users/builder/builds/d744534e/0/team-x/app-ios-experiments"}
Received from Swiftlint: #<Danger::FileList:0x00007f897fee2310>
Job succeeded
```

and all 21-50 failed same way:

```
$ bundle exec danger --verbose
bundler: failed to load command: danger (/Users/builder/.rbenv/versions/2.5.0/bin/danger)
ArgumentError: wrong number of arguments (given 2, expected 1)
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/objectified_hash.rb:26:in `method_missing'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/error.rb:40:in `build_error_message'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/error.rb:16:in `initialize'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `exception'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `raise'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:64:in `validate'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/paginated_response.rb:84:in `next_page'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/paginated_response.rb:38:in `each_page'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.3.0/lib/gitlab/paginated_response.rb:45:in `auto_paginate'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.5.11/lib/danger/request_sources/gitlab.rb:111:in `fetch_details'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/environment_manager.rb:51:in `fill_environment_vars'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/dangerfile.rb:267:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.5.11/lib/danger/danger_core/executor.rb:28:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.5.11/lib/danger/commands/runner.rb:68:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.5.11/bin/danger:5:in `<top (required)>'
  /Users/builder/.rbenv/versions/2.5.0/bin/danger:23:in `load'
  /Users/builder/.rbenv/versions/2.5.0/bin/danger:23:in `<top (required)>'
ERROR: Job failed: exit status 1
```

![screen shot 2018-03-28 at 14 37 39](https://user-images.githubusercontent.com/39100/38029548-69da8ed4-3296-11e8-9238-a7c78ae8e0d0.png)

## Your Environment

* Which CI are you running on?

Private instance of GitLab Enterprise Edition 10.6.0-ee

* Are you running the latest version of Danger?

Yes, 5.5.11

* What is your Dangerfile?

  ```ruby
  # swiftlint.binary_path = "Pods/SwiftLint/swiftlint"
  swiftlint.verbose = true

  warn("Big PR") if git.lines_of_code > 500

  swiftlint.lint_files fail_on_error: true, inline_mode: false
  ```

**Comment by orta** [comment]
Looks like it errors inside the gitlab gem, any clue if they have the same issues?
