### ISSUE TITLE
Danger Script seems to fail on BitRise when running on a PR where new binaries have been added

### ISSUE THREAD

**Issue by aelkady** [danger/danger#991]
# Report

## What did you do?

I have Danger set up to run with BitRise, my CI, every time a pull request is made.

## What did you expect to happen?

I expect Danger to run smoothly without any runtime errors on each PR/change to a PR.

## What happened instead?

Recently I noticed that some PRs would consistently fail with the following error:
```
bundler: failed to load command: danger (/usr/local/bin/danger)
JSON::GeneratorError: source sequence is illegal/malformed utf-8
  /usr/local/lib/ruby/gems/2.5.0/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `to_json'
  /usr/local/lib/ruby/gems/2.5.0/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `dump'
  /usr/local/lib/ruby/gems/2.5.0/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:25:in `dump'
  /usr/local/lib/ruby/gems/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
  /usr/local/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/serializer.rb:49:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/serializer.rb:49:in `encode'
  /usr/local/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:116:in `encode_body'
  /usr/local/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:96:in `block in call'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:384:in `block in run_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:398:in `block in build_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request.rb:26:in `block in create'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `tap'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request.rb:25:in `create'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:394:in `build_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:379:in `run_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `patch'
  /usr/local/lib/ruby/gems/2.5.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octokit/connection.rb:156:in `request'
  /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octokit/connection.rb:46:in `patch'
  /usr/local/lib/ruby/gems/2.5.0/gems/octokit-4.9.0/lib/octokit/client/issues.rb:292:in `update_comment'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/lib/danger/request_sources/github/github.rb:198:in `update_pull_request!'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/lib/danger/danger_core/dangerfile.rb:321:in `post_exception'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/lib/danger/danger_core/dangerfile.rb:285:in `rescue in run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/lib/danger/danger_core/dangerfile.rb:271:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/lib/danger/danger_core/executor.rb:28:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/lib/danger/commands/runner.rb:68:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-5.6.1/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:23:in `load'
  /usr/local/bin/danger:23:in `<top (required)>'
```
After doing some debugging on my end I concluded that this happens on PRs where there are new binaries added in the pull request (such as `png` or `zip` files). Happy to elaborate more if necessary.

## Your Environment

* Which CI are you running on?
BitRise
* Are you running the latest version of Danger?
Yes. 5.6.1.
* What is your Dangerfile?

```
# Realm modification check
(git.modified_files + git.added_files - %w(Dangerfile)).each do |file|
  next unless File.file?(file)
  contents = File.read(file)
  if contents =~ /\w*RLMObject/
    warn 'It looks like you have created/modified an object which subclasses RLMObject. Please ensure you have created a Realm migration'
    break
  end
end

# Login/Register Flow change
has_login_or_register_changes = (git.modified_files + git.added_files + git.deleted_files).any? { |file| file.include?('thm-ios-iphone/Login') }
if has_login_or_register_changes
  message 'It looks like you are changing the login/register flow of the app. Please QA the SSO login/register flow as well.'
end

# Folder structure check
if not git.added_files.empty?
  message 'Please ensure that your new files respect the existing folder structure'
end

# Warn when there are merge conflicts in the diff
if git.commits.any? { |c| c.message =~ /^Merge branch 'master'/ }
  warn 'Please merge in develop to get rid of conflicts'
end

# Warn when there is a big PR
if git.lines_of_code > 500
  warn 'Big PR, please split up. Alternatively mark as a risky change.'
end

# Swiftlint
swiftlint.lint_files fail_on_error: true

# XCode Test Coverage
xcov.report(
   scheme: 'thm-ios-iphone-adhoc',
   workspace: './thm-ios-iphone.xcworkspace',
   minimum_coverage_percentage: 20.0,
   output_directory: '',
   exclude_targets: 'FBSnapshotTestCase.framework,
   KIF_Quick.framework,
   Mockingjay.framework,
   Nimble.framework,
   Nimble_Snapshots.framework,
   PromiseKit.framework,
   Quick.framework,
   URITemplate.framework,
   vendor.framework,
   SnapKit.framework',
)

# XCode Compiler Summary
xcode_summary.ignored_files = '**/Pods/**'
xcode_summary.ignored_results { |result|
  result.message.start_with? 'skipping copy phase strip' or
  result.message.include? 'has been modified since the precompiled header' or
  result.message.end_with? 'No such file or directory' or
  result.message.include? '/Pods/'
}
xcode_summary.report 'xcodebuild.json'
```

**Comment by v-ahadke** [comment]
I am facing similar issue when my PR contains images. This happens on Github as well https://github.com/danger/danger/issues/1055
