### ISSUE TITLE
GitlabCI: Danger fail when running on a PR

### ISSUE THREAD

**Issue by oderkach** [danger/danger#999]
# Report

## What did you do?

We have Danger set up to run with GitlabCI every time on a pull request.

## What did you expect to happen?

Danger should works without runtime error.

## What happened instead?

```ruby
bundler: failed to load command: danger (/Users/builder/.rbenv/versions/2.5.0/bin/danger)
Gitlab::Error::Parsing: The response is not a valid JSON
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:37:in `rescue in decode'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:34:in `decode'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:16:in `parse'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:10:in `block in <class:Request>'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/httparty-0.16.2/lib/httparty/request.rb:391:in `parse_response'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/httparty-0.16.2/lib/httparty/request.rb:359:in `block in handle_response'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/httparty-0.16.2/lib/httparty/response.rb:25:in `parsed_response'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/error.rb:39:in `build_error_message'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/error.rb:16:in `initialize'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:64:in `exception'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:64:in `raise'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:64:in `validate'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/gitlab-4.4.0/lib/gitlab/client/merge_requests.rb:29:in `merge_requests'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/ci_source/gitlab_ci.rb:42:in `determine_merge_request_id'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/ci_source/gitlab_ci.rb:31:in `validates_as_pr?'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/danger_core/environment_manager.rb:15:in `pr?'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/danger_core/executor.rb:62:in `validate_pr!'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/danger_core/executor.rb:46:in `validate!'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/danger_core/executor.rb:21:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/lib/danger/commands/runner.rb:68:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /Users/builder/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/danger-5.6.2/bin/danger:5:in `<top (required)>'
  /Users/builder/.rbenv/versions/2.5.0/bin/danger:23:in `load'
  /Users/builder/.rbenv/versions/2.5.0/bin/danger:23:in `<top (required)>'
```

## Your Environment

* Which CI are you running on?
GitlabCI
* Are you running the latest version of Danger?
Yes, 5.6.2
* What is your Dangerfile?

  ```ruby
  # Warn when there is a big PR
  warn("Big PR") if git.lines_of_code > 500

  swiftlint.lint_files

  ```

**Comment by brodock** [comment]
@oderkach have you set-up `DANGER_GITLAB_API_TOKEN` variable in the CI Variables configuration?

**Comment by oderkach** [comment]
@brodock Yes. By the way it works correctly with version `5.5.13`.

**Comment by orta** [comment]
this seems to live entirely in the gitlab gem, maybe it needs an update, or that the version of the API you have deployed is giving unexpected results

**Comment by martiall** [comment]
I think the bug is located in gitlab_ci.rb line 42:

`merge_requests = client.merge_requests(project_path, state: :opened)`

According to [Gitlab API documentation - List project merge requests](https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests) the parameter must be the project id and not the project path.

Seems that the bug was introduced by commit e78cb621d8855cc43342a77e8fc62a8098a10637

**Comment by jorgifumi** [comment]
Hi, I have been experiencing same problem using Bitrise on my company's Hosted Gitlab and after a lot of research, I've noticed that when running locally with Bitrise CLI it works!
Finally I think I have found the root of the problem and is this: https://gitlab.com/gitlab-org/gitlab-ce/issues/35079
Hope can help someone else.
